// Date: 5/14/2017 4:45:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ACRAction extends ModelBase
{
  //fields
    ModelRenderer ACRAction1;
    ModelRenderer ACRAction2;
    ModelRenderer ACRAction3;
    ModelRenderer ACRAction4;
  
  public ACRAction()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      ACRAction1 = new ModelRenderer(this, 0, 0);
      ACRAction1.addBox(0F, 0F, 0F, 5, 1, 1);
      ACRAction1.setRotationPoint(0F, 0F, 0F);
      ACRAction1.setTextureSize(128, 64);
      ACRAction1.mirror = true;
      setRotation(ACRAction1, 0F, 0F, 0F);
      ACRAction2 = new ModelRenderer(this, 0, 0);
      ACRAction2.addBox(0F, 0F, 0F, 3, 1, 2);
      ACRAction2.setRotationPoint(0F, 0F, 0.5F);
      ACRAction2.setTextureSize(128, 64);
      ACRAction2.mirror = true;
      setRotation(ACRAction2, 0F, 0F, 0F);
      ACRAction3 = new ModelRenderer(this, 0, 0);
      ACRAction3.addBox(0F, 0F, 0F, 1, 1, 2);
      ACRAction3.setRotationPoint(2.6F, 0F, 0.5F);
      ACRAction3.setTextureSize(128, 64);
      ACRAction3.mirror = true;
      setRotation(ACRAction3, 0F, 0F, 0F);
      ACRAction4 = new ModelRenderer(this, 0, 0);
      ACRAction4.addBox(0F, 0F, 0F, 2, 1, 1);
      ACRAction4.setRotationPoint(5F, 0F, 1F);
      ACRAction4.setTextureSize(128, 64);
      ACRAction4.mirror = true;
      setRotation(ACRAction4, 0F, -2.342252F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    ACRAction1.render(f5);
    ACRAction2.render(f5);
    ACRAction3.render(f5);
    ACRAction4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
