// Date: 6/28/2019 3:54:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ACRHandGuard extends ModelBase
{
  //fields
    ModelRenderer handguard1;
    ModelRenderer handguard2;
    ModelRenderer handguard3;
    ModelRenderer handguard4;
    ModelRenderer handguard5;
    ModelRenderer handguard6;
    ModelRenderer handguard7;
    ModelRenderer handguard8;
    ModelRenderer handguard9;
    ModelRenderer handguard10;
    ModelRenderer handguard11;
    ModelRenderer handguard12;
    ModelRenderer handguard13;
    ModelRenderer handguard14;
    ModelRenderer handguard15;
    ModelRenderer handguard16;
    ModelRenderer handguard17;
    ModelRenderer handguard18;
    ModelRenderer handguard19;
    ModelRenderer handguard20;
    ModelRenderer handguard21;
    ModelRenderer handguard22;
    ModelRenderer handguard23;
    ModelRenderer handguard24;
    ModelRenderer handguard25;
    ModelRenderer handguard26;
    ModelRenderer handguard27;
    ModelRenderer handguard28;
    ModelRenderer handguard29;
    ModelRenderer handguard30;
    ModelRenderer handguard31;
    ModelRenderer handguard32;
  
  public ACRHandGuard()
  {
      textureWidth = 512;
      textureHeight = 256;
    
      handguard1 = new ModelRenderer(this, 0, 0);
      handguard1.addBox(0F, 0F, 0F, 1, 3, 24);
      handguard1.setRotationPoint(0.3F, -15.4F, -49F);
      handguard1.setTextureSize(256, 256);
      handguard1.mirror = true;
      setRotation(handguard1, 0F, 0F, 0F);
      handguard2 = new ModelRenderer(this, 0, 0);
      handguard2.addBox(0F, 0F, 0F, 1, 3, 24);
      handguard2.setRotationPoint(-4.3F, -15.4F, -49F);
      handguard2.setTextureSize(256, 256);
      handguard2.mirror = true;
      setRotation(handguard2, 0F, 0F, 0F);
      handguard3 = new ModelRenderer(this, 0, 0);
      handguard3.addBox(0F, 0F, 0F, 1, 2, 2);
      handguard3.setRotationPoint(0.3F, -14.4F, -25F);
      handguard3.setTextureSize(256, 256);
      handguard3.mirror = true;
      setRotation(handguard3, 0F, 0F, 0F);
      handguard4 = new ModelRenderer(this, 0, 0);
      handguard4.addBox(0F, 0F, 0F, 1, 2, 2);
      handguard4.setRotationPoint(-4.3F, -14.4F, -25F);
      handguard4.setTextureSize(256, 256);
      handguard4.mirror = true;
      setRotation(handguard4, 0F, 0F, 0F);
      handguard5 = new ModelRenderer(this, 0, 0);
      handguard5.addBox(0F, 0F, 0F, 1, 1, 26);
      handguard5.setRotationPoint(-4.3F, -13.1F, -49F);
      handguard5.setTextureSize(256, 256);
      handguard5.mirror = true;
      setRotation(handguard5, 0F, 0F, 0F);
      handguard6 = new ModelRenderer(this, 0, 0);
      handguard6.addBox(0F, 0F, 0F, 1, 1, 26);
      handguard6.setRotationPoint(0.3F, -13.1F, -49F);
      handguard6.setTextureSize(256, 256);
      handguard6.mirror = true;
      setRotation(handguard6, 0F, 0F, 0F);
      handguard7 = new ModelRenderer(this, 0, 0);
      handguard7.addBox(0F, 0F, 0F, 2, 1, 26);
      handguard7.setRotationPoint(-2.7F, -11.3F, -49F);
      handguard7.setTextureSize(256, 256);
      handguard7.mirror = true;
      setRotation(handguard7, 0F, 0F, 0F);
      handguard8 = new ModelRenderer(this, 0, 0);
      handguard8.addBox(0F, 0F, 0F, 1, 1, 26);
      handguard8.setRotationPoint(-1.3F, -11.3F, -49F);
      handguard8.setTextureSize(256, 256);
      handguard8.mirror = true;
      setRotation(handguard8, 0F, 0F, 0F);
      handguard9 = new ModelRenderer(this, 0, 0);
      handguard9.addBox(0F, 0F, 0F, 1, 1, 3);
      handguard9.setRotationPoint(-1.3F, -10.6F, -27F);
      handguard9.setTextureSize(256, 256);
      handguard9.mirror = true;
      setRotation(handguard9, 0F, 0F, 0F);
      handguard10 = new ModelRenderer(this, 0, 0);
      handguard10.addBox(0F, 0F, 0F, 2, 1, 3);
      handguard10.setRotationPoint(-2.7F, -10.6F, -27F);
      handguard10.setTextureSize(256, 256);
      handguard10.mirror = true;
      setRotation(handguard10, 0F, 0F, 0F);
      handguard11 = new ModelRenderer(this, 100, 0);
      handguard11.addBox(0F, 0F, 0F, 1, 1, 1);
      handguard11.setRotationPoint(-1.2F, -10.8F, -26F);
      handguard11.setTextureSize(256, 256);
      handguard11.mirror = true;
      setRotation(handguard11, 0F, 0F, 0F);
      handguard12 = new ModelRenderer(this, 100, 0);
      handguard12.addBox(0F, 0F, 0F, 1, 1, 1);
      handguard12.setRotationPoint(-2.8F, -10.8F, -26F);
      handguard12.setTextureSize(256, 256);
      handguard12.mirror = true;
      setRotation(handguard12, 0F, 0F, 0F);
      handguard13 = new ModelRenderer(this, 0, 0);
      handguard13.addBox(0F, 0F, 0F, 1, 1, 24);
      handguard13.setRotationPoint(0.3F, -15.4F, -49F);
      handguard13.setTextureSize(256, 256);
      handguard13.mirror = true;
      setRotation(handguard13, 0F, 0F, -0.4089647F);
      handguard14 = new ModelRenderer(this, 0, 0);
      handguard14.addBox(-1F, 0F, 0F, 1, 1, 24);
      handguard14.setRotationPoint(-3.3F, -15.4F, -49F);
      handguard14.setTextureSize(256, 256);
      handguard14.mirror = true;
      setRotation(handguard14, 0F, 0F, 0.4089656F);
      handguard15 = new ModelRenderer(this, 0, 0);
      handguard15.addBox(0F, 0F, 0F, 1, 2, 24);
      handguard15.setRotationPoint(-4F, -15.8F, -49F);
      handguard15.setTextureSize(256, 256);
      handguard15.mirror = true;
      setRotation(handguard15, 0F, 0F, 0F);
      handguard16 = new ModelRenderer(this, 0, 0);
      handguard16.addBox(0F, 0F, 0F, 1, 2, 24);
      handguard16.setRotationPoint(0F, -15.8F, -49F);
      handguard16.setTextureSize(256, 256);
      handguard16.mirror = true;
      setRotation(handguard16, 0F, 0F, 0F);
      handguard17 = new ModelRenderer(this, 0, 0);
      handguard17.addBox(0F, 0F, 0F, 1, 2, 3);
      handguard17.setRotationPoint(-0.3F, -11F, -49F);
      handguard17.setTextureSize(256, 256);
      handguard17.mirror = true;
      setRotation(handguard17, 0F, 0F, -2.342252F);
      handguard18 = new ModelRenderer(this, 0, 0);
      handguard18.addBox(0F, 0F, 0F, 1, 2, 11);
      handguard18.setRotationPoint(-0.3F, -11F, -35F);
      handguard18.setTextureSize(256, 256);
      handguard18.mirror = true;
      setRotation(handguard18, 0F, 0F, -2.342252F);
      handguard19 = new ModelRenderer(this, 0, 0);
      handguard19.addBox(-1F, 0F, 0F, 1, 2, 11);
      handguard19.setRotationPoint(-2.7F, -11F, -35F);
      handguard19.setTextureSize(256, 256);
      handguard19.mirror = true;
      setRotation(handguard19, 0F, 0F, 2.342249F);
      handguard20 = new ModelRenderer(this, 0, 0);
      handguard20.addBox(-1F, 0F, 0F, 1, 2, 3);
      handguard20.setRotationPoint(-2.7F, -11F, -49F);
      handguard20.setTextureSize(256, 256);
      handguard20.mirror = true;
      setRotation(handguard20, 0F, 0F, 2.342249F);
      handguard21 = new ModelRenderer(this, 0, 0);
      handguard21.addBox(-1F, -0.5F, 0F, 1, 1, 11);
      handguard21.setRotationPoint(-2.7F, -11F, -46F);
      handguard21.setTextureSize(256, 256);
      handguard21.mirror = true;
      setRotation(handguard21, 0F, 0F, 2.342249F);
      handguard22 = new ModelRenderer(this, 0, 0);
      handguard22.addBox(-1F, 1.2F, 0F, 1, 1, 11);
      handguard22.setRotationPoint(-2.7F, -11F, -46F);
      handguard22.setTextureSize(256, 256);
      handguard22.mirror = true;
      setRotation(handguard22, 0F, 0F, 2.342249F);
      handguard23 = new ModelRenderer(this, 0, 0);
      handguard23.addBox(0F, -0.5F, 0F, 1, 1, 11);
      handguard23.setRotationPoint(-0.3F, -11F, -46F);
      handguard23.setTextureSize(256, 256);
      handguard23.mirror = true;
      setRotation(handguard23, 0F, 0F, -2.342249F);
      handguard24 = new ModelRenderer(this, 0, 0);
      handguard24.addBox(0F, 1.2F, 0F, 1, 1, 11);
      handguard24.setRotationPoint(-0.3F, -11F, -46F);
      handguard24.setTextureSize(256, 256);
      handguard24.mirror = true;
      setRotation(handguard24, 0F, 0F, -2.342249F);
      handguard25 = new ModelRenderer(this, 0, 0);
      handguard25.addBox(0F, 0.5F, 0F, 1, 1, 1);
      handguard25.setRotationPoint(-0.3F, -11F, -43F);
      handguard25.setTextureSize(256, 256);
      handguard25.mirror = true;
      setRotation(handguard25, 0F, 0F, -2.342252F);
      handguard26 = new ModelRenderer(this, 0, 0);
      handguard26.addBox(0F, 0.5F, 0F, 1, 1, 1);
      handguard26.setRotationPoint(-0.3F, -11F, -39F);
      handguard26.setTextureSize(256, 256);
      handguard26.mirror = true;
      setRotation(handguard26, 0F, 0F, -2.342252F);
      handguard27 = new ModelRenderer(this, 0, 0);
      handguard27.addBox(-1F, 0.5F, 0F, 1, 1, 1);
      handguard27.setRotationPoint(-2.7F, -11F, -43F);
      handguard27.setTextureSize(256, 256);
      handguard27.mirror = true;
      setRotation(handguard27, 0F, 0F, 2.342249F);
      handguard28 = new ModelRenderer(this, 0, 0);
      handguard28.addBox(-1F, 0.5F, 0F, 1, 1, 1);
      handguard28.setRotationPoint(-2.7F, -11F, -39F);
      handguard28.setTextureSize(256, 256);
      handguard28.mirror = true;
      setRotation(handguard28, 0F, 0F, 2.342249F);
      handguard29 = new ModelRenderer(this, 0, 0);
      handguard29.addBox(0F, 0F, 0F, 1, 2, 2);
      handguard29.setRotationPoint(-4.3F, -14.4F, -23F);
      handguard29.setTextureSize(256, 256);
      handguard29.mirror = true;
      setRotation(handguard29, -2.193538F, 0F, 0F);
      handguard30 = new ModelRenderer(this, 0, 0);
      handguard30.addBox(0F, 0F, 0F, 1, 2, 2);
      handguard30.setRotationPoint(0.3F, -14.4F, -23F);
      handguard30.setTextureSize(256, 256);
      handguard30.mirror = true;
      setRotation(handguard30, -2.193538F, 0F, 0F);
      handguard31 = new ModelRenderer(this, 0, 0);
      handguard31.addBox(0F, 1.4F, 0F, 1, 1, 1);
      handguard31.setRotationPoint(-4.3F, -14.4F, -23F);
      handguard31.setTextureSize(256, 256);
      handguard31.mirror = true;
      setRotation(handguard31, -2.193538F, 0F, 0F);
      handguard32 = new ModelRenderer(this, 0, 0);
      handguard32.addBox(0F, 1.4F, 0F, 1, 1, 1);
      handguard32.setRotationPoint(0.3F, -14.4F, -23F);
      handguard32.setTextureSize(256, 256);
      handguard32.mirror = true;
      setRotation(handguard32, -2.193538F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    handguard1.render(f5);
    handguard2.render(f5);
    handguard3.render(f5);
    handguard4.render(f5);
    handguard5.render(f5);
    handguard6.render(f5);
    handguard7.render(f5);
    handguard8.render(f5);
    handguard9.render(f5);
    handguard10.render(f5);
    handguard11.render(f5);
    handguard12.render(f5);
    handguard13.render(f5);
    handguard14.render(f5);
    handguard15.render(f5);
    handguard16.render(f5);
    handguard17.render(f5);
    handguard18.render(f5);
    handguard19.render(f5);
    handguard20.render(f5);
    handguard21.render(f5);
    handguard22.render(f5);
    handguard23.render(f5);
    handguard24.render(f5);
    handguard25.render(f5);
    handguard26.render(f5);
    handguard27.render(f5);
    handguard28.render(f5);
    handguard29.render(f5);
    handguard30.render(f5);
    handguard31.render(f5);
    handguard32.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
