// Date: 4/22/2017 11:00:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AKaction extends ModelBase
{
  //fields
    ModelRenderer Action1;
    ModelRenderer Action2;
    ModelRenderer Action3;
    ModelRenderer Action4;
    ModelRenderer Action5;
    ModelRenderer Action6;
    ModelRenderer Action7;
    ModelRenderer Action8;
    ModelRenderer Action9;
    ModelRenderer Action10;
    ModelRenderer Action11;
    ModelRenderer Action12;
  
  public AKaction()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Action1 = new ModelRenderer(this, 0, 0);
      Action1.addBox(0F, 0F, 0F, 1, 2, 13);
      Action1.setRotationPoint(-2.5F, -15F, -33.5F);
      Action1.setTextureSize(128, 64);
      Action1.mirror = true;
      setRotation(Action1, 0F, 0F, 0.1858931F);
      Action2 = new ModelRenderer(this, 0, 0);
      Action2.addBox(0F, 0F, 0F, 1, 2, 7);
      Action2.setRotationPoint(-3.5F, -13F, -33.5F);
      Action2.setTextureSize(128, 64);
      Action2.mirror = true;
      setRotation(Action2, 0F, 0F, 0F);
      Action3 = new ModelRenderer(this, 0, 0);
      Action3.addBox(0F, 0F, 0F, 1, 2, 6);
      Action3.setRotationPoint(-3.2F, -13F, -26.5F);
      Action3.setTextureSize(128, 64);
      Action3.mirror = true;
      setRotation(Action3, 0F, 0F, 0F);
      Action4 = new ModelRenderer(this, 0, 0);
      Action4.addBox(0F, 0F, 0F, 1, 2, 11);
      Action4.setRotationPoint(-3F, -13F, -20.5F);
      Action4.setTextureSize(128, 64);
      Action4.mirror = true;
      setRotation(Action4, 0F, 0F, 0F);
      Action5 = new ModelRenderer(this, 0, 0);
      Action5.addBox(0F, 0F, 0F, 1, 2, 2);
      Action5.setRotationPoint(-3.5F, -13F, -26.5F);
      Action5.setTextureSize(128, 64);
      Action5.mirror = true;
      setRotation(Action5, 0F, 0.1858931F, 0F);
      Action6 = new ModelRenderer(this, 0, 0);
      Action6.addBox(0F, 0F, 0F, 4, 1, 1);
      Action6.setRotationPoint(-7F, -12.2F, -33.5F);
      Action6.setTextureSize(128, 64);
      Action6.mirror = true;
      setRotation(Action6, 0F, 0F, 0F);
      Action7 = new ModelRenderer(this, 0, 0);
      Action7.addBox(0F, 0F, 0F, 1, 1, 7);
      Action7.setRotationPoint(-3.5F, -13F, -33.5F);
      Action7.setTextureSize(128, 64);
      Action7.mirror = true;
      setRotation(Action7, 0F, 0F, -0.5205006F);
      Action8 = new ModelRenderer(this, 0, 0);
      Action8.addBox(0F, 0F, 0F, 1, 1, 6);
      Action8.setRotationPoint(-3.2F, -13F, -26.5F);
      Action8.setTextureSize(128, 64);
      Action8.mirror = true;
      setRotation(Action8, 0F, 0F, -0.8551081F);
      Action9 = new ModelRenderer(this, 0, 0);
      Action9.addBox(0F, 0F, 0F, 1, 1, 13);
      Action9.setRotationPoint(-2.9F, -13.6F, -33.5F);
      Action9.setTextureSize(128, 64);
      Action9.mirror = true;
      setRotation(Action9, 0F, 0F, -0.5576792F);
      Action10 = new ModelRenderer(this, 0, 0);
      Action10.addBox(0F, 0F, 0F, 1, 1, 1);
      Action10.setRotationPoint(-7F, -12.8F, -33.5F);
      Action10.setTextureSize(128, 64);
      Action10.mirror = true;
      setRotation(Action10, 0F, 0F, 0F);
      Action11 = new ModelRenderer(this, 0, 0);
      Action11.addBox(0F, 0F, 0F, 1, 1, 1);
      Action11.setRotationPoint(-6F, -12.8F, -33.5F);
      Action11.setTextureSize(128, 64);
      Action11.mirror = true;
      setRotation(Action11, 0F, 0F, 0F);
      Action12 = new ModelRenderer(this, 0, 0);
      Action12.addBox(0F, 0F, 0F, 1, 1, 1);
      Action12.setRotationPoint(-5F, -12.8F, -33.5F);
      Action12.setTextureSize(128, 64);
      Action12.mirror = true;
      setRotation(Action12, 0F, 0F, 0.7435722F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Action1.render(f5);
    Action2.render(f5);
    Action3.render(f5);
    Action4.render(f5);
    Action5.render(f5);
    Action6.render(f5);
    Action7.render(f5);
    Action8.render(f5);
    Action9.render(f5);
    Action10.render(f5);
    Action11.render(f5);
    Action12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
