// Date: 6/22/2019 5:34:37 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AKDrum100 extends ModelBase {
    //fields
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
    ModelRenderer mag18;
    ModelRenderer mag19;
    ModelRenderer mag20;
    ModelRenderer mag21;
    ModelRenderer mag22;
    ModelRenderer mag23;
    ModelRenderer mag24;
    ModelRenderer mag25;
    ModelRenderer mag26;

    public AKDrum100() {
        textureWidth = 256;
        textureHeight = 128;

        mag1 = new ModelRenderer(this, 0, 0);
        mag1.addBox(0F, 2F, 0F, 4, 6, 7);
        mag1.setRotationPoint(-3.5F, -8F, -25F);
        mag1.setTextureSize(64, 32);
        mag1.mirror = true;
        setRotation(mag1, 0.185895F, 0F, 0F);
        mag2 = new ModelRenderer(this, 0, 0);
        mag2.addBox(0F, 2.6F, 0F, 3, 6, 2);
        mag2.setRotationPoint(-3F, -8.3F, -26.6F);
        mag2.setTextureSize(64, 32);
        mag2.mirror = true;
        setRotation(mag2, 0.185895F, 0F, 0F);
        mag3 = new ModelRenderer(this, 0, 0);
        mag3.addBox(0F, 0F, 0F, 4, 4, 8);
        mag3.setRotationPoint(-3.5F, -1.4F, -24.7F);
        mag3.setTextureSize(64, 32);
        mag3.mirror = true;
        setRotation(mag3, 0F, 0F, 0F);
        mag4 = new ModelRenderer(this, 0, 0);
        mag4.addBox(0F, 0F, 0F, 4, 4, 8);
        mag4.setRotationPoint(-10F, 5.1F, -24.7F);
        mag4.setTextureSize(64, 32);
        mag4.mirror = true;
        setRotation(mag4, 0F, 0F, 0F);
        mag5 = new ModelRenderer(this, 0, 0);
        mag5.addBox(0F, 0F, 0F, 4, 4, 1);
        mag5.setRotationPoint(-1.5F, 4.3F, -17.6F);
        mag5.setTextureSize(64, 32);
        mag5.mirror = true;
        setRotation(mag5, 0F, 0F, 0.7853982F);
        mag6 = new ModelRenderer(this, 0, 0);
        mag6.addBox(0F, 0F, 0F, 4, 4, 8);
        mag6.setRotationPoint(-10F, 5.1F, -24.7F);
        mag6.setTextureSize(64, 32);
        mag6.mirror = true;
        setRotation(mag6, 0F, 0F, -1.189716F);
        mag7 = new ModelRenderer(this, 0, 0);
        mag7.addBox(0F, 0F, 0F, 4, 4, 8);
        mag7.setRotationPoint(-3.5F, -1.4F, -24.7F);
        mag7.setTextureSize(64, 32);
        mag7.mirror = true;
        setRotation(mag7, 0F, 0F, 1.189716F);
        mag8 = new ModelRenderer(this, 0, 0);
        mag8.addBox(-4F, 0F, 0F, 4, 4, 8);
        mag8.setRotationPoint(0.5F, -1.4F, -24.7F);
        mag8.setTextureSize(64, 32);
        mag8.mirror = true;
        setRotation(mag8, 0F, 0F, -1.189721F);
        mag9 = new ModelRenderer(this, 0, 0);
        mag9.addBox(-4F, -4F, 0F, 4, 4, 8);
        mag9.setRotationPoint(0.5F, 15.6F, -24.7F);
        mag9.setTextureSize(64, 32);
        mag9.mirror = true;
        setRotation(mag9, 0F, 0F, 1.189721F);
        mag10 = new ModelRenderer(this, 0, 0);
        mag10.addBox(0F, -4F, 0F, 4, 4, 8);
        mag10.setRotationPoint(-3.5F, 15.6F, -24.7F);
        mag10.setTextureSize(64, 32);
        mag10.mirror = true;
        setRotation(mag10, 0F, 0F, -1.189721F);
        mag11 = new ModelRenderer(this, 0, 0);
        mag11.addBox(0F, -4F, 0F, 4, 4, 8);
        mag11.setRotationPoint(-10F, 9.1F, -24.7F);
        mag11.setTextureSize(64, 32);
        mag11.mirror = true;
        setRotation(mag11, 0F, 0F, 1.189721F);
        mag12 = new ModelRenderer(this, 0, 0);
        mag12.addBox(-4F, -4F, 0F, 4, 4, 8);
        mag12.setRotationPoint(7F, 9.1F, -24.7F);
        mag12.setTextureSize(64, 32);
        mag12.mirror = true;
        setRotation(mag12, 0F, 0F, -1.189721F);
        mag13 = new ModelRenderer(this, 0, 0);
        mag13.addBox(-4F, 0F, 0F, 4, 4, 8);
        mag13.setRotationPoint(7F, 5.1F, -24.7F);
        mag13.setTextureSize(64, 32);
        mag13.mirror = true;
        setRotation(mag13, 0F, 0F, 1.189721F);
        mag14 = new ModelRenderer(this, 0, 0);
        mag14.addBox(0F, 0F, 0F, 3, 2, 8);
        mag14.setRotationPoint(-7.2F, 0.1F, -24.7F);
        mag14.setTextureSize(64, 32);
        mag14.mirror = true;
        setRotation(mag14, 0F, 0F, 0.7853982F);
        mag15 = new ModelRenderer(this, 0, 0);
        mag15.addBox(0F, -1F, 0F, 2, 3, 8);
        mag15.setRotationPoint(-7.2F, 11.3F, -24.7F);
        mag15.setTextureSize(64, 32);
        mag15.mirror = true;
        setRotation(mag15, 0F, 0F, 0.7853982F);
        mag16 = new ModelRenderer(this, 0, 0);
        mag16.addBox(0F, 0F, 0F, 2, 3, 8);
        mag16.setRotationPoint(4.2F, 0.1F, -24.7F);
        mag16.setTextureSize(64, 32);
        mag16.mirror = true;
        setRotation(mag16, 0F, 0F, 0.7853982F);
        mag17 = new ModelRenderer(this, 0, 0);
        mag17.addBox(0F, -1F, 0F, 3, 2, 8);
        mag17.setRotationPoint(2.8F, 11.3F, -24.7F);
        mag17.setTextureSize(64, 32);
        mag17.mirror = true;
        setRotation(mag17, 0F, 0F, 0.7853982F);
        mag18 = new ModelRenderer(this, 0, 0);
        mag18.addBox(0F, 0F, 0F, 4, 4, 8);
        mag18.setRotationPoint(3F, 5.1F, -24.7F);
        mag18.setTextureSize(64, 32);
        mag18.mirror = true;
        setRotation(mag18, 0F, 0F, 0F);
        mag19 = new ModelRenderer(this, 0, 0);
        mag19.addBox(0F, 0F, 0F, 4, 4, 8);
        mag19.setRotationPoint(-3.5F, 11.6F, -24.7F);
        mag19.setTextureSize(64, 32);
        mag19.mirror = true;
        setRotation(mag19, 0F, 0F, 0F);
        mag20 = new ModelRenderer(this, 0, 0);
        mag20.addBox(0F, 0F, 0F, 10, 9, 8);
        mag20.setRotationPoint(-6.5F, 2.6F, -25F);
        mag20.setTextureSize(64, 32);
        mag20.mirror = true;
        setRotation(mag20, 0F, 0F, 0F);
        mag21 = new ModelRenderer(this, 0, 0);
        mag21.addBox(0F, 0F, 0F, 7, 1, 1);
        mag21.setRotationPoint(-5F, 2.1F, -25F);
        mag21.setTextureSize(64, 32);
        mag21.mirror = true;
        setRotation(mag21, 0F, 0F, 0F);
        mag22 = new ModelRenderer(this, 0, 0);
        mag22.addBox(0F, 0F, 0F, 7, 1, 1);
        mag22.setRotationPoint(-5F, 11.1F, -25F);
        mag22.setTextureSize(64, 32);
        mag22.mirror = true;
        setRotation(mag22, 0F, 0F, 0F);
        mag23 = new ModelRenderer(this, 0, 0);
        mag23.addBox(0F, 0F, 0F, 1, 6, 1);
        mag23.setRotationPoint(-7F, 4.1F, -25F);
        mag23.setTextureSize(64, 32);
        mag23.mirror = true;
        setRotation(mag23, 0F, 0F, 0F);
        mag24 = new ModelRenderer(this, 0, 0);
        mag24.addBox(0F, 0F, 0F, 1, 6, 1);
        mag24.setRotationPoint(3F, 4.1F, -25F);
        mag24.setTextureSize(64, 32);
        mag24.mirror = true;
        setRotation(mag24, 0F, 0F, 0F);
        mag25 = new ModelRenderer(this, 0, 0);
        mag25.addBox(0F, 0F, 0F, 3, 5, 1);
        mag25.setRotationPoint(-4.5F, 4.7F, -17.3F);
        mag25.setTextureSize(64, 32);
        mag25.mirror = true;
        setRotation(mag25, 0F, -0.1487144F, 0F);
        mag26 = new ModelRenderer(this, 0, 0);
        mag26.addBox(-4F, 0F, 0F, 6, 2, 8);
        mag26.setRotationPoint(-0.5F, -2F, -24.6F);
        mag26.setTextureSize(64, 32);
        mag26.mirror = true;
        setRotation(mag26, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        mag1.render(f5);
        mag2.render(f5);
        mag3.render(f5);
        mag4.render(f5);
        mag5.render(f5);
        mag6.render(f5);
        mag7.render(f5);
        mag8.render(f5);
        mag9.render(f5);
        mag10.render(f5);
        mag11.render(f5);
        mag12.render(f5);
        mag13.render(f5);
        mag14.render(f5);
        mag15.render(f5);
        mag16.render(f5);
        mag17.render(f5);
        mag18.render(f5);
        mag19.render(f5);
        mag20.render(f5);
        mag21.render(f5);
        mag22.render(f5);
        mag23.render(f5);
        mag24.render(f5);
        mag25.render(f5);
        mag26.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
