// Date: 5/21/2016 3:32:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AR15Iron extends ModelBase
{
  //fields
    ModelRenderer gun170;
    ModelRenderer gun171;
    ModelRenderer gun172;
    ModelRenderer gun174;
    ModelRenderer gun175;
    ModelRenderer gun176;
    ModelRenderer gun177;
    ModelRenderer gun178;
    ModelRenderer gun179;
    ModelRenderer gun180;
    ModelRenderer gun181;
    ModelRenderer gun182;
    ModelRenderer gun183;
    ModelRenderer gun184;
    ModelRenderer gun185;
    ModelRenderer gun186;
    ModelRenderer gun187;
    ModelRenderer gun188;
    ModelRenderer gun189;
    ModelRenderer gun190;
    ModelRenderer gun191;
    ModelRenderer gun192;
    ModelRenderer gun193;
    ModelRenderer gun194;
    ModelRenderer gun195;
  
  public AR15Iron()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun170 = new ModelRenderer(this, 0, 0);
      gun170.addBox(0F, 0F, 0F, 3, 1, 4);
      gun170.setRotationPoint(1F, -20.15F, -6.1F);
      gun170.setTextureSize(64, 32);
      gun170.mirror = true;
      setRotation(gun170, 0F, 0F, 0F);
      gun171 = new ModelRenderer(this, 0, 0);
      gun171.addBox(0F, 0F, 0F, 3, 1, 7);
      gun171.setRotationPoint(1F, -20.15F, 7.9F);
      gun171.setTextureSize(64, 32);
      gun171.mirror = true;
      setRotation(gun171, 0F, 0F, 0F);
      gun172 = new ModelRenderer(this, 0, 0);
      gun172.addBox(0F, 0F, 0F, 3, 2, 6);
      gun172.setRotationPoint(1F, -22.15F, 7.9F);
      gun172.setTextureSize(64, 32);
      gun172.mirror = true;
      setRotation(gun172, 0F, 0F, 0F);
      gun174 = new ModelRenderer(this, 0, 0);
      gun174.addBox(0F, 0F, 0F, 3, 2, 2);
      gun174.setRotationPoint(1F, -22.15F, -6.1F);
      gun174.setTextureSize(64, 32);
      gun174.mirror = true;
      setRotation(gun174, 0F, 0F, 0F);
      gun175 = new ModelRenderer(this, 0, 0);
      gun175.addBox(0F, 0F, 0F, 1, 1, 12);
      gun175.setRotationPoint(3F, -23.15F, -4.1F);
      gun175.setTextureSize(64, 32);
      gun175.mirror = true;
      setRotation(gun175, 0F, 0F, 0F);
      gun176 = new ModelRenderer(this, 0, 0);
      gun176.addBox(0F, 0F, 0F, 1, 2, 2);
      gun176.setRotationPoint(1F, -24.15F, 7.9F);
      gun176.setTextureSize(64, 32);
      gun176.mirror = true;
      setRotation(gun176, 0F, 0F, 0F);
      gun177 = new ModelRenderer(this, 0, 0);
      gun177.addBox(0F, 0F, 0F, 1, 2, 2);
      gun177.setRotationPoint(3F, -24.15F, 7.9F);
      gun177.setTextureSize(64, 32);
      gun177.mirror = true;
      setRotation(gun177, 0F, 0F, 0F);
      gun178 = new ModelRenderer(this, 0, 0);
      gun178.addBox(0F, 0F, 0F, 1, 14, 1);
      gun178.setRotationPoint(3F, -24.15F, 7.9F);
      gun178.setTextureSize(64, 32);
      gun178.mirror = true;
      setRotation(gun178, -1.524323F, 0F, 0F);
      gun179 = new ModelRenderer(this, 0, 0);
      gun179.addBox(0F, 0F, 0F, 1, 14, 1);
      gun179.setRotationPoint(1F, -24.15F, 7.9F);
      gun179.setTextureSize(64, 32);
      gun179.mirror = true;
      setRotation(gun179, -1.524323F, 0F, 0F);
      gun180 = new ModelRenderer(this, 0, 0);
      gun180.addBox(0F, 0F, 0F, 4, 1, 2);
      gun180.setRotationPoint(0.5F, -21.8F, 11.5F);
      gun180.setTextureSize(64, 32);
      gun180.mirror = true;
      setRotation(gun180, 0F, 0F, 0F);
      gun181 = new ModelRenderer(this, 0, 0);
      gun181.addBox(0F, 0F, 0F, 4, 1, 5);
      gun181.setRotationPoint(0.5F, -20F, 7.5F);
      gun181.setTextureSize(64, 32);
      gun181.mirror = true;
      setRotation(gun181, 0F, 0F, 0F);
      gun182 = new ModelRenderer(this, 0, 0);
      gun182.addBox(0F, 0F, 0F, 1, 1, 2);
      gun182.setRotationPoint(1F, -23.15F, -6.1F);
      gun182.setTextureSize(64, 32);
      gun182.mirror = true;
      setRotation(gun182, 0F, 0F, 0F);
      gun183 = new ModelRenderer(this, 0, 0);
      gun183.addBox(0F, 0F, 0F, 1, 1, 2);
      gun183.setRotationPoint(3F, -23.15F, -6.1F);
      gun183.setTextureSize(64, 32);
      gun183.mirror = true;
      setRotation(gun183, 0F, 0F, 0F);
      gun184 = new ModelRenderer(this, 0, 0);
      gun184.addBox(0F, 0F, 0F, 1, 1, 12);
      gun184.setRotationPoint(1F, -23.15F, -4.1F);
      gun184.setTextureSize(64, 32);
      gun184.mirror = true;
      setRotation(gun184, 0F, 0F, 0F);
      gun185 = new ModelRenderer(this, 0, 0);
      gun185.addBox(0F, 0F, 0F, 2, 1, 14);
      gun185.setRotationPoint(1.5F, -22.7F, -4.1F);
      gun185.setTextureSize(64, 32);
      gun185.mirror = true;
      setRotation(gun185, 0F, 0F, 0F);
      gun186 = new ModelRenderer(this, 0, 0);
      gun186.addBox(0F, 0F, 0F, 1, 2, 3);
      gun186.setRotationPoint(1.1F, -24F, 9.9F);
      gun186.setTextureSize(64, 32);
      gun186.mirror = true;
      setRotation(gun186, 0.1487144F, 0F, 0F);
      gun187 = new ModelRenderer(this, 0, 0);
      gun187.addBox(0F, 0F, 0F, 1, 2, 3);
      gun187.setRotationPoint(2.9F, -24F, 9.9F);
      gun187.setTextureSize(64, 32);
      gun187.mirror = true;
      setRotation(gun187, 0.1487144F, 0F, 0F);
      gun188 = new ModelRenderer(this, 0, 0);
      gun188.addBox(0F, 0F, 0F, 1, 2, 3);
      gun188.setRotationPoint(1.1F, -24F, 9.9F);
      gun188.setTextureSize(64, 32);
      gun188.mirror = true;
      setRotation(gun188, 0F, 0F, 0F);
      gun189 = new ModelRenderer(this, 0, 0);
      gun189.addBox(0F, 0F, 0F, 1, 2, 3);
      gun189.setRotationPoint(2.9F, -24F, 9.9F);
      gun189.setTextureSize(64, 32);
      gun189.mirror = true;
      setRotation(gun189, 0F, 0F, 0F);
      gun190 = new ModelRenderer(this, 0, 0);
      gun190.addBox(0F, 0F, 0F, 1, 1, 1);
      gun190.setRotationPoint(2.9F, -22.5F, 12.2F);
      gun190.setTextureSize(64, 32);
      gun190.mirror = true;
      setRotation(gun190, 0F, 0F, 0F);
      gun191 = new ModelRenderer(this, 0, 0);
      gun191.addBox(0F, 0F, 0F, 1, 1, 1);
      gun191.setRotationPoint(1.1F, -22.5F, 12.2F);
      gun191.setTextureSize(64, 32);
      gun191.mirror = true;
      setRotation(gun191, 0F, 0F, 0F);
      gun192 = new ModelRenderer(this, 0, 0);
      gun192.addBox(0F, 0F, 0F, 1, 1, 1);
      gun192.setRotationPoint(0.6F, -23.5F, 10.9F);
      gun192.setTextureSize(64, 32);
      gun192.mirror = true;
      setRotation(gun192, 0F, 0F, 0F);
      gun193 = new ModelRenderer(this, 0, 0);
      gun193.addBox(0F, 0F, 0F, 3, 2, 2);
      gun193.setRotationPoint(1F, -22.15F, 13.9F);
      gun193.setTextureSize(64, 32);
      gun193.mirror = true;
      setRotation(gun193, -0.8922867F, 0F, 0F);
      gun194 = new ModelRenderer(this, 0, 0);
      gun194.addBox(0F, 0F, 0F, 3, 1, 1);
      gun194.setRotationPoint(1F, -20.15F, 15.5F);
      gun194.setTextureSize(64, 32);
      gun194.mirror = true;
      setRotation(gun194, -2.490967F, 0F, 0F);
      gun195 = new ModelRenderer(this, 0, 0);
      gun195.addBox(0F, 0F, 0F, 3, 1, 1);
      gun195.setRotationPoint(1F, -20.15F, 14.5F);
      gun195.setTextureSize(64, 32);
      gun195.mirror = true;
      setRotation(gun195, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun170.render(f5);
    gun171.render(f5);
    gun172.render(f5);
    gun174.render(f5);
    gun175.render(f5);
    gun176.render(f5);
    gun177.render(f5);
    gun178.render(f5);
    gun179.render(f5);
    gun180.render(f5);
    gun181.render(f5);
    gun182.render(f5);
    gun183.render(f5);
    gun184.render(f5);
    gun185.render(f5);
    gun186.render(f5);
    gun187.render(f5);
    gun188.render(f5);
    gun189.render(f5);
    gun190.render(f5);
    gun191.render(f5);
    gun192.render(f5);
    gun193.render(f5);
    gun194.render(f5);
    gun195.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
