// Date: 2/22/2020 6:09:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AR57Receiver extends ModelBase
{
  //fields
    ModelRenderer receiver4;
    ModelRenderer receiver7;
    ModelRenderer receiver8;
    ModelRenderer receiver12;
    ModelRenderer receiver13;
    ModelRenderer receiver14;
    ModelRenderer receiver21;
    ModelRenderer receiver22;
    ModelRenderer receiver26;
    ModelRenderer receiver32;
    ModelRenderer receiver36;
    ModelRenderer receiver37;
    ModelRenderer receiver38;
    ModelRenderer receiver39;
    ModelRenderer receiver40;
    ModelRenderer receiver41;
    ModelRenderer receiver42;
    ModelRenderer receiver43;
    ModelRenderer receiver44;
    ModelRenderer receiver45;
    ModelRenderer receiver46;
    ModelRenderer receiver47;
    ModelRenderer receiver48;
    ModelRenderer receiver49;
    ModelRenderer receiver50;
    ModelRenderer receiver51;
    ModelRenderer receiver52;
    ModelRenderer receiver53;
    ModelRenderer receiver54;
    ModelRenderer receiver55;
    ModelRenderer receiver56;
    ModelRenderer receiver57;
    ModelRenderer receiver58;
    ModelRenderer receiver59;
    ModelRenderer receiver60;
    ModelRenderer receiver61;
    ModelRenderer receiver62;
    ModelRenderer receiver63;
    ModelRenderer receiver64;
  
  public AR57Receiver()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      receiver4 = new ModelRenderer(this, 0, 0);
      receiver4.addBox(0F, 0F, 0F, 1, 1, 9);
      receiver4.setRotationPoint(-0.3F, -13.3F, -22.7F);
      receiver4.setTextureSize(64, 32);
      receiver4.mirror = true;
      setRotation(receiver4, 0F, 0F, 0F);
      receiver7 = new ModelRenderer(this, 0, 0);
      receiver7.addBox(0F, 0F, 0F, 1, 1, 18);
      receiver7.setRotationPoint(-3.7F, -14.2F, -22.7F);
      receiver7.setTextureSize(64, 32);
      receiver7.mirror = true;
      setRotation(receiver7, 0F, 0F, 0F);
      receiver8 = new ModelRenderer(this, 0, 0);
      receiver8.addBox(-1F, 0F, 0F, 1, 1, 14);
      receiver8.setRotationPoint(-3.7F, -14.2F, -12.7F);
      receiver8.setTextureSize(64, 32);
      receiver8.mirror = true;
      setRotation(receiver8, 0F, 0F, -2.294746F);
      receiver12 = new ModelRenderer(this, 0, 0);
      receiver12.addBox(0F, 0F, 0F, 1, 1, 18);
      receiver12.setRotationPoint(-2.7F, -15.3F, -16.7F);
      receiver12.setTextureSize(64, 32);
      receiver12.mirror = true;
      setRotation(receiver12, 0F, 0F, 0F);
      receiver13 = new ModelRenderer(this, 0, 0);
      receiver13.addBox(0F, 0F, 0F, 1, 1, 18);
      receiver13.setRotationPoint(-1.3F, -15.3F, -16.7F);
      receiver13.setTextureSize(64, 32);
      receiver13.mirror = true;
      setRotation(receiver13, 0F, 0F, 0F);
      receiver14 = new ModelRenderer(this, 0, 0);
      receiver14.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver14.setRotationPoint(-0.3F, -15.1F, -22.7F);
      receiver14.setTextureSize(64, 32);
      receiver14.mirror = true;
      setRotation(receiver14, 0F, 0F, 0F);
      receiver21 = new ModelRenderer(this, 0, 0);
      receiver21.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver21.setRotationPoint(-2.7F, -15.3F, -22.7F);
      receiver21.setTextureSize(64, 32);
      receiver21.mirror = true;
      setRotation(receiver21, 0F, 0F, 0F);
      receiver22 = new ModelRenderer(this, 0, 0);
      receiver22.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver22.setRotationPoint(-1.3F, -15.3F, -22.7F);
      receiver22.setTextureSize(64, 32);
      receiver22.mirror = true;
      setRotation(receiver22, 0F, 0F, 0F);
      receiver26 = new ModelRenderer(this, 0, 0);
      receiver26.addBox(0F, 0F, 0F, 1, 1, 24);
      receiver26.setRotationPoint(-0.3F, -14.2F, -22.7F);
      receiver26.setTextureSize(64, 32);
      receiver26.mirror = true;
      setRotation(receiver26, 0F, 0F, 0F);
      receiver32 = new ModelRenderer(this, 0, 0);
      receiver32.addBox(0F, 0F, 0F, 1, 1, 1);
      receiver32.setRotationPoint(-3.7F, -13.3F, -22.7F);
      receiver32.setTextureSize(64, 32);
      receiver32.mirror = true;
      setRotation(receiver32, 0F, 0F, 0F);
      receiver36 = new ModelRenderer(this, 0, 0);
      receiver36.addBox(0F, 0F, 0F, 1, 1, 13);
      receiver36.setRotationPoint(-0.3F, -13.3F, -11.7F);
      receiver36.setTextureSize(64, 32);
      receiver36.mirror = true;
      setRotation(receiver36, 0F, 0F, 0F);
      receiver37 = new ModelRenderer(this, 0, 0);
      receiver37.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver37.setRotationPoint(-3.7F, -15.1F, -22.7F);
      receiver37.setTextureSize(64, 32);
      receiver37.mirror = true;
      setRotation(receiver37, 0F, 0F, 0F);
      receiver38 = new ModelRenderer(this, 0, 0);
      receiver38.addBox(0F, 0F, 0F, 1, 1, 14);
      receiver38.setRotationPoint(0.7F, -14.2F, -12.7F);
      receiver38.setTextureSize(64, 32);
      receiver38.mirror = true;
      setRotation(receiver38, 0F, 0F, 2.294753F);
      receiver39 = new ModelRenderer(this, 0, 0);
      receiver39.addBox(0F, 0F, 0F, 1, 1, 4);
      receiver39.setRotationPoint(-3.7F, -15.1F, -16.7F);
      receiver39.setTextureSize(64, 32);
      receiver39.mirror = true;
      setRotation(receiver39, 0F, 0F, 0F);
      receiver40 = new ModelRenderer(this, 0, 0);
      receiver40.addBox(0F, 0F, 0F, 1, 1, 4);
      receiver40.setRotationPoint(-0.3F, -15.1F, -16.7F);
      receiver40.setTextureSize(64, 32);
      receiver40.mirror = true;
      setRotation(receiver40, 0F, 0F, 0F);
      receiver41 = new ModelRenderer(this, 0, 0);
      receiver41.addBox(0F, 0.5F, 0F, 1, 1, 14);
      receiver41.setRotationPoint(0.7F, -14.2F, -12.7F);
      receiver41.setTextureSize(64, 32);
      receiver41.mirror = true;
      setRotation(receiver41, 0F, 0F, 2.294753F);
      receiver42 = new ModelRenderer(this, 0, 0);
      receiver42.addBox(-1F, 0.5F, 0F, 1, 1, 14);
      receiver42.setRotationPoint(-3.7F, -14.2F, -12.7F);
      receiver42.setTextureSize(64, 32);
      receiver42.mirror = true;
      setRotation(receiver42, 0F, 0F, -2.294746F);
      receiver43 = new ModelRenderer(this, 0, 0);
      receiver43.addBox(0F, 0F, 0F, 1, 1, 3);
      receiver43.setRotationPoint(-3.7F, -15.1F, -12.7F);
      receiver43.setTextureSize(64, 32);
      receiver43.mirror = true;
      setRotation(receiver43, -0.3346075F, 0F, 0F);
      receiver44 = new ModelRenderer(this, 0, 0);
      receiver44.addBox(0F, 0F, 0F, 1, 1, 3);
      receiver44.setRotationPoint(-0.3F, -15.1F, -12.7F);
      receiver44.setTextureSize(64, 32);
      receiver44.mirror = true;
      setRotation(receiver44, -0.3346075F, 0F, 0F);
      receiver45 = new ModelRenderer(this, 0, 0);
      receiver45.addBox(0F, 0F, 0F, 1, 1, 9);
      receiver45.setRotationPoint(0.7F, -12.3F, -22.7F);
      receiver45.setTextureSize(64, 32);
      receiver45.mirror = true;
      setRotation(receiver45, 0F, 0F, 2.602503F);
      receiver46 = new ModelRenderer(this, 0, 0);
      receiver46.addBox(0F, 0F, 0F, 1, 1, 13);
      receiver46.setRotationPoint(0.7F, -12.3F, -11.7F);
      receiver46.setTextureSize(64, 32);
      receiver46.mirror = true;
      setRotation(receiver46, 0F, 0F, 2.602503F);
      receiver47 = new ModelRenderer(this, 0, 0);
      receiver47.addBox(-1F, 0F, 0F, 1, 1, 24);
      receiver47.setRotationPoint(-3.7F, -12.3F, -22.7F);
      receiver47.setTextureSize(64, 32);
      receiver47.mirror = true;
      setRotation(receiver47, 0F, 0F, -2.602507F);
      receiver48 = new ModelRenderer(this, 0, 0);
      receiver48.addBox(0F, 0F, 0F, 1, 1, 9);
      receiver48.setRotationPoint(-0.2F, -13.6F, -11.6F);
      receiver48.setTextureSize(64, 32);
      receiver48.mirror = true;
      setRotation(receiver48, 0F, 0F, 0F);
      receiver49 = new ModelRenderer(this, 0, 0);
      receiver49.addBox(0F, 0F, 0F, 1, 1, 8);
      receiver49.setRotationPoint(-0.2F, -13.6F, -21.8F);
      receiver49.setTextureSize(64, 32);
      receiver49.mirror = true;
      setRotation(receiver49, 0F, 0F, 0F);
      receiver50 = new ModelRenderer(this, 0, 0);
      receiver50.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver50.setRotationPoint(-0.2F, -13.4F, -4.7F);
      receiver50.setTextureSize(64, 32);
      receiver50.mirror = true;
      setRotation(receiver50, 0F, 0F, 0F);
      receiver51 = new ModelRenderer(this, 0, 0);
      receiver51.addBox(0F, 0F, 0F, 1, 1, 2);
      receiver51.setRotationPoint(-0.2F, -13.8F, -4.7F);
      receiver51.setTextureSize(64, 32);
      receiver51.mirror = true;
      setRotation(receiver51, 0F, 0F, 0F);
      receiver52 = new ModelRenderer(this, 0, 0);
      receiver52.addBox(0F, 0F, 0F, 1, 1, 1);
      receiver52.setRotationPoint(-0.2F, -13.7F, -14.8F);
      receiver52.setTextureSize(64, 32);
      receiver52.mirror = true;
      setRotation(receiver52, 0F, 0F, 0F);
      receiver53 = new ModelRenderer(this, 0, 0);
      receiver53.addBox(0F, 0F, 0F, 1, 1, 15);
      receiver53.setRotationPoint(-2.8F, -16.3F, -16F);
      receiver53.setTextureSize(64, 32);
      receiver53.mirror = true;
      setRotation(receiver53, 0F, 0F, 0F);
      receiver54 = new ModelRenderer(this, 0, 0);
      receiver54.addBox(0F, 0F, 0F, 1, 1, 15);
      receiver54.setRotationPoint(-1.2F, -16.3F, -16F);
      receiver54.setTextureSize(64, 32);
      receiver54.mirror = true;
      setRotation(receiver54, 0F, 0F, 0F);
      receiver55 = new ModelRenderer(this, 0, 0);
      receiver55.addBox(0F, 0F, 0F, 1, 1, 17);
      receiver55.setRotationPoint(-1.2F, -17.1F, -16F);
      receiver55.setTextureSize(64, 32);
      receiver55.mirror = true;
      setRotation(receiver55, 0F, 0F, 0F);
      receiver56 = new ModelRenderer(this, 0, 0);
      receiver56.addBox(0F, 0F, 0F, 2, 1, 17);
      receiver56.setRotationPoint(-2.8F, -17.1F, -16F);
      receiver56.setTextureSize(64, 32);
      receiver56.mirror = true;
      setRotation(receiver56, 0F, 0F, 0F);
      receiver57 = new ModelRenderer(this, 0, 0);
      receiver57.addBox(0F, 0F, 0F, 2, 1, 17);
      receiver57.setRotationPoint(-2.5F, -17.5F, -16F);
      receiver57.setTextureSize(64, 32);
      receiver57.mirror = true;
      setRotation(receiver57, 0F, 0F, 0F);
      receiver58 = new ModelRenderer(this, 0, 0);
      receiver58.addBox(0F, 0F, 0F, 1, 1, 3);
      receiver58.setRotationPoint(-1.2F, -16.1F, 1F);
      receiver58.setTextureSize(64, 32);
      receiver58.mirror = true;
      setRotation(receiver58, -3.011467F, 0F, 0F);
      receiver59 = new ModelRenderer(this, 0, 0);
      receiver59.addBox(0F, 0F, 0F, 1, 1, 3);
      receiver59.setRotationPoint(-2.8F, -16.1F, 1F);
      receiver59.setTextureSize(64, 32);
      receiver59.mirror = true;
      setRotation(receiver59, -3.011467F, 0F, 0F);
      receiver60 = new ModelRenderer(this, 0, 0);
      receiver60.addBox(0F, 0F, 0F, 1, 1, 4);
      receiver60.setRotationPoint(-3.7F, -14.7F, -20.7F);
      receiver60.setTextureSize(64, 32);
      receiver60.mirror = true;
      setRotation(receiver60, 0F, 0F, 0F);
      receiver61 = new ModelRenderer(this, 0, 0);
      receiver61.addBox(0F, 0F, 0F, 1, 1, 4);
      receiver61.setRotationPoint(-0.301F, -14.7F, -20.7F);
      receiver61.setTextureSize(64, 32);
      receiver61.mirror = true;
      setRotation(receiver61, 0F, 0F, 0F);
      receiver62 = new ModelRenderer(this, 0, 0);
      receiver62.addBox(0F, 0F, 0F, 1, 1, 6);
      receiver62.setRotationPoint(-3.7F, -14.2F, -4.7F);
      receiver62.setTextureSize(64, 32);
      receiver62.mirror = true;
      setRotation(receiver62, 0F, 0F, 0F);
      receiver63 = new ModelRenderer(this, 0, 0);
      receiver63.addBox(0F, 0F, 0F, 1, 1, 6);
      receiver63.setRotationPoint(-3.7F, -13.3F, -4.7F);
      receiver63.setTextureSize(64, 32);
      receiver63.mirror = true;
      setRotation(receiver63, 0F, 0F, 0F);
      receiver64 = new ModelRenderer(this, 0, 0);
      receiver64.addBox(0F, 0F, 0F, 1, 1, 17);
      receiver64.setRotationPoint(-3.5F, -13.2F, -21.7F);
      receiver64.setTextureSize(64, 32);
      receiver64.mirror = true;
      setRotation(receiver64, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    receiver4.render(f5);
    receiver7.render(f5);
    receiver8.render(f5);
    receiver12.render(f5);
    receiver13.render(f5);
    receiver14.render(f5);
    receiver21.render(f5);
    receiver22.render(f5);
    receiver26.render(f5);
    receiver32.render(f5);
    receiver36.render(f5);
    receiver37.render(f5);
    receiver38.render(f5);
    receiver39.render(f5);
    receiver40.render(f5);
    receiver41.render(f5);
    receiver42.render(f5);
    receiver43.render(f5);
    receiver44.render(f5);
    receiver45.render(f5);
    receiver46.render(f5);
    receiver47.render(f5);
    receiver48.render(f5);
    receiver49.render(f5);
    receiver50.render(f5);
    receiver51.render(f5);
    receiver52.render(f5);
    receiver53.render(f5);
    receiver54.render(f5);
    receiver55.render(f5);
    receiver56.render(f5);
    receiver57.render(f5);
    receiver58.render(f5);
    receiver59.render(f5);
    receiver60.render(f5);
    receiver61.render(f5);
    receiver62.render(f5);
    receiver63.render(f5);
    receiver64.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
