// Date: 2/16/2019 8:17:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DeskShelfAlt1 extends ModelBase
{
  //fields
    ModelRenderer shelf1;
    ModelRenderer shelf2;
    ModelRenderer shelf3;
    ModelRenderer shelf4;
    ModelRenderer shelf6;
    ModelRenderer shelf7;
    ModelRenderer shelf11;
  
  public DeskShelfAlt1()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      shelf1 = new ModelRenderer(this, 0, 0);
      shelf1.addBox(0F, 0F, 0F, 15, 2, 8);
      shelf1.setRotationPoint(-7F, 15F, 0F);
      shelf1.setTextureSize(64, 32);
      shelf1.mirror = true;
      setRotation(shelf1, 0F, 0F, 0F);
      shelf2 = new ModelRenderer(this, 0, 50);
      shelf2.addBox(0F, 0F, 0F, 2, 5, 5);
      shelf2.setRotationPoint(-6.5F, 10F, 2.5F);
      shelf2.setTextureSize(64, 32);
      shelf2.mirror = true;
      setRotation(shelf2, 0F, 0F, 0F);
      shelf3 = new ModelRenderer(this, 0, 90);
      shelf3.addBox(0F, 0F, 0F, 2, 6, 4);
      shelf3.setRotationPoint(-4.1F, 9.5F, 3F);
      shelf3.setTextureSize(64, 32);
      shelf3.mirror = true;
      setRotation(shelf3, 0F, 0F, 0F);
      shelf4 = new ModelRenderer(this, 0, 70);
      shelf4.addBox(0F, 0F, 0F, 1, 4, 4);
      shelf4.setRotationPoint(-2F, 11F, 3.5F);
      shelf4.setTextureSize(64, 32);
      shelf4.mirror = true;
      setRotation(shelf4, 0F, 0F, 0F);
      shelf6 = new ModelRenderer(this, 0, 30);
      shelf6.addBox(0F, 0F, 0F, 8, 4, 4);
      shelf6.setRotationPoint(-5F, 20F, -3F);
      shelf6.setTextureSize(64, 32);
      shelf6.mirror = true;
      setRotation(shelf6, 0F, -0.3346075F, 0F);
      shelf7 = new ModelRenderer(this, 40, 30);
      shelf7.addBox(0F, 0F, 0F, 4, 2, 1);
      shelf7.setRotationPoint(-4F, 19F, 0F);
      shelf7.setTextureSize(64, 32);
      shelf7.mirror = true;
      setRotation(shelf7, -0.3717861F, 0F, 0F);
      shelf11 = new ModelRenderer(this, 0, 110);
      shelf11.addBox(0F, 0F, 0F, 1, 15, 14);
      shelf11.setRotationPoint(-8F, 9F, -6F);
      shelf11.setTextureSize(64, 32);
      shelf11.mirror = true;
      setRotation(shelf11, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    shelf1.render(f5);
    shelf2.render(f5);
    shelf3.render(f5);
    shelf4.render(f5);
    shelf6.render(f5);
    shelf7.render(f5);
    shelf11.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
