// Date: 6/4/2020 6:42:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class G95_rearsights extends ModelBase
{
  //fields
    ModelRenderer sight8;
    ModelRenderer sight13;
    ModelRenderer sight17;
    ModelRenderer sight19;
    ModelRenderer sight31;
    ModelRenderer sight35;
    ModelRenderer sight36;
    ModelRenderer sight37;
    ModelRenderer sight38;
    ModelRenderer sight39;
    ModelRenderer sight40;
    ModelRenderer sight43;
    ModelRenderer sight44;
    ModelRenderer sight47;
    ModelRenderer sight48;
    ModelRenderer sight49;
    ModelRenderer sight50;
    ModelRenderer sight51;
    ModelRenderer sight52;
    ModelRenderer sight53;
    ModelRenderer sight54;
    ModelRenderer sight55;
    ModelRenderer sight56;
    ModelRenderer sight57;
    ModelRenderer sight58;
    ModelRenderer sight59;
    ModelRenderer sight60;
  
  public G95_rearsights()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 8, 4, 2);
      sight8.setRotationPoint(-4.7F, 5F, -4.3F);
      sight8.setTextureSize(64, 32);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, 0F);
      sight13 = new ModelRenderer(this, 0, 0);
      sight13.addBox(0F, 0F, 0F, 3, 4, 4);
      sight13.setRotationPoint(-7.5F, 6.5F, -5F);
      sight13.setTextureSize(64, 32);
      sight13.mirror = true;
      setRotation(sight13, 0.7853982F, 0F, 0F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 3, 2, 8);
      sight17.setRotationPoint(0F, 5.3F, 0.8F);
      sight17.setTextureSize(64, 32);
      sight17.mirror = true;
      setRotation(sight17, 0F, 0F, 0F);
      sight19 = new ModelRenderer(this, 0, 0);
      sight19.addBox(0F, 0F, 0F, 4, 4, 3);
      sight19.setRotationPoint(-0.5F, 4.5F, -1.5F);
      sight19.setTextureSize(64, 32);
      sight19.mirror = true;
      setRotation(sight19, 0F, 0F, 0F);
      sight31 = new ModelRenderer(this, 0, 0);
      sight31.addBox(0F, 0F, 0F, 2, 4, 6);
      sight31.setRotationPoint(-4.7F, 5F, -2.3F);
      sight31.setTextureSize(64, 32);
      sight31.mirror = true;
      setRotation(sight31, 0F, 0F, 0F);
      sight35 = new ModelRenderer(this, 0, 0);
      sight35.addBox(0F, 0F, 0F, 2, 3, 11);
      sight35.setRotationPoint(3.7F, 5F, -2.3F);
      sight35.setTextureSize(64, 32);
      sight35.mirror = true;
      setRotation(sight35, 0F, 0F, 0F);
      sight36 = new ModelRenderer(this, 0, 0);
      sight36.addBox(0F, 0F, 0F, 1, 3, 3);
      sight36.setRotationPoint(5.7F, 5F, -2.3F);
      sight36.setTextureSize(64, 32);
      sight36.mirror = true;
      setRotation(sight36, 0F, -2.193538F, 0F);
      sight37 = new ModelRenderer(this, 0, 0);
      sight37.addBox(0.5F, 0F, 0F, 1, 3, 3);
      sight37.setRotationPoint(5.7F, 5F, -2.3F);
      sight37.setTextureSize(64, 32);
      sight37.mirror = true;
      setRotation(sight37, 0F, -2.193538F, 0F);
      sight38 = new ModelRenderer(this, 0, 0);
      sight38.addBox(0F, 0F, 0F, 1, 1, 1);
      sight38.setRotationPoint(5.2F, 6F, -1.5F);
      sight38.setTextureSize(64, 32);
      sight38.mirror = true;
      setRotation(sight38, 0.7853982F, 0F, 0F);
      sight39 = new ModelRenderer(this, 0, 0);
      sight39.addBox(0F, 0F, 0F, 6, 2, 2);
      sight39.setRotationPoint(-1.8F, 5.5F, -1F);
      sight39.setTextureSize(64, 32);
      sight39.mirror = true;
      setRotation(sight39, 0F, 0F, 0F);
      sight40 = new ModelRenderer(this, 0, 0);
      sight40.addBox(0F, 0F, 0F, 2, 3, 17);
      sight40.setRotationPoint(5F, 8F, -9.3F);
      sight40.setTextureSize(64, 32);
      sight40.mirror = true;
      setRotation(sight40, 0F, 0F, 0F);
      sight43 = new ModelRenderer(this, 0, 0);
      sight43.addBox(0F, 0F, 0F, 9, 3, 6);
      sight43.setRotationPoint(-3.7F, 6.5F, -10.3F);
      sight43.setTextureSize(64, 32);
      sight43.mirror = true;
      setRotation(sight43, 0F, 0F, 0F);
      sight44 = new ModelRenderer(this, 0, 0);
      sight44.addBox(0F, 0F, 0F, 4, 3, 3);
      sight44.setRotationPoint(-0.5F, 5F, -7.3F);
      sight44.setTextureSize(64, 32);
      sight44.mirror = true;
      setRotation(sight44, -1.152537F, 0F, 0F);
      sight47 = new ModelRenderer(this, 0, 0);
      sight47.addBox(0F, 0F, 0F, 1, 2, 1);
      sight47.setRotationPoint(1F, 5.5F, 10F);
      sight47.setTextureSize(64, 32);
      sight47.mirror = true;
      setRotation(sight47, 0F, 0F, 0F);
      sight48 = new ModelRenderer(this, 0, 0);
      sight48.addBox(0F, 0F, 0F, 1, 2, 1);
      sight48.setRotationPoint(0F, 5.5F, 9F);
      sight48.setTextureSize(64, 32);
      sight48.mirror = true;
      setRotation(sight48, 0F, 0F, 0F);
      sight49 = new ModelRenderer(this, 0, 0);
      sight49.addBox(0F, 0F, 0F, 1, 2, 1);
      sight49.setRotationPoint(2F, 5.5F, 9F);
      sight49.setTextureSize(64, 32);
      sight49.mirror = true;
      setRotation(sight49, 0F, 0F, 0F);
      sight50 = new ModelRenderer(this, 0, 0);
      sight50.addBox(0F, 0F, 0F, 2, 2, 1);
      sight50.setRotationPoint(0F, 5.5F, 9F);
      sight50.setTextureSize(64, 32);
      sight50.mirror = true;
      setRotation(sight50, 0F, 0.7853982F, 0F);
      sight51 = new ModelRenderer(this, 0, 0);
      sight51.addBox(0F, 0F, 0F, 1, 2, 1);
      sight51.setRotationPoint(0F, 5.5F, 10F);
      sight51.setTextureSize(64, 32);
      sight51.mirror = true;
      setRotation(sight51, 0F, 0.7853982F, 0F);
      sight52 = new ModelRenderer(this, 0, 0);
      sight52.addBox(0F, 0F, 0F, 1, 2, 2);
      sight52.setRotationPoint(3F, 5.5F, 9F);
      sight52.setTextureSize(64, 32);
      sight52.mirror = true;
      setRotation(sight52, 0F, -2.356194F, 0F);
      sight53 = new ModelRenderer(this, 0, 0);
      sight53.addBox(0F, 0F, 0F, 1, 2, 1);
      sight53.setRotationPoint(3F, 5.5F, 10F);
      sight53.setTextureSize(64, 32);
      sight53.mirror = true;
      setRotation(sight53, 0F, -2.356194F, 0F);
      sight54 = new ModelRenderer(this, 0, 0);
      sight54.addBox(0F, 0F, 0F, 1, 2, 1);
      sight54.setRotationPoint(1F, 5.5F, 11F);
      sight54.setTextureSize(64, 32);
      sight54.mirror = true;
      setRotation(sight54, 0F, 2.356194F, 0F);
      sight55 = new ModelRenderer(this, 0, 0);
      sight55.addBox(0F, 0F, 0F, 1, 2, 1);
      sight55.setRotationPoint(2F, 5.5F, 11F);
      sight55.setTextureSize(64, 32);
      sight55.mirror = true;
      setRotation(sight55, 0F, 2.356194F, 0F);
      sight56 = new ModelRenderer(this, 0, 0);
      sight56.addBox(0F, 0F, 0F, 2, 3, 11);
      sight56.setRotationPoint(-2.7F, 5F, -2.3F);
      sight56.setTextureSize(64, 32);
      sight56.mirror = true;
      setRotation(sight56, 0F, 0F, 0F);
      sight57 = new ModelRenderer(this, 0, 0);
      sight57.addBox(0F, 0F, 0F, 4, 3, 3);
      sight57.setRotationPoint(-0.5F, 5F, -7.3F);
      sight57.setTextureSize(64, 32);
      sight57.mirror = true;
      setRotation(sight57, 0F, 0F, 0F);
      sight58 = new ModelRenderer(this, 0, 0);
      sight58.addBox(0F, 0F, 0F, 2, 4, 17);
      sight58.setRotationPoint(-4F, 7F, -9.3F);
      sight58.setTextureSize(64, 32);
      sight58.mirror = true;
      setRotation(sight58, 0F, 0F, 0F);
      sight59 = new ModelRenderer(this, 0, 0);
      sight59.addBox(0F, 0F, 0F, 9, 2, 17);
      sight59.setRotationPoint(-2.9F, 7.5F, -9.35F);
      sight59.setTextureSize(64, 32);
      sight59.mirror = true;
      setRotation(sight59, 0F, 0F, 0F);
      sight60 = new ModelRenderer(this, 0, 0);
      sight60.addBox(0F, 0F, 0F, 1, 1, 17);
      sight60.setRotationPoint(6.1F, 7.5F, -9.3F);
      sight60.setTextureSize(64, 32);
      sight60.mirror = true;
      setRotation(sight60, 0F, 0F, 0.5205006F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight8.render(f5);
    sight13.render(f5);
    sight17.render(f5);
    sight19.render(f5);
    sight31.render(f5);
    sight35.render(f5);
    sight36.render(f5);
    sight37.render(f5);
    sight38.render(f5);
    sight39.render(f5);
    sight40.render(f5);
    sight43.render(f5);
    sight44.render(f5);
    sight47.render(f5);
    sight48.render(f5);
    sight49.render(f5);
    sight50.render(f5);
    sight51.render(f5);
    sight52.render(f5);
    sight53.render(f5);
    sight54.render(f5);
    sight55.render(f5);
    sight56.render(f5);
    sight57.render(f5);
    sight58.render(f5);
    sight59.render(f5);
    sight60.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
