// Date: 8/24/2019 11:12:23 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import com.paneedah.weaponlib.ModelWithAttachments;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GasCan extends ModelWithAttachments
{
  //fields
    ModelRenderer can1;
    ModelRenderer can2;
    ModelRenderer can3;
    ModelRenderer can4;
    ModelRenderer can5;
    ModelRenderer can6;
    ModelRenderer can7;
    ModelRenderer can8;
    ModelRenderer can9;
    ModelRenderer can10;
    ModelRenderer can11;
    ModelRenderer can12;
  
  public GasCan()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      can1 = new ModelRenderer(this, 0, 0);
      can1.addBox(0F, 0F, 0F, 2, 1, 7);
      can1.setRotationPoint(-0.5F, -10F, -2F);
      can1.setTextureSize(256, 256);
      can1.mirror = true;
      setRotation(can1, 0F, 0F, 0F);
      can2 = new ModelRenderer(this, 0, 0);
      can2.addBox(0F, 0F, 0F, 3, 4, 2);
      can2.setRotationPoint(-1F, -10.5F, -4F);
      can2.setTextureSize(256, 256);
      can2.mirror = true;
      setRotation(can2, 0F, 0F, 0F);
      can3 = new ModelRenderer(this, 0, 0);
      can3.addBox(0F, 0F, 0F, 3, 4, 3);
      can3.setRotationPoint(-1F, -10.5F, 5F);
      can3.setTextureSize(256, 256);
      can3.mirror = true;
      setRotation(can3, 0F, 0F, 0F);
      can4 = new ModelRenderer(this, 0, 0);
      can4.addBox(0F, 0F, 0F, 5, 18, 17);
      can4.setRotationPoint(-2F, -6.5F, -8F);
      can4.setTextureSize(256, 256);
      can4.mirror = true;
      setRotation(can4, 0F, 0F, 0F);
      can5 = new ModelRenderer(this, 0, 0);
      can5.addBox(0F, 0F, 0F, 3, 4, 2);
      can5.setRotationPoint(-1F, -10.5F, -4F);
      can5.setTextureSize(256, 256);
      can5.mirror = true;
      setRotation(can5, -0.4461433F, 0F, 0F);
      can6 = new ModelRenderer(this, 0, 0);
      can6.addBox(0F, 0F, 0F, 5, 2, 4);
      can6.setRotationPoint(-2F, -6.5F, -8F);
      can6.setTextureSize(256, 256);
      can6.mirror = true;
      setRotation(can6, 0.4089647F, 0F, 0F);
      can7 = new ModelRenderer(this, 0, 0);
      can7.addBox(0F, 0F, 0F, 2, 4, 2);
      can7.setRotationPoint(-1F, -10.5F, -4F);
      can7.setTextureSize(256, 256);
      can7.mirror = true;
      setRotation(can7, 0F, 0F, 0.2443461F);
      can8 = new ModelRenderer(this, 0, 0);
      can8.addBox(-2F, 0F, 0F, 2, 4, 2);
      can8.setRotationPoint(2F, -10.5F, -4F);
      can8.setTextureSize(256, 256);
      can8.mirror = true;
      setRotation(can8, 0F, 0F, -0.2443461F);
      can9 = new ModelRenderer(this, 0, 0);
      can9.addBox(-2F, 0F, 0F, 2, 4, 3);
      can9.setRotationPoint(2F, -10.5F, 5F);
      can9.setTextureSize(256, 256);
      can9.mirror = true;
      setRotation(can9, 0F, 0F, -0.2443461F);
      can10 = new ModelRenderer(this, 0, 0);
      can10.addBox(0F, 0F, 0F, 2, 4, 3);
      can10.setRotationPoint(-1F, -10.5F, 5F);
      can10.setTextureSize(256, 256);
      can10.mirror = true;
      setRotation(can10, 0F, 0F, 0.2443461F);
      can11 = new ModelRenderer(this, 0, 0);
      can11.addBox(0F, 0F, 0F, 3, 1, 4);
      can11.setRotationPoint(-1F, -10.5F, 8F);
      can11.setTextureSize(256, 256);
      can11.mirror = true;
      setRotation(can11, -1.33843F, 0F, 0F);
      can12 = new ModelRenderer(this, 0, 50);
      can12.addBox(0F, 0F, 0F, 2, 5, 2);
      can12.setRotationPoint(-0.5F, -11F, -9F);
      can12.setTextureSize(256, 256);
      can12.mirror = true;
      setRotation(can12, 0.669215F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    can1.render(f5);
    can2.render(f5);
    can3.render(f5);
    can4.render(f5);
    can5.render(f5);
    can6.render(f5);
    can7.render(f5);
    can8.render(f5);
    can9.render(f5);
    can10.render(f5);
    can11.render(f5);
    can12.render(f5);
  }
  
}
