package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GasDetector extends ModelBase {
    // fields
    ModelRenderer GasDetector1;
    ModelRenderer GasDetector2;
    ModelRenderer GasDetector3;
    ModelRenderer GasDetector4;
    ModelRenderer GasDetector5;
    ModelRenderer GasDetector6;
    ModelRenderer GasDetector7;
    ModelRenderer GasDetector8;
    ModelRenderer GasDetector9;
    ModelRenderer GasDetector10;
    ModelRenderer GasDetector11;
    ModelRenderer GasDetector12;
    ModelRenderer GasDetector13;
    ModelRenderer GasDetector14;
    ModelRenderer GasDetector15;
    ModelRenderer GasDetector16;
    ModelRenderer GasDetector17;
    ModelRenderer GasDetector18;
    ModelRenderer GasDetector19;
    ModelRenderer GasDetector20;
    ModelRenderer GasDetector21;
    ModelRenderer GasDetector22;
    ModelRenderer GasDetector23;
    ModelRenderer GasDetector24;
    ModelRenderer GasDetector25;
    ModelRenderer GasDetector26;
    ModelRenderer GasDetector27;
    ModelRenderer GasDetector28;

    public GasDetector() {
        textureWidth = 64;
        textureHeight = 32;

        GasDetector1 = new ModelRenderer(this, 0, 0);
        GasDetector1.addBox(0F, 0F, 0F, 7, 11, 1);
        GasDetector1.setRotationPoint(0F, -10F, 0F);
        GasDetector1.setTextureSize(64, 32);
        GasDetector1.mirror = true;
        setRotation(GasDetector1, 0F, 0F, 0F);
        GasDetector2 = new ModelRenderer(this, 0, 0);
        GasDetector2.addBox(0F, 0F, 0F, 7, 4, 3);
        GasDetector2.setRotationPoint(0F, -3F, 1F);
        GasDetector2.setTextureSize(64, 32);
        GasDetector2.mirror = true;
        setRotation(GasDetector2, 0F, 0F, 0F);
        GasDetector3 = new ModelRenderer(this, 0, 0);
        GasDetector3.addBox(0F, 0F, 0F, 7, 2, 3);
        GasDetector3.setRotationPoint(0F, -10.5F, 1F);
        GasDetector3.setTextureSize(64, 32);
        GasDetector3.mirror = true;
        setRotation(GasDetector3, 0F, 0F, 0F);
        GasDetector4 = new ModelRenderer(this, 0, 0);
        GasDetector4.addBox(0F, 0F, 0F, 1, 6, 1);
        GasDetector4.setRotationPoint(0F, -8.5F, 3F);
        GasDetector4.setTextureSize(64, 32);
        GasDetector4.mirror = true;
        setRotation(GasDetector4, 0F, 0F, 0F);
        GasDetector5 = new ModelRenderer(this, 0, 0);
        GasDetector5.addBox(0F, 0F, 0F, 1, 6, 3);
        GasDetector5.setRotationPoint(6F, -8.5F, 1F);
        GasDetector5.setTextureSize(64, 32);
        GasDetector5.mirror = true;
        setRotation(GasDetector5, 0F, 0F, 0F);
        GasDetector6 = new ModelRenderer(this, 0, 0);
        GasDetector6.addBox(0F, 0F, 0F, 1, 5, 1);
        GasDetector6.setRotationPoint(5.5F, -9.5F, 3.2F);
        GasDetector6.setTextureSize(64, 32);
        GasDetector6.mirror = true;
        setRotation(GasDetector6, 0F, 0F, 0F);
        GasDetector7 = new ModelRenderer(this, 0, 0);
        GasDetector7.addBox(0F, 0F, 0F, 4, 1, 1);
        GasDetector7.setRotationPoint(1.5F, -9.5F, 3.2F);
        GasDetector7.setTextureSize(64, 32);
        GasDetector7.mirror = true;
        setRotation(GasDetector7, 0F, 0F, 0F);
        GasDetector8 = new ModelRenderer(this, 0, 0);
        GasDetector8.addBox(0F, 0F, 0F, 1, 5, 1);
        GasDetector8.setRotationPoint(0.5F, -9.5F, 3.2F);
        GasDetector8.setTextureSize(64, 32);
        GasDetector8.mirror = true;
        setRotation(GasDetector8, 0F, 0F, 0F);
        GasDetector9 = new ModelRenderer(this, 0, 0);
        GasDetector9.addBox(0F, 0F, 0F, 4, 1, 1);
        GasDetector9.setRotationPoint(1.5F, -5.5F, 3.2F);
        GasDetector9.setTextureSize(64, 32);
        GasDetector9.mirror = true;
        setRotation(GasDetector9, 0F, 0F, 0F);
        GasDetector10 = new ModelRenderer(this, 0, 0);
        GasDetector10.addBox(0F, 0F, 0F, 5, 2, 1);
        GasDetector10.setRotationPoint(1F, -4.5F, 3F);
        GasDetector10.setTextureSize(64, 32);
        GasDetector10.mirror = true;
        setRotation(GasDetector10, 0F, 0F, 0F);
        GasDetector11 = new ModelRenderer(this, 0, 0);
        GasDetector11.addBox(0F, 0F, 0F, 7, 1, 1);
        GasDetector11.setRotationPoint(-0.2F, -3.3F, 3.2F);
        GasDetector11.setTextureSize(64, 32);
        GasDetector11.mirror = true;
        setRotation(GasDetector11, 0F, 0F, 0F);
        GasDetector12 = new ModelRenderer(this, 0, 0);
        GasDetector12.addBox(0F, 0F, 0F, 1, 1, 1);
        GasDetector12.setRotationPoint(6.2F, -3.3F, 3.2F);
        GasDetector12.setTextureSize(64, 32);
        GasDetector12.mirror = true;
        setRotation(GasDetector12, 0F, 0F, 0F);
        GasDetector13 = new ModelRenderer(this, 0, 0);
        GasDetector13.addBox(0F, 0F, 0F, 6, 1, 1);
        GasDetector13.setRotationPoint(0.5F, -2F, 3.1F);
        GasDetector13.setTextureSize(64, 32);
        GasDetector13.mirror = true;
        setRotation(GasDetector13, 0F, 0F, 0F);
        GasDetector14 = new ModelRenderer(this, 0, 0);
        GasDetector14.addBox(0F, 0F, 0F, 5, 1, 1);
        GasDetector14.setRotationPoint(1F, -0.5F, 3.1F);
        GasDetector14.setTextureSize(64, 32);
        GasDetector14.mirror = true;
        setRotation(GasDetector14, 0F, 0F, 0F);
        GasDetector15 = new ModelRenderer(this, 0, 0);
        GasDetector15.addBox(0F, 0F, 0F, 1, 6, 1);
        GasDetector15.setRotationPoint(0F, -9F, 0.5F);
        GasDetector15.setTextureSize(64, 32);
        GasDetector15.mirror = true;
        setRotation(GasDetector15, 0F, 0F, 0F);
        GasDetector16 = new ModelRenderer(this, 0, 0);
        GasDetector16.addBox(0F, 0F, 0F, 1, 6, 1);
        GasDetector16.setRotationPoint(0F, -9F, 2.5F);
        GasDetector16.setTextureSize(64, 32);
        GasDetector16.mirror = true;
        setRotation(GasDetector16, 0F, 0F, 0F);
        GasDetector17 = new ModelRenderer(this, 30, 0);
        GasDetector17.addBox(0F, 0F, 0F, 1, 6, 1);
        GasDetector17.setRotationPoint(0.2F, -9F, 1.5F);
        GasDetector17.setTextureSize(64, 32);
        GasDetector17.mirror = true;
        setRotation(GasDetector17, 0F, 0F, 0F);
        GasDetector18 = new ModelRenderer(this, 30, 0);
        GasDetector18.addBox(0F, 0F, 0F, 1, 1, 1);
        GasDetector18.setRotationPoint(-0.5F, -2F, 1.5F);
        GasDetector18.setTextureSize(64, 32);
        GasDetector18.mirror = true;
        setRotation(GasDetector18, 0F, 0F, 0F);
        GasDetector19 = new ModelRenderer(this, 30, 0);
        GasDetector19.addBox(0F, 0F, 0F, 1, 1, 1);
        GasDetector19.setRotationPoint(-0.3F, -0.5F, 1.5F);
        GasDetector19.setTextureSize(64, 32);
        GasDetector19.mirror = true;
        setRotation(GasDetector19, 0F, 0F, 0F);
        GasDetector20 = new ModelRenderer(this, 30, 0);
        GasDetector20.addBox(0F, 0F, 0F, 3, 2, 2);
        GasDetector20.setRotationPoint(-0.3F, -10.8F, 1.5F);
        GasDetector20.setTextureSize(64, 32);
        GasDetector20.mirror = true;
        setRotation(GasDetector20, 0F, 0F, 0F);
        GasDetector21 = new ModelRenderer(this, 0, 0);
        GasDetector21.addBox(0F, 0F, 0F, 3, 1, 4);
        GasDetector21.setRotationPoint(4.1F, -10.6F, 0.1F);
        GasDetector21.setTextureSize(64, 32);
        GasDetector21.mirror = true;
        setRotation(GasDetector21, 0F, 0F, 0F);
        GasDetector22 = new ModelRenderer(this, 0, 0);
        GasDetector22.addBox(0F, 0F, 0F, 3, 3, 1);
        GasDetector22.setRotationPoint(4.1F, -10.6F, -0.1F);
        GasDetector22.setTextureSize(64, 32);
        GasDetector22.mirror = true;
        setRotation(GasDetector22, -0.1115358F, 0F, 0F);
        GasDetector23 = new ModelRenderer(this, 0, 0);
        GasDetector23.addBox(0F, 0F, 0F, 1, 2, 3);
        GasDetector23.setRotationPoint(6.1F, -9.6F, 0.1F);
        GasDetector23.setTextureSize(64, 32);
        GasDetector23.mirror = true;
        setRotation(GasDetector23, 0F, 0F, 0F);
        GasDetector24 = new ModelRenderer(this, 0, 0);
        GasDetector24.addBox(0F, 0F, 0F, 3, 1, 2);
        GasDetector24.setRotationPoint(4.1F, -10.6F, 4.1F);
        GasDetector24.setTextureSize(64, 32);
        GasDetector24.mirror = true;
        setRotation(GasDetector24, -1.449966F, 0F, 0F);
        GasDetector25 = new ModelRenderer(this, 0, 0);
        GasDetector25.addBox(0F, 0F, 0F, 1, 1, 1);
        GasDetector25.setRotationPoint(6.1F, -8.6F, 4.4F);
        GasDetector25.setTextureSize(64, 32);
        GasDetector25.mirror = true;
        setRotation(GasDetector25, -1.933288F, 0F, 0F);
        GasDetector26 = new ModelRenderer(this, 0, 0);
        GasDetector26.addBox(0F, 0F, 0F, 1, 2, 1);
        GasDetector26.setRotationPoint(6.1F, -9.6F, 3F);
        GasDetector26.setTextureSize(64, 32);
        GasDetector26.mirror = true;
        setRotation(GasDetector26, 0F, 0F, 0F);
        GasDetector27 = new ModelRenderer(this, 0, 0);
        GasDetector27.addBox(0F, 0F, 0F, 3, 10, 1);
        GasDetector27.setRotationPoint(-0.2F, -9.5F, -0.5F);
        GasDetector27.setTextureSize(64, 32);
        GasDetector27.mirror = true;
        setRotation(GasDetector27, 0F, 0F, 0F);
        GasDetector28 = new ModelRenderer(this, 0, 0);
        GasDetector28.addBox(0F, 0F, 0F, 5, 1, 1);
        GasDetector28.setRotationPoint(0F, -10.5F, 1F);
        GasDetector28.setTextureSize(64, 32);
        GasDetector28.mirror = true;
        setRotation(GasDetector28, -1.152537F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        GasDetector1.render(f5);
        GasDetector2.render(f5);
        GasDetector3.render(f5);
        GasDetector4.render(f5);
        GasDetector5.render(f5);
        GasDetector6.render(f5);
        GasDetector7.render(f5);
        GasDetector8.render(f5);
        GasDetector9.render(f5);
        GasDetector10.render(f5);
        GasDetector11.render(f5);
        GasDetector12.render(f5);
        GasDetector13.render(f5);
        GasDetector14.render(f5);
        GasDetector15.render(f5);
        GasDetector16.render(f5);
        GasDetector17.render(f5);
        GasDetector18.render(f5);
        GasDetector19.render(f5);
        GasDetector20.render(f5);
        GasDetector21.render(f5);
        GasDetector22.render(f5);
        GasDetector23.render(f5);
        GasDetector24.render(f5);
        GasDetector25.render(f5);
        GasDetector26.render(f5);
        GasDetector27.render(f5);
        GasDetector28.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
