// Date: 1/6/2017 11:58:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GlockMagazine extends ModelBase {
    //fields
    ModelRenderer gun1;
    ModelRenderer gun2;
    ModelRenderer gun3;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun6;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun10;
    ModelRenderer gun11;

    public GlockMagazine() {
        textureWidth = 512;
        textureHeight = 256;

        gun1 = new ModelRenderer(this, 0, 0);
        gun1.addBox(0F, 0F, 0F, 4, 1, 6);
        gun1.setRotationPoint(-3.5F, 4F, -4.5F);
        gun1.setTextureSize(64, 32);
        gun1.mirror = true;
        setRotation(gun1, 0F, 0F, 0F);
        gun2 = new ModelRenderer(this, 0, 0);
        gun2.addBox(0F, 0F, 0F, 3, 11, 5);
        gun2.setRotationPoint(-3.3F, -6F, -7F);
        gun2.setTextureSize(64, 32);
        gun2.mirror = true;
        setRotation(gun2, 0.2974289F, 0F, 0F);
        gun3 = new ModelRenderer(this, 0, 0);
        gun3.addBox(0F, 0F, 0F, 3, 1, 3);
        gun3.setRotationPoint(-3.3F, 3.9F, -1.9F);
        gun3.setTextureSize(64, 32);
        gun3.mirror = true;
        setRotation(gun3, 0.2974289F, 0F, 0F);
        gun4 = new ModelRenderer(this, 0, 0);
        gun4.addBox(0F, 0F, 0F, 3, 1, 1);
        gun4.setRotationPoint(-3.3F, 3.5F, -2.5F);
        gun4.setTextureSize(64, 32);
        gun4.mirror = true;
        setRotation(gun4, 0F, 0F, 0F);
        gun5 = new ModelRenderer(this, 0, 0);
        gun5.addBox(0F, 0F, 0F, 1, 11, 5);
        gun5.setRotationPoint(-0.7F, -6F, -7F);
        gun5.setTextureSize(64, 32);
        gun5.mirror = true;
        setRotation(gun5, 0.2974289F, 0F, 0F);
        gun6 = new ModelRenderer(this, 0, 0);
        gun6.addBox(0F, 0F, 0F, 1, 1, 3);
        gun6.setRotationPoint(-0.7F, 3.9F, -1.9F);
        gun6.setTextureSize(64, 32);
        gun6.mirror = true;
        setRotation(gun6, 0.2974289F, 0F, 0F);
        gun7 = new ModelRenderer(this, 0, 0);
        gun7.addBox(0F, 0F, 0F, 1, 1, 1);
        gun7.setRotationPoint(-0.7F, 3.5F, -2.5F);
        gun7.setTextureSize(64, 32);
        gun7.mirror = true;
        setRotation(gun7, 0F, 0F, 0F);
        gun8 = new ModelRenderer(this, 0, 0);
        gun8.addBox(0F, 0F, 0F, 3, 1, 1);
        gun8.setRotationPoint(-3.3F, 4F, -4.5F);
        gun8.setTextureSize(64, 32);
        gun8.mirror = true;
        setRotation(gun8, 0.8551081F, 0F, 0F);
        gun9 = new ModelRenderer(this, 0, 0);
        gun9.addBox(0F, 0F, 0F, 1, 1, 1);
        gun9.setRotationPoint(-0.7F, 4F, -4.5F);
        gun9.setTextureSize(64, 32);
        gun9.mirror = true;
        setRotation(gun9, 0.8551081F, 0F, 0F);
        gun10 = new ModelRenderer(this, 0, 0);
        gun10.addBox(0F, 0F, 0F, 3, 1, 2);
        gun10.setRotationPoint(-3F, -6.5F, -7F);
        gun10.setTextureSize(64, 32);
        gun10.mirror = true;
        setRotation(gun10, 0.2974289F, 0F, 0F);
        gun11 = new ModelRenderer(this, 0, 0);
        gun11.addBox(0F, 0F, 0F, 3, 1, 4);
        gun11.setRotationPoint(-3F, -7.5F, -7F);
        gun11.setTextureSize(64, 32);
        gun11.mirror = true;
        setRotation(gun11, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        gun1.render(f5);
        gun2.render(f5);
        gun3.render(f5);
        gun4.render(f5);
        gun5.render(f5);
        gun6.render(f5);
        gun7.render(f5);
        gun8.render(f5);
        gun9.render(f5);
        gun10.render(f5);
        gun11.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
