// Date: 2/17/2019 1:59:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class HangingBody extends ModelBase {
    //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer rope1;
    ModelRenderer rope2;

    public HangingBody() {
        textureWidth = 256;
        textureHeight = 256;

        head = new ModelRenderer(this, 0, 0);
        head.addBox(0F, 0F, 0F, 8, 8, 8);
        head.setRotationPoint(-4F, -8F, -6F);
        head.setTextureSize(256, 256);
        head.mirror = true;
        setRotation(head, 0.2974289F, 0F, 0F);
        body = new ModelRenderer(this, 16, 16);
        body.addBox(0F, 0F, 0F, 8, 12, 4);
        body.setRotationPoint(-4F, -2F, -2F);
        body.setTextureSize(256, 256);
        body.mirror = true;
        setRotation(body, -0.0743572F, 0F, 0F);
        rightarm = new ModelRenderer(this, 40, 16);
        rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
        rightarm.setRotationPoint(-5F, 1F, 0F);
        rightarm.setTextureSize(256, 256);
        rightarm.mirror = true;
        setRotation(rightarm, -0.0371786F, 0F, 0.0371786F);
        leftarm = new ModelRenderer(this, 40, 16);
        leftarm.addBox(0F, 0F, 0F, 4, 12, 4);
        leftarm.setRotationPoint(3.5F, -1.5F, -2F);
        leftarm.setTextureSize(256, 256);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, -0.1115358F);
        rightleg = new ModelRenderer(this, 0, 16);
        rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
        rightleg.setRotationPoint(-2F, 10F, -1F);
        rightleg.setTextureSize(256, 256);
        rightleg.mirror = true;
        setRotation(rightleg, 0F, 0F, 0.1115358F);
        leftleg = new ModelRenderer(this, 0, 16);
        leftleg.addBox(0F, 0F, 0F, 4, 12, 4);
        leftleg.setRotationPoint(0F, 10F, -3F);
        leftleg.setTextureSize(256, 256);
        leftleg.mirror = true;
        setRotation(leftleg, 0.1858931F, 0F, 0F);
        rope1 = new ModelRenderer(this, 0, 46);
        rope1.addBox(0F, 0F, 0F, 9, 2, 9);
        rope1.setRotationPoint(-4.5F, -0.5F, -4.3F);
        rope1.setTextureSize(256, 256);
        rope1.mirror = true;
        setRotation(rope1, 0.4461433F, 0F, 0F);
        rope2 = new ModelRenderer(this, 0, 46);
        rope2.addBox(0F, 0F, 0F, 2, 18, 2);
        rope2.setRotationPoint(-1F, -20.5F, 2.7F);
        rope2.setTextureSize(256, 256);
        rope2.mirror = true;
        setRotation(rope2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        head.render(f5);
        body.render(f5);
        rightarm.render(f5);
        leftarm.render(f5);
        rightleg.render(f5);
        leftleg.render(f5);
        rope1.render(f5);
        rope2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
