// Date: 1/5/2017 7:51:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M14Mag extends ModelBase {
    //fields
    ModelRenderer gun1;
    ModelRenderer gun11;
    ModelRenderer gun13;

    public M14Mag() {
        textureWidth = 256;
        textureHeight = 128;

        gun1 = new ModelRenderer(this, 200, 0);
        gun1.addBox(0F, 0F, 0F, 2, 11, 2);
        gun1.setRotationPoint(1.5F, -12.9F, -6F);
        gun1.setTextureSize(64, 32);
        gun1.mirror = true;
        setRotation(gun1, -0.0743572F, 0F, 0F);
        gun11 = new ModelRenderer(this, 200, 0);
        gun11.addBox(0F, 0F, 0F, 3, 11, 2);
        gun11.setRotationPoint(1F, -13F, -7F);
        gun11.setTextureSize(64, 32);
        gun11.mirror = true;
        setRotation(gun11, -0.0743572F, 0F, 0F);
        gun13 = new ModelRenderer(this, 200, 0);
        gun13.addBox(0F, 0F, 0F, 3, 11, 4);
        gun13.setRotationPoint(1F, -12.8F, -4.5F);
        gun13.setTextureSize(64, 32);
        gun13.mirror = true;
        setRotation(gun13, -0.0743572F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        gun1.render(f5);
        gun11.render(f5);
        gun13.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
