// Date: 2/29/2020 11:37:27 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class RPKbarrel extends ModelBase
{
  //fields
   
    ModelRenderer accessory1;
    ModelRenderer accessory2;
    ModelRenderer accessory3;
    ModelRenderer accessory4;
    ModelRenderer accessory5;
    ModelRenderer accessory6;
    ModelRenderer accessory7;
    ModelRenderer accessory8;
    ModelRenderer accessory9;
    ModelRenderer accessory10;
    ModelRenderer accessory11;
    ModelRenderer accessory12;
    ModelRenderer accessory13;
    ModelRenderer accessory14;
    ModelRenderer accessory15;
    ModelRenderer accessory16;
    ModelRenderer accessory17;
    ModelRenderer accessory18;
    ModelRenderer accessory19;
    ModelRenderer accessory20;
    ModelRenderer accessory21;
    ModelRenderer accessory22;
    ModelRenderer accessory23;
    ModelRenderer accessory24;
    ModelRenderer accessory25;
    ModelRenderer accessory26;
    ModelRenderer accessory27;
    ModelRenderer accessory28;
  
  public RPKbarrel()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      accessory1 = new ModelRenderer(this, 100, 0);
      accessory1.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory1.setRotationPoint(-2F, -12F, -93F);
      accessory1.setTextureSize(64, 32);
      accessory1.mirror = true;
      setRotation(accessory1, 0F, 0F, 0F);
      accessory2 = new ModelRenderer(this, 100, 0);
      accessory2.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory2.setRotationPoint(-2F, -11.4F, -93F);
      accessory2.setTextureSize(64, 32);
      accessory2.mirror = true;
      setRotation(accessory2, 0F, 0F, 0F);
      accessory3 = new ModelRenderer(this, 100, 0);
      accessory3.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory3.setRotationPoint(-1.7F, -11.7F, -93F);
      accessory3.setTextureSize(64, 32);
      accessory3.mirror = true;
      setRotation(accessory3, 0F, 0F, 0F);
      accessory4 = new ModelRenderer(this, 100, 0);
      accessory4.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory4.setRotationPoint(-2.3F, -11.7F, -93F);
      accessory4.setTextureSize(64, 32);
      accessory4.mirror = true;
      setRotation(accessory4, 0F, 0F, 0F);
      accessory5 = new ModelRenderer(this, 100, 0);
      accessory5.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory5.setRotationPoint(-2.2F, -11.9F, -93F);
      accessory5.setTextureSize(64, 32);
      accessory5.mirror = true;
      setRotation(accessory5, 0F, 0F, 0F);
      accessory6 = new ModelRenderer(this, 100, 0);
      accessory6.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory6.setRotationPoint(-1.8F, -11.9F, -93F);
      accessory6.setTextureSize(64, 32);
      accessory6.mirror = true;
      setRotation(accessory6, 0F, 0F, 0F);
      accessory7 = new ModelRenderer(this, 100, 0);
      accessory7.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory7.setRotationPoint(-1.8F, -11.5F, -93F);
      accessory7.setTextureSize(64, 32);
      accessory7.mirror = true;
      setRotation(accessory7, 0F, 0F, 0F);
      accessory8 = new ModelRenderer(this, 100, 0);
      accessory8.addBox(0F, 0F, 0F, 1, 1, 17);
      accessory8.setRotationPoint(-2.2F, -11.5F, -93F);
      accessory8.setTextureSize(64, 32);
      accessory8.mirror = true;
      setRotation(accessory8, 0F, 0F, 0F);
      accessory9 = new ModelRenderer(this, 100, 0);
      accessory9.addBox(0F, 0F, 0F, 2, 1, 4);
      accessory9.setRotationPoint(-2.5F, -11.7F, -91.5F);
      accessory9.setTextureSize(64, 32);
      accessory9.mirror = true;
      setRotation(accessory9, 0F, 0F, 0F);
      accessory10 = new ModelRenderer(this, 100, 0);
      accessory10.addBox(0F, 0F, 0F, 1, 2, 4);
      accessory10.setRotationPoint(-2F, -12.2F, -91.5F);
      accessory10.setTextureSize(64, 32);
      accessory10.mirror = true;
      setRotation(accessory10, 0F, 0F, 0F);
      accessory11 = new ModelRenderer(this, 100, 0);
      accessory11.addBox(0F, 0F, 0F, 1, 1, 4);
      accessory11.setRotationPoint(-2.3F, -12F, -91.5F);
      accessory11.setTextureSize(64, 32);
      accessory11.mirror = true;
      setRotation(accessory11, 0F, 0F, 0F);
      accessory12 = new ModelRenderer(this, 100, 0);
      accessory12.addBox(0F, 0F, 0F, 1, 1, 4);
      accessory12.setRotationPoint(-1.7F, -12F, -91.5F);
      accessory12.setTextureSize(64, 32);
      accessory12.mirror = true;
      setRotation(accessory12, 0F, 0F, 0F);
      accessory13 = new ModelRenderer(this, 100, 0);
      accessory13.addBox(0F, 0F, 0F, 1, 1, 4);
      accessory13.setRotationPoint(-1.7F, -11.4F, -91.5F);
      accessory13.setTextureSize(64, 32);
      accessory13.mirror = true;
      setRotation(accessory13, 0F, 0F, 0F);
      accessory14 = new ModelRenderer(this, 100, 0);
      accessory14.addBox(0F, 0F, 0F, 1, 1, 4);
      accessory14.setRotationPoint(-2.3F, -11.4F, -91.5F);
      accessory14.setTextureSize(64, 32);
      accessory14.mirror = true;
      setRotation(accessory14, 0F, 0F, 0F);
      accessory15 = new ModelRenderer(this, 100, 0);
      accessory15.addBox(0F, 0F, 0F, 2, 2, 2);
      accessory15.setRotationPoint(-2.5F, -10.7F, -89.5F);
      accessory15.setTextureSize(64, 32);
      accessory15.mirror = true;
      setRotation(accessory15, 0F, 0F, 0F);
      accessory16 = new ModelRenderer(this, 100, 0);
      accessory16.addBox(0F, 0F, 0F, 1, 2, 1);
      accessory16.setRotationPoint(-2.3F, -8.7F, -88.8F);
      accessory16.setTextureSize(64, 32);
      accessory16.mirror = true;
      setRotation(accessory16, 0F, 0F, 0F);
      accessory17 = new ModelRenderer(this, 100, 0);
      accessory17.addBox(0F, 0F, 0F, 1, 2, 1);
      accessory17.setRotationPoint(-1.7F, -8.7F, -88.8F);
      accessory17.setTextureSize(64, 32);
      accessory17.mirror = true;
      setRotation(accessory17, 0F, 0F, 0F);
      accessory18 = new ModelRenderer(this, 100, 0);
      accessory18.addBox(0F, 0F, 0F, 1, 1, 35);
      accessory18.setRotationPoint(-1F, -8.7F, -89.2F);
      accessory18.setTextureSize(64, 32);
      accessory18.mirror = true;
      setRotation(accessory18, 0F, 0F, 0F);
      accessory19 = new ModelRenderer(this, 100, 0);
      accessory19.addBox(0F, 0F, 0F, 1, 1, 35);
      accessory19.setRotationPoint(-1F, -8.2F, -89.2F);
      accessory19.setTextureSize(64, 32);
      accessory19.mirror = true;
      setRotation(accessory19, 0F, 0F, 0F);
      accessory20 = new ModelRenderer(this, 100, 0);
      accessory20.addBox(0F, 0F, 0F, 1, 1, 35);
      accessory20.setRotationPoint(-3F, -8.2F, -89.2F);
      accessory20.setTextureSize(64, 32);
      accessory20.mirror = true;
      setRotation(accessory20, 0F, 0F, 0F);
      accessory21 = new ModelRenderer(this, 100, 0);
      accessory21.addBox(0F, 0F, 0F, 1, 1, 35);
      accessory21.setRotationPoint(-3F, -8.7F, -89.2F);
      accessory21.setTextureSize(64, 32);
      accessory21.mirror = true;
      setRotation(accessory21, 0F, 0F, 0F);
      accessory22 = new ModelRenderer(this, 100, 0);
      accessory22.addBox(0F, 0F, 0F, 1, 1, 25);
      accessory22.setRotationPoint(-0.9F, -8.45F, -79.5F);
      accessory22.setTextureSize(64, 32);
      accessory22.mirror = true;
      setRotation(accessory22, 0F, 0.0087266F, 0F);
      accessory23 = new ModelRenderer(this, 100, 0);
      accessory23.addBox(-1F, 0F, 0F, 1, 1, 25);
      accessory23.setRotationPoint(-2.1F, -8.45F, -79.5F);
      accessory23.setTextureSize(64, 32);
      accessory23.mirror = true;
      setRotation(accessory23, 0F, -0.0087266F, 0F);
      accessory24 = new ModelRenderer(this, 100, 0);
      accessory24.addBox(0F, 0F, 0F, 1, 2, 2);
      accessory24.setRotationPoint(-3.4F, -8.9F, -63.2F);
      accessory24.setTextureSize(64, 32);
      accessory24.mirror = true;
      setRotation(accessory24, 0F, 0F, 0F);
      accessory25 = new ModelRenderer(this, 100, 0);
      accessory25.addBox(0F, 0F, 0F, 1, 2, 2);
      accessory25.setRotationPoint(-0.6F, -8.9F, -63.2F);
      accessory25.setTextureSize(64, 32);
      accessory25.mirror = true;
      setRotation(accessory25, 0F, 0F, 0F);
      accessory26 = new ModelRenderer(this, 100, 0);
      accessory26.addBox(0F, 0F, 0F, 1, 2, 1);
      accessory26.setRotationPoint(-2F, -10.2F, -91.5F);
      accessory26.setTextureSize(64, 32);
      accessory26.mirror = true;
      setRotation(accessory26, 1.33843F, 0F, 0F);
      accessory27 = new ModelRenderer(this, 100, 0);
      accessory27.addBox(0F, 0F, 0F, 2, 3, 1);
      accessory27.setRotationPoint(-4.1F, -9.4F, -55.1F);
      accessory27.setTextureSize(64, 32);
      accessory27.mirror = true;
      setRotation(accessory27, 0F, 0F, 0F);
      accessory28 = new ModelRenderer(this, 100, 0);
      accessory28.addBox(0F, 0F, 0F, 2, 3, 1);
      accessory28.setRotationPoint(-0.9F, -9.4F, -55.1F);
      accessory28.setTextureSize(64, 32);
      accessory28.mirror = true;
      setRotation(accessory28, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    accessory1.render(f5);
    accessory2.render(f5);
    accessory3.render(f5);
    accessory4.render(f5);
    accessory5.render(f5);
    accessory6.render(f5);
    accessory7.render(f5);
    accessory8.render(f5);
    accessory9.render(f5);
    accessory10.render(f5);
    accessory11.render(f5);
    accessory12.render(f5);
    accessory13.render(f5);
    accessory14.render(f5);
    accessory15.render(f5);
    accessory16.render(f5);
    accessory17.render(f5);
    accessory18.render(f5);
    accessory19.render(f5);
    accessory20.render(f5);
    accessory21.render(f5);
    accessory22.render(f5);
    accessory23.render(f5);
    accessory24.render(f5);
    accessory25.render(f5);
    accessory26.render(f5);
    accessory27.render(f5);
    accessory28.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
