// Date: 7/29/2019 9:16:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ServerRackRight extends ModelBase
{
  //fields
    ModelRenderer rack1;
    ModelRenderer rack2;
    ModelRenderer rack3;
    ModelRenderer rack4;
    ModelRenderer rack5;
    ModelRenderer rack6;
    ModelRenderer rack7;
    ModelRenderer rack8;
    ModelRenderer rack9;
    ModelRenderer rack10;
    ModelRenderer rack11;
    ModelRenderer rack12;
    ModelRenderer rack13;
    ModelRenderer rack14;
    ModelRenderer rack15;
    ModelRenderer rack16;
    ModelRenderer rack17;
    ModelRenderer rack18;
    ModelRenderer rack19;
    ModelRenderer rack20;
  
  public ServerRackRight()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      rack1 = new ModelRenderer(this, 0, 0);
      rack1.addBox(0F, 0F, 0F, 16, 2, 13);
      rack1.setRotationPoint(-8F, 20F, -6F);
      rack1.setTextureSize(256, 256);
      rack1.mirror = true;
      setRotation(rack1, 0F, 0F, 0F);
      rack2 = new ModelRenderer(this, 0, 0);
      rack2.addBox(0F, 0F, 0F, 2, 16, 2);
      rack2.setRotationPoint(6.2F, 8F, -6.1F);
      rack2.setTextureSize(256, 256);
      rack2.mirror = true;
      setRotation(rack2, 0F, 0F, 0F);
      rack3 = new ModelRenderer(this, 0, 0);
      rack3.addBox(0F, 0F, 0F, 2, 16, 2);
      rack3.setRotationPoint(6.2F, 8F, 5.1F);
      rack3.setTextureSize(256, 256);
      rack3.mirror = true;
      setRotation(rack3, 0F, 0F, 0F);
      rack4 = new ModelRenderer(this, 0, 50);
      rack4.addBox(0F, 0F, 0F, 1, 15, 9);
      rack4.setRotationPoint(7.1F, 8F, -4.1F);
      rack4.setTextureSize(256, 256);
      rack4.mirror = true;
      setRotation(rack4, 0F, 0F, 0F);
      rack5 = new ModelRenderer(this, 100, 0);
      rack5.addBox(0F, 0F, 0F, 5, 10, 11);
      rack5.setRotationPoint(0.5F, 10F, -5F);
      rack5.setTextureSize(256, 256);
      rack5.mirror = true;
      setRotation(rack5, 0F, 0F, 0F);
      rack6 = new ModelRenderer(this, 100, 0);
      rack6.addBox(0F, 0F, 0F, 5, 10, 11);
      rack6.setRotationPoint(-6.5F, 10F, -5F);
      rack6.setTextureSize(256, 256);
      rack6.mirror = true;
      setRotation(rack6, 0F, 0F, 0F);
      rack7 = new ModelRenderer(this, 100, 0);
      rack7.addBox(0F, 0F, 0F, 1, 11, 2);
      rack7.setRotationPoint(-7F, 9.5F, -5.2F);
      rack7.setTextureSize(256, 256);
      rack7.mirror = true;
      setRotation(rack7, 0F, 0F, 0F);
      rack8 = new ModelRenderer(this, 100, 0);
      rack8.addBox(0F, 0F, 0F, 1, 11, 2);
      rack8.setRotationPoint(0F, 9.5F, -5.2F);
      rack8.setTextureSize(256, 256);
      rack8.mirror = true;
      setRotation(rack8, 0F, 0F, 0F);
      rack9 = new ModelRenderer(this, 100, 0);
      rack9.addBox(0F, 0F, 0F, 1, 11, 2);
      rack9.setRotationPoint(-2F, 9.5F, -5.2F);
      rack9.setTextureSize(256, 256);
      rack9.mirror = true;
      setRotation(rack9, 0F, 0F, 0F);
      rack10 = new ModelRenderer(this, 100, 0);
      rack10.addBox(0F, 0F, 0F, 1, 11, 2);
      rack10.setRotationPoint(5F, 9.5F, -5.2F);
      rack10.setTextureSize(256, 256);
      rack10.mirror = true;
      setRotation(rack10, 0F, 0F, 0F);
      rack11 = new ModelRenderer(this, 100, 0);
      rack11.addBox(0F, 0F, 0F, 4, 1, 2);
      rack11.setRotationPoint(-6F, 9.5F, -5.2F);
      rack11.setTextureSize(256, 256);
      rack11.mirror = true;
      setRotation(rack11, 0F, 0F, 0F);
      rack12 = new ModelRenderer(this, 100, 0);
      rack12.addBox(0F, 0F, 0F, 4, 1, 2);
      rack12.setRotationPoint(1F, 9.5F, -5.2F);
      rack12.setTextureSize(256, 256);
      rack12.mirror = true;
      setRotation(rack12, 0F, 0F, 0F);
      rack13 = new ModelRenderer(this, 100, 60);
      rack13.addBox(0F, 0F, 0F, 2, 1, 1);
      rack13.setRotationPoint(-5.8F, 11F, -5.1F);
      rack13.setTextureSize(256, 256);
      rack13.mirror = true;
      setRotation(rack13, 0F, 0F, 0F);
      rack14 = new ModelRenderer(this, 100, 60);
      rack14.addBox(0F, 0F, 0F, 2, 1, 1);
      rack14.setRotationPoint(-5.8F, 13F, -5.1F);
      rack14.setTextureSize(256, 256);
      rack14.mirror = true;
      setRotation(rack14, 0F, 0F, 0F);
      rack15 = new ModelRenderer(this, 100, 60);
      rack15.addBox(0F, 0F, 0F, 2, 1, 1);
      rack15.setRotationPoint(-5.8F, 15F, -5.1F);
      rack15.setTextureSize(256, 256);
      rack15.mirror = true;
      setRotation(rack15, 0F, 0F, 0F);
      rack16 = new ModelRenderer(this, 100, 60);
      rack16.addBox(0F, 0F, 0F, 2, 1, 1);
      rack16.setRotationPoint(-5.8F, 17F, -5.1F);
      rack16.setTextureSize(256, 256);
      rack16.mirror = true;
      setRotation(rack16, 0F, 0F, 0F);
      rack17 = new ModelRenderer(this, 100, 60);
      rack17.addBox(0F, 0F, 0F, 2, 1, 1);
      rack17.setRotationPoint(1.2F, 11F, -5.1F);
      rack17.setTextureSize(256, 256);
      rack17.mirror = true;
      setRotation(rack17, 0F, 0F, 0F);
      rack18 = new ModelRenderer(this, 100, 60);
      rack18.addBox(0F, 0F, 0F, 2, 1, 1);
      rack18.setRotationPoint(1.2F, 13F, -5.1F);
      rack18.setTextureSize(256, 256);
      rack18.mirror = true;
      setRotation(rack18, 0F, 0F, 0F);
      rack19 = new ModelRenderer(this, 100, 60);
      rack19.addBox(0F, 0F, 0F, 2, 1, 1);
      rack19.setRotationPoint(1.2F, 15F, -5.1F);
      rack19.setTextureSize(256, 256);
      rack19.mirror = true;
      setRotation(rack19, 0F, 0F, 0F);
      rack20 = new ModelRenderer(this, 100, 60);
      rack20.addBox(0F, 0F, 0F, 2, 1, 1);
      rack20.setRotationPoint(1.2F, 17F, -5.1F);
      rack20.setTextureSize(256, 256);
      rack20.mirror = true;
      setRotation(rack20, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    rack1.render(f5);
    rack2.render(f5);
    rack3.render(f5);
    rack4.render(f5);
    rack5.render(f5);
    rack6.render(f5);
    rack7.render(f5);
    rack8.render(f5);
    rack9.render(f5);
    rack10.render(f5);
    rack11.render(f5);
    rack12.render(f5);
    rack13.render(f5);
    rack14.render(f5);
    rack15.render(f5);
    rack16.render(f5);
    rack17.render(f5);
    rack18.render(f5);
    rack19.render(f5);
    rack20.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
