// Date: 5/11/2019 11:40:18 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TracerProjectile extends ModelBase
{
  //fields
    ModelRenderer tracreprojectile;
  
  public TracerProjectile()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      tracreprojectile = new ModelRenderer(this, 0, 0);
      tracreprojectile.addBox(0F, 0F, 0F, 0, 1, 500);
      tracreprojectile.setRotationPoint(-5F, -5F, 10F);
      tracreprojectile.setTextureSize(256, 256);
      tracreprojectile.mirror = true;
      setRotation(tracreprojectile, 0.5F, -29.8F, -45F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    tracreprojectile.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
