// Date: 2/16/2019 4:21:21 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TV extends ModelBase {
    //fields
    ModelRenderer tv1;
    ModelRenderer tv2;
    ModelRenderer tv3;
    ModelRenderer tv4;
    ModelRenderer tv5;
    ModelRenderer tv6;
    ModelRenderer tv7;
    ModelRenderer tv8;

    public TV() {
        textureWidth = 128;
        textureHeight = 128;

        tv1 = new ModelRenderer(this, 0, 0);
        tv1.addBox(0F, 0F, 0F, 14, 1, 5);
        tv1.setRotationPoint(-7F, 23F, -3F);
        tv1.setTextureSize(128, 128);
        tv1.mirror = true;
        setRotation(tv1, 0F, 0F, 0F);
        tv2 = new ModelRenderer(this, 0, 0);
        tv2.addBox(0F, -3F, 0F, 7, 11, 3);
        tv2.setRotationPoint(-3.5F, 15.5F, -1.5F);
        tv2.setTextureSize(128, 128);
        tv2.mirror = true;
        setRotation(tv2, -0.0371786F, 0F, 0F);
        tv3 = new ModelRenderer(this, 0, 0);
        tv3.addBox(0F, 0F, 0F, 43, 2, 1);
        tv3.setRotationPoint(-21.5F, 18.5F, -2.5F);
        tv3.setTextureSize(128, 128);
        tv3.mirror = true;
        setRotation(tv3, 0F, 0F, 0F);
        tv4 = new ModelRenderer(this, 0, 0);
        tv4.addBox(0F, 0F, 0F, 1, 19, 1);
        tv4.setRotationPoint(-21.5F, -0.5F, -2.5F);
        tv4.setTextureSize(128, 128);
        tv4.mirror = true;
        setRotation(tv4, 0F, 0F, 0F);
        tv5 = new ModelRenderer(this, 0, 0);
        tv5.addBox(0F, 0F, 0F, 1, 19, 1);
        tv5.setRotationPoint(20.5F, -0.5F, -2.5F);
        tv5.setTextureSize(128, 128);
        tv5.mirror = true;
        setRotation(tv5, 0F, 0F, 0F);
        tv6 = new ModelRenderer(this, 0, 0);
        tv6.addBox(0F, 0F, 0F, 43, 1, 1);
        tv6.setRotationPoint(-21.5F, -1.5F, -2.5F);
        tv6.setTextureSize(128, 128);
        tv6.mirror = true;
        setRotation(tv6, 0F, 0F, 0F);
        tv7 = new ModelRenderer(this, 0, 0);
        tv7.addBox(0F, 0F, 0F, 42, 20, 1);
        tv7.setRotationPoint(-21F, -1F, -1.5F);
        tv7.setTextureSize(128, 128);
        tv7.mirror = true;
        setRotation(tv7, 0F, 0F, 0F);
        tv8 = new ModelRenderer(this, 0, 50);
        tv8.addBox(0F, 0F, 0F, 41, 19, 1);
        tv8.setRotationPoint(-20.5F, -0.5F, -2.4F);
        tv8.setTextureSize(128, 128);
        tv8.mirror = true;
        setRotation(tv8, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        tv1.render(f5);
        tv2.render(f5);
        tv3.render(f5);
        tv4.render(f5);
        tv5.render(f5);
        tv6.render(f5);
        tv7.render(f5);
        tv8.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
