// Date: 12/15/2018 2:44:27 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class UziRearSight extends ModelBase {
    //fields
    ModelRenderer sight1;
    ModelRenderer sight2;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight6;
    ModelRenderer sight7;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight12;
    ModelRenderer sight13;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
    ModelRenderer sight20;
    ModelRenderer sight21;
    ModelRenderer sight22;
    ModelRenderer sight23;
    ModelRenderer sight24;
    ModelRenderer sight25;

    public UziRearSight() {
        textureWidth = 128;
        textureHeight = 128;

        sight1 = new ModelRenderer(this, 0, 0);
        sight1.addBox(0F, 0F, 0F, 1, 5, 8);
        sight1.setRotationPoint(0F, 2F, -1F);
        sight1.setTextureSize(128, 128);
        sight1.mirror = true;
        setRotation(sight1, 0F, 0F, 0F);
        sight2 = new ModelRenderer(this, 0, 0);
        sight2.addBox(0F, 0F, 0F, 1, 2, 4);
        sight2.setRotationPoint(0F, 0F, 1F);
        sight2.setTextureSize(128, 128);
        sight2.mirror = true;
        setRotation(sight2, 0F, 0F, 0F);
        sight3 = new ModelRenderer(this, 0, 0);
        sight3.addBox(0F, 0F, 0F, 1, 3, 2);
        sight3.setRotationPoint(0F, 0F, 1F);
        sight3.setTextureSize(128, 128);
        sight3.mirror = true;
        setRotation(sight3, -0.7853982F, 0F, 0F);
        sight4 = new ModelRenderer(this, 0, 0);
        sight4.addBox(0F, 0F, 0F, 1, 2, 3);
        sight4.setRotationPoint(0F, 0F, 5F);
        sight4.setTextureSize(128, 128);
        sight4.mirror = true;
        setRotation(sight4, -0.7853982F, 0F, 0F);
        sight5 = new ModelRenderer(this, 0, 0);
        sight5.addBox(0F, 0F, 0F, 6, 2, 8);
        sight5.setRotationPoint(1F, 5.5F, -1F);
        sight5.setTextureSize(128, 128);
        sight5.mirror = true;
        setRotation(sight5, 0F, 0F, 0F);
        sight6 = new ModelRenderer(this, 0, 0);
        sight6.addBox(0F, 0F, 0F, 1, 5, 8);
        sight6.setRotationPoint(7F, 2F, -1F);
        sight6.setTextureSize(128, 128);
        sight6.mirror = true;
        setRotation(sight6, 0F, 0F, 0F);
        sight7 = new ModelRenderer(this, 0, 0);
        sight7.addBox(0F, 0F, 0F, 1, 2, 4);
        sight7.setRotationPoint(7F, 0F, 1F);
        sight7.setTextureSize(128, 128);
        sight7.mirror = true;
        setRotation(sight7, 0F, 0F, 0F);
        sight8 = new ModelRenderer(this, 0, 0);
        sight8.addBox(0F, 0F, 0F, 1, 2, 3);
        sight8.setRotationPoint(7F, 0F, 5F);
        sight8.setTextureSize(128, 128);
        sight8.mirror = true;
        setRotation(sight8, -0.7853982F, 0F, 0F);
        sight9 = new ModelRenderer(this, 0, 0);
        sight9.addBox(0F, 0F, 0F, 1, 3, 2);
        sight9.setRotationPoint(7F, 0F, 1F);
        sight9.setTextureSize(128, 128);
        sight9.mirror = true;
        setRotation(sight9, -0.7853982F, 0F, 0F);
        sight10 = new ModelRenderer(this, 0, 0);
        sight10.addBox(0F, 0F, 0F, 1, 4, 4);
        sight10.setRotationPoint(-1F, 3F, 0.2F);
        sight10.setTextureSize(128, 128);
        sight10.mirror = true;
        setRotation(sight10, 0.7853982F, 0F, 0F);
        sight11 = new ModelRenderer(this, 0, 0);
        sight11.addBox(0F, 0F, 0F, 6, 2, 2);
        sight11.setRotationPoint(1F, 5.5F, -1F);
        sight11.setTextureSize(128, 128);
        sight11.mirror = true;
        setRotation(sight11, -0.7853982F, 0F, 0F);
        sight12 = new ModelRenderer(this, 0, 0);
        sight12.addBox(0F, 0F, 0F, 6, 1, 1);
        sight12.setRotationPoint(1F, 3.5F, 3F);
        sight12.setTextureSize(128, 128);
        sight12.mirror = true;
        setRotation(sight12, 0F, 0F, 0F);
        sight13 = new ModelRenderer(this, 0, 0);
        sight13.addBox(0F, 0F, 0F, 1, 4, 6);
        sight13.setRotationPoint(0.5F, 1.5F, 0F);
        sight13.setTextureSize(128, 128);
        sight13.mirror = true;
        setRotation(sight13, 0F, 0F, 0F);
        sight14 = new ModelRenderer(this, 0, 0);
        sight14.addBox(0F, 0F, 0F, 1, 4, 6);
        sight14.setRotationPoint(6.5F, 1.5F, 0F);
        sight14.setTextureSize(128, 128);
        sight14.mirror = true;
        setRotation(sight14, 0F, 0F, 0F);
        sight15 = new ModelRenderer(this, 0, 0);
        sight15.addBox(0F, 0F, 0F, 3, 2, 2);
        sight15.setRotationPoint(2.5F, 2.7F, 2.5F);
        sight15.setTextureSize(128, 128);
        sight15.mirror = true;
        setRotation(sight15, 0F, 0F, 0F);
        sight16 = new ModelRenderer(this, 0, 0);
        sight16.addBox(0F, 0F, 0F, 3, 1, 2);
        sight16.setRotationPoint(2.5F, 3.7F, 4.5F);
        sight16.setTextureSize(128, 128);
        sight16.mirror = true;
        setRotation(sight16, 0F, 0F, 0F);
        sight17 = new ModelRenderer(this, 0, 0);
        sight17.addBox(0F, 0F, 0F, 1, 1, 2);
        sight17.setRotationPoint(2.5F, 1.7F, 2.5F);
        sight17.setTextureSize(128, 128);
        sight17.mirror = true;
        setRotation(sight17, 0F, 0F, 0F);
        sight18 = new ModelRenderer(this, 0, 0);
        sight18.addBox(0F, 0F, 0F, 1, 1, 2);
        sight18.setRotationPoint(4.5F, 1.7F, 2.5F);
        sight18.setTextureSize(128, 128);
        sight18.mirror = true;
        setRotation(sight18, 0F, 0F, 0F);
        sight19 = new ModelRenderer(this, 0, 0);
        sight19.addBox(0F, 0F, 0F, 1, 1, 2);
        sight19.setRotationPoint(3.5F, 0.7F, 2.5F);
        sight19.setTextureSize(128, 128);
        sight19.mirror = true;
        setRotation(sight19, 0F, 0F, 0F);
        sight20 = new ModelRenderer(this, 0, 0);
        sight20.addBox(0F, 0F, 0F, 1, 1, 2);
        sight20.setRotationPoint(4.5F, 0.7F, 2.5F);
        sight20.setTextureSize(128, 128);
        sight20.mirror = true;
        setRotation(sight20, 0F, 0F, 0.7853982F);
        sight21 = new ModelRenderer(this, 0, 0);
        sight21.addBox(0F, 0F, 0F, 1, 1, 2);
        sight21.setRotationPoint(3.5F, 0.7F, 2.5F);
        sight21.setTextureSize(128, 128);
        sight21.mirror = true;
        setRotation(sight21, 0F, 0F, 0.7853982F);
        sight22 = new ModelRenderer(this, 0, 0);
        sight22.addBox(0F, 0F, 0F, 1, 1, 2);
        sight22.setRotationPoint(5.5F, 1.7F, 2.5F);
        sight22.setTextureSize(128, 128);
        sight22.mirror = true;
        setRotation(sight22, 0F, 0F, 2.356194F);
        sight23 = new ModelRenderer(this, 0, 0);
        sight23.addBox(0F, 0F, 0F, 1, 1, 2);
        sight23.setRotationPoint(2.5F, 1.7F, 2.5F);
        sight23.setTextureSize(128, 128);
        sight23.mirror = true;
        setRotation(sight23, 0F, 0F, -0.7853982F);
        sight24 = new ModelRenderer(this, 0, 0);
        sight24.addBox(0F, 0F, 0F, 1, 1, 2);
        sight24.setRotationPoint(2.5F, 2.7F, 2.5F);
        sight24.setTextureSize(128, 128);
        sight24.mirror = true;
        setRotation(sight24, 0F, 0F, -0.7853982F);
        sight25 = new ModelRenderer(this, 0, 0);
        sight25.addBox(0F, 0F, 0F, 1, 1, 2);
        sight25.setRotationPoint(5.5F, 2.7F, 2.5F);
        sight25.setTextureSize(128, 128);
        sight25.mirror = true;
        setRotation(sight25, 0F, 0F, 2.356194F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        sight1.render(f5);
        sight2.render(f5);
        sight3.render(f5);
        sight4.render(f5);
        sight5.render(f5);
        sight6.render(f5);
        sight7.render(f5);
        sight8.render(f5);
        sight9.render(f5);
        sight10.render(f5);
        sight11.render(f5);
        sight12.render(f5);
        sight13.render(f5);
        sight14.render(f5);
        sight15.render(f5);
        sight16.render(f5);
        sight17.render(f5);
        sight18.render(f5);
        sight19.render(f5);
        sight20.render(f5);
        sight21.render(f5);
        sight22.render(f5);
        sight23.render(f5);
        sight24.render(f5);
        sight25.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
