// Date: 2/18/2019 5:16:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.paneedah.mwc.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Vent extends ModelBase {
    //fields
    ModelRenderer vent1;
    ModelRenderer vent2;

    public Vent() {
        textureWidth = 128;
        textureHeight = 128;

        vent1 = new ModelRenderer(this, 0, 0);
        vent1.addBox(0F, 0F, 0F, 14, 14, 16);
        vent1.setRotationPoint(-7F, 9F, -8F);
        vent1.setTextureSize(128, 128);
        vent1.mirror = true;
        setRotation(vent1, 0F, 0F, 0F);
        vent2 = new ModelRenderer(this, 0, 40);
        vent2.addBox(0F, 0F, 0F, 15, 15, 1);
        vent2.setRotationPoint(-7.5F, 8.5F, -0.5F);
        vent2.setTextureSize(128, 128);
        vent2.mirror = true;
        setRotation(vent2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        vent1.render(f5);
        vent2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
