org.gradle.jvmargs = -Dfile.encoding=UTF-8 -Xmx2G -XX:+UseStringDeduplication -XX:+UseZGC -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders

org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand = true

org.gradle.parallel = true
