// Date: 10/29/2019 8:45:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ChainsawFuel extends ModelBase
{
  //fields
    ModelRenderer fuel1;
    ModelRenderer fuel2;
    ModelRenderer fuel3;
    ModelRenderer fuel4;
  
  public ChainsawFuel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      fuel1 = new ModelRenderer(this, 0, 0);
      fuel1.addBox(0F, 0F, 0F, 6, 15, 6);
      fuel1.setRotationPoint(0F, -13F, 0F);
      fuel1.setTextureSize(128, 128);
      fuel1.mirror = true;
      setRotation(fuel1, 0F, 0F, 0F);
      fuel2 = new ModelRenderer(this, 0, 50);
      fuel2.addBox(0F, 0F, 0F, 7, 9, 7);
      fuel2.setRotationPoint(-0.5F, -10F, -0.5F);
      fuel2.setTextureSize(128, 128);
      fuel2.mirror = true;
      setRotation(fuel2, 0F, 0F, 0F);
      fuel3 = new ModelRenderer(this, 0, 0);
      fuel3.addBox(0F, 0F, 0F, 7, 3, 7);
      fuel3.setRotationPoint(-0.5F, -13.5F, -0.5F);
      fuel3.setTextureSize(128, 128);
      fuel3.mirror = true;
      setRotation(fuel3, 0F, 0F, 0F);
      fuel4 = new ModelRenderer(this, 0, 0);
      fuel4.addBox(0F, 0F, 0F, 7, 3, 7);
      fuel4.setRotationPoint(-0.5F, -0.5F, -0.5F);
      fuel4.setTextureSize(128, 128);
      fuel4.mirror = true;
      setRotation(fuel4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    fuel1.render(f5);
    fuel2.render(f5);
    fuel3.render(f5);
    fuel4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
