// Date: 2/16/2019 7:14:27 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DeskLeftAlt1 extends ModelBase
{
  //fields
    ModelRenderer desk1;
    ModelRenderer desk2;
    ModelRenderer desk3;
    ModelRenderer desk4;
    ModelRenderer desk5;
    ModelRenderer desk6;
    ModelRenderer desk7;
    ModelRenderer desk8;
    ModelRenderer desk9;
    ModelRenderer desk10;
  
  public DeskLeftAlt1()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      desk1 = new ModelRenderer(this, 0, 0);
      desk1.addBox(0F, 0F, 0F, 15, 15, 1);
      desk1.setRotationPoint(-7F, 8F, 6.5F);
      desk1.setTextureSize(64, 32);
      desk1.mirror = true;
      setRotation(desk1, 0F, 0F, 0F);
      desk2 = new ModelRenderer(this, 0, 50);
      desk2.addBox(0F, 0F, 0F, 1, 7, 5);
      desk2.setRotationPoint(-4.9F, 17F, -5.5F);
      desk2.setTextureSize(64, 32);
      desk2.mirror = true;
      setRotation(desk2, 0F, -0.5205006F, 0F);
      desk3 = new ModelRenderer(this, 0, 0);
      desk3.addBox(0F, 0F, 0F, 16, 4, 13);
      desk3.setRotationPoint(-8F, 8F, -6.5F);
      desk3.setTextureSize(64, 32);
      desk3.mirror = true;
      setRotation(desk3, 0F, 0F, 0F);
      desk4 = new ModelRenderer(this, 0, 0);
      desk4.addBox(0F, 0F, 0F, 2, 16, 13);
      desk4.setRotationPoint(0F, 8.05F, -6.3F);
      desk4.setTextureSize(64, 32);
      desk4.mirror = true;
      setRotation(desk4, 0F, 0F, 0F);
      desk5 = new ModelRenderer(this, 0, 0);
      desk5.addBox(0F, 0F, 0F, 2, 16, 2);
      desk5.setRotationPoint(-8F, 8.05F, 5.6F);
      desk5.setTextureSize(64, 32);
      desk5.mirror = true;
      setRotation(desk5, 0F, 0F, 0F);
      desk6 = new ModelRenderer(this, 0, 0);
      desk6.addBox(0F, 0F, 0F, 2, 16, 13);
      desk6.setRotationPoint(6F, 8.05F, -6.3F);
      desk6.setTextureSize(64, 32);
      desk6.mirror = true;
      setRotation(desk6, 0F, 0F, 0F);
      desk7 = new ModelRenderer(this, 0, 0);
      desk7.addBox(0F, 0F, 0F, 4, 16, 13);
      desk7.setRotationPoint(2F, 8.05F, -6.1F);
      desk7.setTextureSize(64, 32);
      desk7.mirror = true;
      setRotation(desk7, 0F, 0F, 0F);
      desk8 = new ModelRenderer(this, 0, 50);
      desk8.addBox(4F, 0F, 0F, 1, 7, 5);
      desk8.setRotationPoint(-4.9F, 17F, -5.5F);
      desk8.setTextureSize(64, 32);
      desk8.mirror = true;
      setRotation(desk8, 0F, -0.5205006F, 0F);
      desk9 = new ModelRenderer(this, 0, 50);
      desk9.addBox(1F, 0F, 0F, 3, 7, 1);
      desk9.setRotationPoint(-4.9F, 17F, -5.5F);
      desk9.setTextureSize(64, 32);
      desk9.mirror = true;
      setRotation(desk9, 0F, -0.5205006F, 0F);
      desk10 = new ModelRenderer(this, 0, 50);
      desk10.addBox(1F, 0F, 4F, 3, 7, 1);
      desk10.setRotationPoint(-4.9F, 17F, -5.5F);
      desk10.setTextureSize(64, 32);
      desk10.mirror = true;
      setRotation(desk10, 0F, -0.5205006F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    desk1.render(f5);
    desk2.render(f5);
    desk3.render(f5);
    desk4.render(f5);
    desk5.render(f5);
    desk6.render(f5);
    desk7.render(f5);
    desk8.render(f5);
    desk9.render(f5);
    desk10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
