// Date: 2/16/2019 1:46:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FilingCabinet extends ModelBase
{
  //fields
    ModelRenderer cabinet1;
    ModelRenderer cabinet2;
    ModelRenderer cabinet3;
    ModelRenderer cabinet4;
    ModelRenderer cabinet5;
  
  public FilingCabinet()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      cabinet1 = new ModelRenderer(this, 0, 0);
      cabinet1.addBox(0F, 0F, 0F, 13, 16, 14);
      cabinet1.setRotationPoint(-6.5F, 8F, -6.5F);
      cabinet1.setTextureSize(256, 256);
      cabinet1.mirror = true;
      setRotation(cabinet1, 0F, 0F, 0F);
      cabinet2 = new ModelRenderer(this, 0, 0);
      cabinet2.addBox(0F, 0F, 0F, 11, 6, 1);
      cabinet2.setRotationPoint(-5.5F, 16F, -6.7F);
      cabinet2.setTextureSize(256, 256);
      cabinet2.mirror = true;
      setRotation(cabinet2, 0F, 0F, 0F);
      cabinet3 = new ModelRenderer(this, 0, 0);
      cabinet3.addBox(0F, 0F, 0F, 5, 2, 1);
      cabinet3.setRotationPoint(-2.5F, 18F, -7.3F);
      cabinet3.setTextureSize(256, 256);
      cabinet3.mirror = true;
      setRotation(cabinet3, 0.1487144F, 0F, 0F);
      cabinet4 = new ModelRenderer(this, 0, 0);
      cabinet4.addBox(0F, 0F, 0F, 11, 6, 1);
      cabinet4.setRotationPoint(-5.5F, 9.5F, -6.7F);
      cabinet4.setTextureSize(256, 256);
      cabinet4.mirror = true;
      setRotation(cabinet4, 0F, 0F, 0F);
      cabinet5 = new ModelRenderer(this, 0, 0);
      cabinet5.addBox(0F, 0F, 0F, 5, 2, 1);
      cabinet5.setRotationPoint(-2.5F, 11.5F, -7.3F);
      cabinet5.setTextureSize(256, 256);
      cabinet5.mirror = true;
      setRotation(cabinet5, 0.1487144F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    cabinet1.render(f5);
    cabinet2.render(f5);
    cabinet3.render(f5);
    cabinet4.render(f5);
    cabinet5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
