// Date: 6/25/2019 3:48:59 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class HeraArmsGrip extends ModelBase
{
  //fields
    ModelRenderer grip1;
    ModelRenderer grip2;
    ModelRenderer grip3;
    ModelRenderer grip4;
    ModelRenderer grip5;
    ModelRenderer grip6;
    ModelRenderer grip7;
    ModelRenderer grip11;
    ModelRenderer grip12;
    ModelRenderer grip13;
    ModelRenderer grip14;
    ModelRenderer grip15;
  
  public HeraArmsGrip()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      grip1 = new ModelRenderer(this, 0, 0);
      grip1.addBox(0F, 0F, 0F, 4, 5, 5);
      grip1.setRotationPoint(-3.5F, -7F, -6F);
      grip1.setTextureSize(64, 32);
      grip1.mirror = true;
      setRotation(grip1, 0F, 0F, 0F);
      grip2 = new ModelRenderer(this, 0, 0);
      grip2.addBox(0F, -0.5F, 0F, 4, 11, 4);
      grip2.setRotationPoint(-3.5F, -2F, -5.5F);
      grip2.setTextureSize(64, 32);
      grip2.mirror = true;
      setRotation(grip2, 0.3717861F, 0F, 0F);
      grip3 = new ModelRenderer(this, 0, 0);
      grip3.addBox(0F, 0F, -0.2F, 4, 3, 13);
      grip3.setRotationPoint(-3.5F, -5F, -1F);
      grip3.setTextureSize(64, 32);
      grip3.mirror = true;
      setRotation(grip3, -1.041001F, 0F, 0F);
      grip4 = new ModelRenderer(this, 0, 0);
      grip4.addBox(0F, 0F, 0F, 4, 2, 1);
      grip4.setRotationPoint(-3.5F, 7.2F, -2.6F);
      grip4.setTextureSize(64, 32);
      grip4.mirror = true;
      setRotation(grip4, 0.3717861F, 0F, 0F);
      grip5 = new ModelRenderer(this, 0, 0);
      grip5.addBox(0F, 0F, 0F, 4, 1, 1);
      grip5.setRotationPoint(-3.5F, 7.2F, -2.6F);
      grip5.setTextureSize(64, 32);
      grip5.mirror = true;
      setRotation(grip5, 1.07818F, 0F, 0F);
      grip6 = new ModelRenderer(this, 0, 0);
      grip6.addBox(0F, 0F, 0F, 3, 5, 2);
      grip6.setRotationPoint(-3F, -8F, -1.5F);
      grip6.setTextureSize(64, 32);
      grip6.mirror = true;
      setRotation(grip6, 0F, 0F, 0F);
      grip7 = new ModelRenderer(this, 0, 0);
      grip7.addBox(0F, -1F, 0F, 3, 1, 12);
      grip7.setRotationPoint(-3F, -5F, -1F);
      grip7.setTextureSize(64, 32);
      grip7.mirror = true;
      setRotation(grip7, -1.07818F, 0F, 0F);
      grip11 = new ModelRenderer(this, 0, 0);
      grip11.addBox(0F, 0F, 1F, 1, 12, 4);
      grip11.setRotationPoint(-0.4F, -2F, -5.5F);
      grip11.setTextureSize(64, 32);
      grip11.mirror = true;
      setRotation(grip11, 0.3717861F, 0F, 0F);
      grip12 = new ModelRenderer(this, 0, 0);
      grip12.addBox(0F, 0.5F, 1F, 1, 9, 4);
      grip12.setRotationPoint(-3.6F, -2F, -5.5F);
      grip12.setTextureSize(64, 32);
      grip12.mirror = true;
      setRotation(grip12, 0.3717861F, 0F, 0F);
      grip13 = new ModelRenderer(this, 0, 0);
      grip13.addBox(0F, -2F, 0F, 4, 3, 3);
      grip13.setRotationPoint(-3.5F, 8.1F, -1.8F);
      grip13.setTextureSize(64, 32);
      grip13.mirror = true;
      setRotation(grip13, -0.0743572F, 0F, 0F);
      grip14 = new ModelRenderer(this, 0, 0);
      grip14.addBox(0F, 0F, 0F, 4, 7, 1);
      grip14.setRotationPoint(-3.5F, 9.3F, 1.1F);
      grip14.setTextureSize(64, 32);
      grip14.mirror = true;
      setRotation(grip14, 2.193538F, 0F, 0F);
      grip15 = new ModelRenderer(this, 0, 0);
      grip15.addBox(0F, 0F, 0F, 4, 1, 2);
      grip15.setRotationPoint(-3.5F, 4.5F, 4.2F);
      grip15.setTextureSize(64, 32);
      grip15.mirror = true;
      setRotation(grip15, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    grip1.render(f5);
    grip2.render(f5);
    grip3.render(f5);
    grip4.render(f5);
    grip5.render(f5);
    grip6.render(f5);
    grip7.render(f5);
    grip11.render(f5);
    grip12.render(f5);
    grip13.render(f5);
    grip14.render(f5);
    grip15.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
