// Date: 2/28/2020 4:32:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M1A1Grip extends ModelBase
{
  //fields
    
    ModelRenderer grip1;
    ModelRenderer grip2;
    ModelRenderer grip3;
    ModelRenderer grip4;
    ModelRenderer grip5;
    ModelRenderer grip6;
    ModelRenderer grip7;
    ModelRenderer grip8;
    ModelRenderer grip9;
    ModelRenderer grip10;
    ModelRenderer grip11;
    ModelRenderer grip12;
    ModelRenderer grip13;
    ModelRenderer grip14;
    ModelRenderer grip15;
    ModelRenderer grip16;
    ModelRenderer grip17;
    ModelRenderer grip18;
    ModelRenderer grip19;
  
  public M1A1Grip()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      grip1 = new ModelRenderer(this, 250, 0);
      grip1.addBox(0F, 0F, 0F, 3, 1, 21);
      grip1.setRotationPoint(-2.5F, -9F, -40.5F);
      grip1.setTextureSize(64, 32);
      grip1.mirror = true;
      setRotation(grip1, 0F, 0F, 0F);
      grip2 = new ModelRenderer(this, 250, 0);
      grip2.addBox(0F, 0F, 0F, 4, 1, 21);
      grip2.setRotationPoint(-3F, -8.1F, -40.5F);
      grip2.setTextureSize(64, 32);
      grip2.mirror = true;
      setRotation(grip2, 0F, 0F, 0F);
      grip3 = new ModelRenderer(this, 250, 0);
      grip3.addBox(0F, 0F, 0F, 4, 2, 5);
      grip3.setRotationPoint(-3F, -7.1F, -40.5F);
      grip3.setTextureSize(64, 32);
      grip3.mirror = true;
      setRotation(grip3, 0F, 0F, 0F);
      grip4 = new ModelRenderer(this, 250, 0);
      grip4.addBox(0F, 0F, 0F, 1, 1, 11);
      grip4.setRotationPoint(-3F, -5.7F, -35.5F);
      grip4.setTextureSize(64, 32);
      grip4.mirror = true;
      setRotation(grip4, 0F, 0F, -0.5934119F);
      grip5 = new ModelRenderer(this, 250, 0);
      grip5.addBox(0F, 0F, 0F, 1, 21, 1);
      grip5.setRotationPoint(-2.8F, -4.6F, -40.5F);
      grip5.setTextureSize(64, 32);
      grip5.mirror = true;
      setRotation(grip5, 1.561502F, 0F, 0F);
      grip6 = new ModelRenderer(this, 250, 0);
      grip6.addBox(0F, 0F, 0F, 4, 2, 5);
      grip6.setRotationPoint(-3F, -7.1F, -24.5F);
      grip6.setTextureSize(64, 32);
      grip6.mirror = true;
      setRotation(grip6, 0F, 0F, 0F);
      grip7 = new ModelRenderer(this, 250, 0);
      grip7.addBox(0F, 0F, -0.4F, 3, 21, 1);
      grip7.setRotationPoint(-2.5F, -4.6F, -40.5F);
      grip7.setTextureSize(64, 32);
      grip7.mirror = true;
      setRotation(grip7, 1.561502F, 0F, 0F);
      grip8 = new ModelRenderer(this, 250, 0);
      grip8.addBox(0F, 0F, 0F, 1, 1, 21);
      grip8.setRotationPoint(-2.5F, -9F, -40.5F);
      grip8.setTextureSize(64, 32);
      grip8.mirror = true;
      setRotation(grip8, 0F, 0F, 0.5235988F);
      grip9 = new ModelRenderer(this, 250, 0);
      grip9.addBox(-1F, 0F, 0F, 1, 1, 21);
      grip9.setRotationPoint(0.5F, -9F, -40.5F);
      grip9.setTextureSize(64, 32);
      grip9.mirror = true;
      setRotation(grip9, 0F, 0F, -0.5235988F);
      grip10 = new ModelRenderer(this, 250, 0);
      grip10.addBox(0F, 0F, 0F, 3, 2, 11);
      grip10.setRotationPoint(-2.5F, -7.1F, -35.5F);
      grip10.setTextureSize(64, 32);
      grip10.mirror = true;
      setRotation(grip10, 0F, 0F, 0F);
      grip11 = new ModelRenderer(this, 250, 0);
      grip11.addBox(0F, 0F, 0F, 4, 1, 11);
      grip11.setRotationPoint(-3F, -5.7F, -35.5F);
      grip11.setTextureSize(64, 32);
      grip11.mirror = true;
      setRotation(grip11, 0F, 0F, 0F);
      grip12 = new ModelRenderer(this, 250, 0);
      grip12.addBox(-1F, 0F, 0F, 1, 1, 11);
      grip12.setRotationPoint(1F, -5.7F, -35.5F);
      grip12.setTextureSize(64, 32);
      grip12.mirror = true;
      setRotation(grip12, 0F, 0F, 0.5934119F);
      grip13 = new ModelRenderer(this, 250, 0);
      grip13.addBox(-1F, 0F, 0F, 1, 1, 11);
      grip13.setRotationPoint(1F, -7.1F, -35.5F);
      grip13.setTextureSize(64, 32);
      grip13.mirror = true;
      setRotation(grip13, 0F, 0F, 0.8536622F);
      grip14 = new ModelRenderer(this, 250, 0);
      grip14.addBox(0F, 0F, 0F, 1, 1, 11);
      grip14.setRotationPoint(-3F, -7.1F, -35.5F);
      grip14.setTextureSize(64, 32);
      grip14.mirror = true;
      setRotation(grip14, 0F, 0F, -0.853658F);
      grip15 = new ModelRenderer(this, 250, 0);
      grip15.addBox(0F, 0F, 0F, 4, 1, 2);
      grip15.setRotationPoint(-3F, -6.6F, -24.5F);
      grip15.setTextureSize(64, 32);
      grip15.mirror = true;
      setRotation(grip15, 2.899932F, 0F, 0F);
      grip16 = new ModelRenderer(this, 250, 0);
      grip16.addBox(0F, -1F, 0F, 4, 1, 2);
      grip16.setRotationPoint(-3F, -6.2F, -24.5F);
      grip16.setTextureSize(64, 32);
      grip16.mirror = true;
      setRotation(grip16, -2.899934F, 0F, 0F);
      grip17 = new ModelRenderer(this, 250, 0);
      grip17.addBox(0F, -1F, -2F, 4, 1, 2);
      grip17.setRotationPoint(-3F, -6.2F, -35.5F);
      grip17.setTextureSize(64, 32);
      grip17.mirror = true;
      setRotation(grip17, 2.899934F, 0F, 0F);
      grip18 = new ModelRenderer(this, 250, 0);
      grip18.addBox(0F, 0F, -2F, 4, 1, 2);
      grip18.setRotationPoint(-3F, -6.6F, -35.5F);
      grip18.setTextureSize(64, 32);
      grip18.mirror = true;
      setRotation(grip18, -2.899934F, 0F, 0F);
      grip19 = new ModelRenderer(this, 250, 0);
      grip19.addBox(0F, 0F, 0F, 1, 21, 1);
      grip19.setRotationPoint(-0.2F, -4.6F, -40.5F);
      grip19.setTextureSize(64, 32);
      grip19.mirror = true;
      setRotation(grip19, 1.561502F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    grip1.render(f5);
    grip2.render(f5);
    grip3.render(f5);
    grip4.render(f5);
    grip5.render(f5);
    grip6.render(f5);
    grip7.render(f5);
    grip8.render(f5);
    grip9.render(f5);
    grip10.render(f5);
    grip11.render(f5);
    grip12.render(f5);
    grip13.render(f5);
    grip14.render(f5);
    grip15.render(f5);
    grip16.render(f5);
    grip17.render(f5);
    grip18.render(f5);
    grip19.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
