// Date: 9/30/2017 12:29:45 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class P226rearsight extends ModelBase
{
  //fields
    ModelRenderer sight1;
    ModelRenderer sight2;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight6;
    ModelRenderer sight7;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
    ModelRenderer sight25;
    ModelRenderer sight26;
    ModelRenderer sight30;
    ModelRenderer sight31;
    ModelRenderer sight32;
    ModelRenderer sight33;
    ModelRenderer sight41;
    ModelRenderer sight42;
    ModelRenderer sight44;
    ModelRenderer sight45;
  
  public P226rearsight()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      sight1 = new ModelRenderer(this, 50, 0);
      sight1.addBox(0F, 0F, 0F, 1, 1, 1);
      sight1.setRotationPoint(-1F, -1.5F, 0.1F);
      sight1.setTextureSize(64, 32);
      sight1.mirror = true;
      setRotation(sight1, 0F, 0F, 0F);
      sight2 = new ModelRenderer(this, 0, 0);
      sight2.addBox(0F, 0F, 0F, 1, 1, 1);
      sight2.setRotationPoint(-1F, -1.2F, 0F);
      sight2.setTextureSize(64, 32);
      sight2.mirror = true;
      setRotation(sight2, 0F, 0F, 0F);
      sight3 = new ModelRenderer(this, 0, 0);
      sight3.addBox(0F, 0F, 0F, 2, 1, 1);
      sight3.setRotationPoint(-1.7F, -1.8F, 0F);
      sight3.setTextureSize(64, 32);
      sight3.mirror = true;
      setRotation(sight3, 0F, 0F, 0F);
      sight4 = new ModelRenderer(this, 0, 0);
      sight4.addBox(0F, 0F, 0F, 2, 1, 1);
      sight4.setRotationPoint(-1.7F, -1.2F, 0F);
      sight4.setTextureSize(64, 32);
      sight4.mirror = true;
      setRotation(sight4, 0F, 0F, 0F);
      sight5 = new ModelRenderer(this, 0, 0);
      sight5.addBox(0F, 0F, 0F, 2, 1, 1);
      sight5.setRotationPoint(2.7F, -1.8F, 0F);
      sight5.setTextureSize(64, 32);
      sight5.mirror = true;
      setRotation(sight5, 0F, 0F, 0F);
      sight6 = new ModelRenderer(this, 50, 0);
      sight6.addBox(0F, 0F, 0F, 1, 1, 1);
      sight6.setRotationPoint(3F, -1.5F, 0.1F);
      sight6.setTextureSize(64, 32);
      sight6.mirror = true;
      setRotation(sight6, 0F, 0F, 0F);
      sight7 = new ModelRenderer(this, 0, 0);
      sight7.addBox(0F, 0F, 0F, 2, 1, 1);
      sight7.setRotationPoint(2.7F, -1.2F, 0F);
      sight7.setTextureSize(64, 32);
      sight7.mirror = true;
      setRotation(sight7, 0F, 0F, 0F);
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 3, 3, 1);
      sight8.setRotationPoint(1.7F, -0.2F, 0F);
      sight8.setTextureSize(64, 32);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, 0F);
      sight9 = new ModelRenderer(this, 0, 0);
      sight9.addBox(0F, 0F, 0F, 4, 3, 1);
      sight9.setRotationPoint(-1.7F, -0.2F, 0F);
      sight9.setTextureSize(64, 32);
      sight9.mirror = true;
      setRotation(sight9, 0F, 0F, 0F);
      sight10 = new ModelRenderer(this, 0, 0);
      sight10.addBox(0F, 0F, 0F, 2, 5, 2);
      sight10.setRotationPoint(4.3F, -2.8F, -1F);
      sight10.setTextureSize(64, 32);
      sight10.mirror = true;
      setRotation(sight10, 0F, 0F, 0F);
      sight11 = new ModelRenderer(this, 0, 0);
      sight11.addBox(0F, 0F, 0F, 2, 5, 2);
      sight11.setRotationPoint(-3.3F, -2.8F, -1F);
      sight11.setTextureSize(64, 32);
      sight11.mirror = true;
      setRotation(sight11, 0F, 0F, 0F);
      sight14 = new ModelRenderer(this, 0, 0);
      sight14.addBox(0F, 0F, 0F, 6, 2, 2);
      sight14.setRotationPoint(-1.5F, 1F, 0.6F);
      sight14.setTextureSize(64, 32);
      sight14.mirror = true;
      setRotation(sight14, 0F, 0F, 0F);
      sight15 = new ModelRenderer(this, 0, 0);
      sight15.addBox(0F, 0F, 0F, 2, 1, 1);
      sight15.setRotationPoint(-3.3F, -2.8F, 0.5F);
      sight15.setTextureSize(64, 32);
      sight15.mirror = true;
      setRotation(sight15, 0F, 0F, 0F);
      sight16 = new ModelRenderer(this, 0, 0);
      sight16.addBox(0F, 0F, 0F, 2, 1, 1);
      sight16.setRotationPoint(4.3F, -1.8F, 0.5F);
      sight16.setTextureSize(64, 32);
      sight16.mirror = true;
      setRotation(sight16, 0F, 0F, 0F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 2, 3, 6);
      sight17.setRotationPoint(4.3F, -2.8F, 1.5F);
      sight17.setTextureSize(64, 32);
      sight17.mirror = true;
      setRotation(sight17, -1.301251F, 0F, 0F);
      sight18 = new ModelRenderer(this, 0, 0);
      sight18.addBox(0F, 0F, 0F, 2, 3, 6);
      sight18.setRotationPoint(-3.3F, -2.8F, 1.5F);
      sight18.setTextureSize(64, 32);
      sight18.mirror = true;
      setRotation(sight18, -1.301251F, 0F, 0F);
      sight19 = new ModelRenderer(this, 0, 0);
      sight19.addBox(0F, 0F, 0F, 6, 1, 2);
      sight19.setRotationPoint(-1.5F, 1F, 2.6F);
      sight19.setTextureSize(64, 32);
      sight19.mirror = true;
      setRotation(sight19, -1.301251F, 0F, 0F);
      sight25 = new ModelRenderer(this, 0, 0);
      sight25.addBox(0F, 0F, 0F, 2, 12, 4);
      sight25.setRotationPoint(-3.3F, -2.8F, -1F);
      sight25.setTextureSize(64, 32);
      sight25.mirror = true;
      setRotation(sight25, -1.301251F, 0F, 0F);
      sight26 = new ModelRenderer(this, 0, 0);
      sight26.addBox(0F, 0F, 0F, 2, 12, 4);
      sight26.setRotationPoint(4.3F, -2.8F, -1F);
      sight26.setTextureSize(64, 32);
      sight26.mirror = true;
      setRotation(sight26, -1.301251F, 0F, 0F);
      sight30 = new ModelRenderer(this, 0, 0);
      sight30.addBox(0F, 0F, 0F, 4, 1, 11);
      sight30.setRotationPoint(-0.5F, 0.8F, -11.6F);
      sight30.setTextureSize(64, 32);
      sight30.mirror = true;
      setRotation(sight30, 0F, 0F, 0F);
      sight31 = new ModelRenderer(this, 0, 0);
      sight31.addBox(0F, 0F, 0F, 2, 3, 1);
      sight31.setRotationPoint(-3.3F, 0.2F, -0.5F);
      sight31.setTextureSize(64, 32);
      sight31.mirror = true;
      setRotation(sight31, 0F, 0F, 0F);
      sight32 = new ModelRenderer(this, 0, 0);
      sight32.addBox(0F, 0F, 0F, 2, 3, 1);
      sight32.setRotationPoint(4.3F, 0.2F, -0.5F);
      sight32.setTextureSize(64, 32);
      sight32.mirror = true;
      setRotation(sight32, 0F, 0F, 0F);
      sight33 = new ModelRenderer(this, 0, 0);
      sight33.addBox(0F, 0F, 0F, 2, 1, 1);
      sight33.setRotationPoint(4.3F, -2.8F, 0.5F);
      sight33.setTextureSize(64, 32);
      sight33.mirror = true;
      setRotation(sight33, 0F, 0F, 0F);
      sight41 = new ModelRenderer(this, 0, 0);
      sight41.addBox(0F, 0F, 0F, 2, 2, 6);
      sight41.setRotationPoint(-3.3F, 1.2F, -6.5F);
      sight41.setTextureSize(64, 32);
      sight41.mirror = true;
      setRotation(sight41, 0F, 0F, 0F);
      sight42 = new ModelRenderer(this, 0, 0);
      sight42.addBox(0F, 0F, 0F, 2, 2, 6);
      sight42.setRotationPoint(4.3F, 1.2F, -6.5F);
      sight42.setTextureSize(64, 32);
      sight42.mirror = true;
      setRotation(sight42, 0F, 0F, 0F);
      sight44 = new ModelRenderer(this, 0, 0);
      sight44.addBox(0F, 0F, 0F, 2, 12, 3);
      sight44.setRotationPoint(-2F, -1.8F, 0F);
      sight44.setTextureSize(64, 32);
      sight44.mirror = true;
      setRotation(sight44, -1.375609F, 0F, 0F);
      sight45 = new ModelRenderer(this, 0, 0);
      sight45.addBox(0F, 0F, 0F, 2, 12, 3);
      sight45.setRotationPoint(3F, -1.8F, 0F);
      sight45.setTextureSize(64, 32);
      sight45.mirror = true;
      setRotation(sight45, -1.375609F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight1.render(f5);
    sight2.render(f5);
    sight3.render(f5);
    sight4.render(f5);
    sight5.render(f5);
    sight6.render(f5);
    sight7.render(f5);
    sight8.render(f5);
    sight9.render(f5);
    sight10.render(f5);
    sight11.render(f5);
    sight14.render(f5);
    sight15.render(f5);
    sight16.render(f5);
    sight17.render(f5);
    sight18.render(f5);
    sight19.render(f5);
    sight25.render(f5);
    sight26.render(f5);
    sight30.render(f5);
    sight31.render(f5);
    sight32.render(f5);
    sight33.render(f5);
    sight41.render(f5);
    sight42.render(f5);
    sight44.render(f5);
    sight45.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
