// Date: 10/10/2017 7:41:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Saiga12mag extends ModelBase
{
  //fields
    ModelRenderer Mag1;
    ModelRenderer Mag2;
    ModelRenderer Mag3;
    ModelRenderer Mag4;
    ModelRenderer Mag5;
    ModelRenderer Mag6;
    ModelRenderer Mag7;
    ModelRenderer Mag8;
    ModelRenderer Mag9;
    ModelRenderer Mag10;
    ModelRenderer Mag11;
    ModelRenderer Mag12;
    ModelRenderer Mag13;
    ModelRenderer Mag14;
    ModelRenderer Mag15;
    ModelRenderer Mag16;
    ModelRenderer Mag17;
    ModelRenderer Mag18;
    ModelRenderer Mag19;
    ModelRenderer Mag20;
    ModelRenderer Mag21;
    ModelRenderer Mag22;
    ModelRenderer Mag23;
    ModelRenderer Mag24;
    ModelRenderer Mag25;
  
  public Saiga12mag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Mag1 = new ModelRenderer(this, 0, 0);
      Mag1.addBox(0F, 0F, 0F, 3, 17, 5);
      Mag1.setRotationPoint(-3.2F, -7F, -31F);
      Mag1.setTextureSize(64, 32);
      Mag1.mirror = true;
      setRotation(Mag1, -0.2094395F, 0F, 0F);
      Mag2 = new ModelRenderer(this, 0, 0);
      Mag2.addBox(0F, 0F, 0F, 4, 3, 1);
      Mag2.setRotationPoint(-3.5F, -7F, -20.8F);
      Mag2.setTextureSize(64, 32);
      Mag2.mirror = true;
      setRotation(Mag2, -0.2094395F, 0F, 0F);
      Mag3 = new ModelRenderer(this, 0, 0);
      Mag3.addBox(0F, 0F, 0F, 3, 2, 10);
      Mag3.setRotationPoint(-3.2F, -7F, -31F);
      Mag3.setTextureSize(64, 32);
      Mag3.mirror = true;
      setRotation(Mag3, 0F, 0F, 0F);
      Mag4 = new ModelRenderer(this, 0, 0);
      Mag4.addBox(0F, 0F, 0F, 4, 1, 1);
      Mag4.setRotationPoint(-3.5F, -5F, -22F);
      Mag4.setTextureSize(64, 32);
      Mag4.mirror = true;
      setRotation(Mag4, 0F, 0F, 0F);
      Mag5 = new ModelRenderer(this, 0, 0);
      Mag5.addBox(0F, 0F, 0F, 3, 5, 1);
      Mag5.setRotationPoint(-3.2F, 4.6F, -33.3F);
      Mag5.setTextureSize(64, 32);
      Mag5.mirror = true;
      setRotation(Mag5, -0.4325112F, 0F, 0F);
      Mag6 = new ModelRenderer(this, 0, 0);
      Mag6.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag6.setRotationPoint(-2.9F, -6.8F, -26.2F);
      Mag6.setTextureSize(64, 32);
      Mag6.mirror = true;
      setRotation(Mag6, 0F, 0F, 0.7853982F);
      Mag7 = new ModelRenderer(this, 0, 0);
      Mag7.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag7.setRotationPoint(-2.9F, -6.2F, -26.3F);
      Mag7.setTextureSize(64, 32);
      Mag7.mirror = true;
      setRotation(Mag7, 0F, 0F, 0.7853982F);
      Mag8 = new ModelRenderer(this, 0, 0);
      Mag8.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag8.setRotationPoint(-2.9F, -5.6F, -26.5F);
      Mag8.setTextureSize(64, 32);
      Mag8.mirror = true;
      setRotation(Mag8, 0F, 0F, 0.7853982F);
      Mag9 = new ModelRenderer(this, 0, 0);
      Mag9.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag9.setRotationPoint(-0.1F, -6.8F, -26.2F);
      Mag9.setTextureSize(64, 32);
      Mag9.mirror = true;
      setRotation(Mag9, 0F, 0F, 0.7853982F);
      Mag10 = new ModelRenderer(this, 0, 0);
      Mag10.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag10.setRotationPoint(-0.1F, -6.2F, -26.3F);
      Mag10.setTextureSize(64, 32);
      Mag10.mirror = true;
      setRotation(Mag10, 0F, 0F, 0.7853982F);
      Mag11 = new ModelRenderer(this, 0, 0);
      Mag11.addBox(0F, 0F, 0F, 1, 1, 6);
      Mag11.setRotationPoint(-0.1F, -5.6F, -26.5F);
      Mag11.setTextureSize(64, 32);
      Mag11.mirror = true;
      setRotation(Mag11, 0F, 0F, 0.7853982F);
      Mag12 = new ModelRenderer(this, 0, 0);
      Mag12.addBox(0F, 0F, 0F, 1, 17, 5);
      Mag12.setRotationPoint(-0.8F, -7F, -31F);
      Mag12.setTextureSize(64, 32);
      Mag12.mirror = true;
      setRotation(Mag12, -0.2094395F, 0F, 0F);
      Mag13 = new ModelRenderer(this, 0, 0);
      Mag13.addBox(0F, 0F, 0F, 4, 18, 6);
      Mag13.setRotationPoint(-3.5F, -7F, -26F);
      Mag13.setTextureSize(64, 32);
      Mag13.mirror = true;
      setRotation(Mag13, -0.2094395F, 0F, 0F);
      Mag14 = new ModelRenderer(this, 0, 0);
      Mag14.addBox(0F, 0F, 0F, 1, 5, 1);
      Mag14.setRotationPoint(-0.8F, 4.6F, -33.3F);
      Mag14.setTextureSize(64, 32);
      Mag14.mirror = true;
      setRotation(Mag14, -0.4325112F, 0F, 0F);
      Mag15 = new ModelRenderer(this, 0, 0);
      Mag15.addBox(0F, 0F, 0F, 1, 2, 10);
      Mag15.setRotationPoint(-0.8F, -7F, -31F);
      Mag15.setTextureSize(64, 32);
      Mag15.mirror = true;
      setRotation(Mag15, 0F, 0F, 0F);
      Mag16 = new ModelRenderer(this, 0, 0);
      Mag16.addBox(0F, 0F, 0F, 4, 2, 5);
      Mag16.setRotationPoint(-3.5F, -7F, -26F);
      Mag16.setTextureSize(64, 32);
      Mag16.mirror = true;
      setRotation(Mag16, 0F, 0F, 0F);
      Mag17 = new ModelRenderer(this, 0, 0);
      Mag17.addBox(0F, 0F, 0F, 4, 2, 1);
      Mag17.setRotationPoint(-3.5F, -7F, -21.8F);
      Mag17.setTextureSize(64, 32);
      Mag17.mirror = true;
      setRotation(Mag17, 0F, 0F, 0F);
      Mag18 = new ModelRenderer(this, 0, 0);
      Mag18.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag18.setRotationPoint(-0.4F, -5.6F, -31.3F);
      Mag18.setTextureSize(64, 32);
      Mag18.mirror = true;
      setRotation(Mag18, 0F, 0F, 0.7853982F);
      Mag19 = new ModelRenderer(this, 0, 0);
      Mag19.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag19.setRotationPoint(-0.4F, -6.2F, -31F);
      Mag19.setTextureSize(64, 32);
      Mag19.mirror = true;
      setRotation(Mag19, 0F, 0F, 0.7853982F);
      Mag20 = new ModelRenderer(this, 0, 0);
      Mag20.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag20.setRotationPoint(-2.6F, -5.6F, -31.3F);
      Mag20.setTextureSize(64, 32);
      Mag20.mirror = true;
      setRotation(Mag20, 0F, 0F, 0.7853982F);
      Mag21 = new ModelRenderer(this, 0, 0);
      Mag21.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag21.setRotationPoint(-2.6F, -6.2F, -31F);
      Mag21.setTextureSize(64, 32);
      Mag21.mirror = true;
      setRotation(Mag21, 0F, 0F, 0.7853982F);
      Mag22 = new ModelRenderer(this, 0, 0);
      Mag22.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag22.setRotationPoint(-0.4F, -6.8F, -30.7F);
      Mag22.setTextureSize(64, 32);
      Mag22.mirror = true;
      setRotation(Mag22, 0F, 0F, 0.7853982F);
      Mag23 = new ModelRenderer(this, 0, 0);
      Mag23.addBox(0F, 0F, 0F, 1, 1, 5);
      Mag23.setRotationPoint(-2.6F, -6.8F, -30.7F);
      Mag23.setTextureSize(64, 32);
      Mag23.mirror = true;
      setRotation(Mag23, 0F, 0F, 0.7853982F);
      Mag24 = new ModelRenderer(this, 0, 0);
      Mag24.addBox(0F, 0F, 0F, 1, 2, 1);
      Mag24.setRotationPoint(-3.65F, -6.5F, -20.9F);
      Mag24.setTextureSize(64, 32);
      Mag24.mirror = true;
      setRotation(Mag24, -0.2094395F, 0F, 0F);
      Mag25 = new ModelRenderer(this, 0, 0);
      Mag25.addBox(0F, 0F, 0F, 1, 2, 1);
      Mag25.setRotationPoint(-0.35F, -6.5F, -20.9F);
      Mag25.setTextureSize(64, 32);
      Mag25.mirror = true;
      setRotation(Mag25, -0.2094395F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Mag1.render(f5);
    Mag2.render(f5);
    Mag3.render(f5);
    Mag4.render(f5);
    Mag5.render(f5);
    Mag6.render(f5);
    Mag7.render(f5);
    Mag8.render(f5);
    Mag9.render(f5);
    Mag10.render(f5);
    Mag11.render(f5);
    Mag12.render(f5);
    Mag13.render(f5);
    Mag14.render(f5);
    Mag15.render(f5);
    Mag16.render(f5);
    Mag17.render(f5);
    Mag18.render(f5);
    Mag19.render(f5);
    Mag20.render(f5);
    Mag21.render(f5);
    Mag22.render(f5);
    Mag23.render(f5);
    Mag24.render(f5);
    Mag25.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
