// Date: 11/3/2017 10:55:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mwc.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class STG44Mag extends ModelBase
{
  //fields
    
    ModelRenderer mag1;
    ModelRenderer mag2;
    ModelRenderer mag3;
    ModelRenderer mag4;
    ModelRenderer mag5;
    ModelRenderer mag6;
    ModelRenderer mag7;
    ModelRenderer mag8;
    ModelRenderer mag9;
    ModelRenderer mag10;
    ModelRenderer mag11;
    ModelRenderer mag12;
    ModelRenderer mag13;
    ModelRenderer mag14;
    ModelRenderer mag15;
    ModelRenderer mag16;
    ModelRenderer mag17;
    ModelRenderer mag18;
    ModelRenderer mag19;
    ModelRenderer mag20;
    ModelRenderer mag21;
    ModelRenderer mag22;
    ModelRenderer mag23;
    ModelRenderer mag24;
    ModelRenderer mag25;
    ModelRenderer mag26;
    ModelRenderer mag27;
    ModelRenderer mag28;
    ModelRenderer mag29;
  
  public STG44Mag()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      
      mag1 = new ModelRenderer(this, 100, 0);
      mag1.addBox(0F, 0F, 0F, 4, 2, 8);
      mag1.setRotationPoint(-3.5F, -7.5F, -28.8F);
      mag1.setTextureSize(64, 32);
      mag1.mirror = true;
      setRotation(mag1, 0F, 0F, 0F);
      mag2 = new ModelRenderer(this, 100, 0);
      mag2.addBox(0F, 0F, 0F, 4, 12, 8);
      mag2.setRotationPoint(-3.6F, -6.1F, -28.8F);
      mag2.setTextureSize(64, 32);
      mag2.mirror = true;
      setRotation(mag2, -0.0743572F, 0F, 0F);
      mag3 = new ModelRenderer(this, 100, 0);
      mag3.addBox(0F, 0F, 0F, 1, 12, 8);
      mag3.setRotationPoint(-0.4F, -6.1F, -28.8F);
      mag3.setTextureSize(64, 32);
      mag3.mirror = true;
      setRotation(mag3, -0.0743572F, 0F, 0F);
      mag4 = new ModelRenderer(this, 100, 0);
      mag4.addBox(0F, 0F, 0F, 4, 8, 14);
      mag4.setRotationPoint(-3.6F, 6.45F, -21.7F);
      mag4.setTextureSize(64, 32);
      mag4.mirror = true;
      setRotation(mag4, -1.858931F, 0F, 0F);
      mag5 = new ModelRenderer(this, 100, 0);
      mag5.addBox(0F, 0F, 0F, 1, 8, 14);
      mag5.setRotationPoint(-0.4F, 6.45F, -21.7F);
      mag5.setTextureSize(64, 32);
      mag5.mirror = true;
      setRotation(mag5, -1.858931F, 0F, 0F);
      mag6 = new ModelRenderer(this, 100, 0);
      mag6.addBox(0F, 0F, 0F, 3, 8, 14);
      mag6.setRotationPoint(-3F, 6.6F, -20.8F);
      mag6.setTextureSize(64, 32);
      mag6.mirror = true;
      setRotation(mag6, -1.858931F, 0F, 0F);
      mag7 = new ModelRenderer(this, 100, 0);
      mag7.addBox(0F, 0F, 0F, 3, 12, 1);
      mag7.setRotationPoint(-3F, -5.5F, -20.9F);
      mag7.setTextureSize(64, 32);
      mag7.mirror = true;
      setRotation(mag7, -0.0743572F, 0F, 0F);
      mag8 = new ModelRenderer(this, 100, 0);
      mag8.addBox(0F, 0F, 0F, 3, 2, 1);
      mag8.setRotationPoint(-3F, -7.5F, -20.9F);
      mag8.setTextureSize(64, 32);
      mag8.mirror = true;
      setRotation(mag8, 0F, 0F, 0F);
      mag9 = new ModelRenderer(this, 100, 0);
      mag9.addBox(0F, 0F, 0F, 3, 1, 1);
      mag9.setRotationPoint(-3F, -6.4F, -20.9F);
      mag9.setTextureSize(64, 32);
      mag9.mirror = true;
      setRotation(mag9, 0F, 0F, 0F);
      mag10 = new ModelRenderer(this, 100, 0);
      mag10.addBox(0F, 0F, 0F, 1, 1, 2);
      mag10.setRotationPoint(-3.7F, -7.5F, -23.9F);
      mag10.setTextureSize(64, 32);
      mag10.mirror = true;
      setRotation(mag10, 0F, 0F, 0F);
      mag11 = new ModelRenderer(this, 100, 0);
      mag11.addBox(0F, 0F, 0F, 1, 1, 2);
      mag11.setRotationPoint(-3.7F, -7.5F, -27.9F);
      mag11.setTextureSize(64, 32);
      mag11.mirror = true;
      setRotation(mag11, 0F, 0F, 0F);
      mag12 = new ModelRenderer(this, 100, 0);
      mag12.addBox(0F, 0F, 0F, 1, 1, 2);
      mag12.setRotationPoint(-0.3F, -7.5F, -23.9F);
      mag12.setTextureSize(64, 32);
      mag12.mirror = true;
      setRotation(mag12, 0F, 0F, 0F);
      mag13 = new ModelRenderer(this, 100, 0);
      mag13.addBox(0F, 0F, 0F, 1, 1, 2);
      mag13.setRotationPoint(-0.3F, -7.5F, -27.9F);
      mag13.setTextureSize(64, 32);
      mag13.mirror = true;
      setRotation(mag13, 0F, 0F, 0F);
      mag14 = new ModelRenderer(this, 100, 0);
      mag14.addBox(0F, 0F, 0F, 1, 12, 1);
      mag14.setRotationPoint(-3.8F, -6.05F, -28F);
      mag14.setTextureSize(64, 32);
      mag14.mirror = true;
      setRotation(mag14, -0.0743572F, 0F, 0F);
      mag15 = new ModelRenderer(this, 100, 0);
      mag15.addBox(0F, 0F, 0F, 1, 12, 1);
      mag15.setRotationPoint(-0.2F, -6.05F, -28F);
      mag15.setTextureSize(64, 32);
      mag15.mirror = true;
      setRotation(mag15, -0.0743572F, 0F, 0F);
      mag16 = new ModelRenderer(this, 100, 0);
      mag16.addBox(0F, 0F, 0F, 1, 12, 1);
      mag16.setRotationPoint(-0.2F, -5.85F, -26F);
      mag16.setTextureSize(64, 32);
      mag16.mirror = true;
      setRotation(mag16, -0.0743572F, 0F, 0F);
      mag17 = new ModelRenderer(this, 100, 0);
      mag17.addBox(0F, 0F, 0F, 1, 12, 1);
      mag17.setRotationPoint(-3.8F, -5.85F, -26F);
      mag17.setTextureSize(64, 32);
      mag17.mirror = true;
      setRotation(mag17, -0.0743572F, 0F, 0F);
      mag18 = new ModelRenderer(this, 100, 0);
      mag18.addBox(0F, 0F, 0F, 1, 12, 1);
      mag18.setRotationPoint(-3.8F, -5.7F, -24F);
      mag18.setTextureSize(64, 32);
      mag18.mirror = true;
      setRotation(mag18, -0.0743572F, 0F, 0F);
      mag19 = new ModelRenderer(this, 100, 0);
      mag19.addBox(0F, 0F, 0F, 1, 12, 1);
      mag19.setRotationPoint(-0.2F, -5.7F, -24F);
      mag19.setTextureSize(64, 32);
      mag19.mirror = true;
      setRotation(mag19, -0.0743572F, 0F, 0F);
      mag20 = new ModelRenderer(this, 100, 0);
      mag20.addBox(0F, 0F, 0F, 1, 12, 1);
      mag20.setRotationPoint(-0.2F, -5.6F, -22F);
      mag20.setTextureSize(64, 32);
      mag20.mirror = true;
      setRotation(mag20, -0.0743572F, 0F, 0F);
      mag21 = new ModelRenderer(this, 100, 0);
      mag21.addBox(0F, 0F, 0F, 1, 12, 1);
      mag21.setRotationPoint(-3.8F, -5.6F, -22F);
      mag21.setTextureSize(64, 32);
      mag21.mirror = true;
      setRotation(mag21, -0.0743572F, 0F, 0F);
      mag22 = new ModelRenderer(this, 100, 0);
      mag22.addBox(0F, 0F, 0F, 1, 1, 13);
      mag22.setRotationPoint(-3.8F, 6.45F, -21.9F);
      mag22.setTextureSize(64, 32);
      mag22.mirror = true;
      setRotation(mag22, -1.858931F, 0F, 0F);
      mag23 = new ModelRenderer(this, 100, 0);
      mag23.addBox(0F, 0F, 0F, 1, 1, 12);
      mag23.setRotationPoint(-3.8F, 6.3F, -23.9F);
      mag23.setTextureSize(64, 32);
      mag23.mirror = true;
      setRotation(mag23, -1.858931F, 0F, 0F);
      mag24 = new ModelRenderer(this, 100, 0);
      mag24.addBox(0F, 0F, 0F, 1, 1, 12);
      mag24.setRotationPoint(-3.8F, 6.2F, -25.9F);
      mag24.setTextureSize(64, 32);
      mag24.mirror = true;
      setRotation(mag24, -1.858931F, 0F, 0F);
      mag25 = new ModelRenderer(this, 100, 0);
      mag25.addBox(0F, 0F, 0F, 1, 1, 12);
      mag25.setRotationPoint(-3.8F, 6F, -27.9F);
      mag25.setTextureSize(64, 32);
      mag25.mirror = true;
      setRotation(mag25, -1.858931F, 0F, 0F);
      mag26 = new ModelRenderer(this, 100, 0);
      mag26.addBox(0F, 0F, 0F, 1, 1, 12);
      mag26.setRotationPoint(-0.2F, 6F, -27.9F);
      mag26.setTextureSize(64, 32);
      mag26.mirror = true;
      setRotation(mag26, -1.858931F, 0F, 0F);
      mag27 = new ModelRenderer(this, 100, 0);
      mag27.addBox(0F, 0F, 0F, 1, 1, 12);
      mag27.setRotationPoint(-0.2F, 6.2F, -25.9F);
      mag27.setTextureSize(64, 32);
      mag27.mirror = true;
      setRotation(mag27, -1.858931F, 0F, 0F);
      mag28 = new ModelRenderer(this, 100, 0);
      mag28.addBox(0F, 0F, 0F, 1, 1, 12);
      mag28.setRotationPoint(-0.2F, 6.3F, -23.9F);
      mag28.setTextureSize(64, 32);
      mag28.mirror = true;
      setRotation(mag28, -1.858931F, 0F, 0F);
      mag29 = new ModelRenderer(this, 100, 0);
      mag29.addBox(0F, 0F, 0F, 1, 1, 13);
      mag29.setRotationPoint(-0.2F, 6.45F, -21.9F);
      mag29.setTextureSize(64, 32);
      mag29.mirror = true;
      setRotation(mag29, -1.858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    mag1.render(f5);
    mag2.render(f5);
    mag3.render(f5);
    mag4.render(f5);
    mag5.render(f5);
    mag6.render(f5);
    mag7.render(f5);
    mag8.render(f5);
    mag9.render(f5);
    mag10.render(f5);
    mag11.render(f5);
    mag12.render(f5);
    mag13.render(f5);
    mag14.render(f5);
    mag15.render(f5);
    mag16.render(f5);
    mag17.render(f5);
    mag18.render(f5);
    mag19.render(f5);
    mag20.render(f5);
    mag21.render(f5);
    mag22.render(f5);
    mag23.render(f5);
    mag24.render(f5);
    mag25.render(f5);
    mag26.render(f5);
    mag27.render(f5);
    mag28.render(f5);
    mag29.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
