// Date: 3/11/2019 5:24:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class EnergyCase extends ModelBase
{
  //fields
    ModelRenderer case1;
    ModelRenderer case2;
    ModelRenderer case3;
    ModelRenderer case4;
    ModelRenderer case5;
  
  public EnergyCase()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      case1 = new ModelRenderer(this, 0, 0);
      case1.addBox(0F, 0F, 0F, 2, 8, 3);
      case1.setRotationPoint(0.5F, 0F, 0F);
      case1.setTextureSize(128, 128);
      case1.mirror = true;
      setRotation(case1, 0F, 0F, 0F);
      case2 = new ModelRenderer(this, 0, 0);
      case2.addBox(0F, 0F, 0F, 1, 4, 3);
      case2.setRotationPoint(1.6F, 4F, 0.1F);
      case2.setTextureSize(128, 128);
      case2.mirror = true;
      setRotation(case2, 0F, 0F, 0F);
      case3 = new ModelRenderer(this, 0, 0);
      case3.addBox(0F, 0F, 0F, 1, 8, 1);
      case3.setRotationPoint(1F, 0F, -0.1F);
      case3.setTextureSize(128, 128);
      case3.mirror = true;
      setRotation(case3, 0F, 0F, 0F);
      case4 = new ModelRenderer(this, 0, 0);
      case4.addBox(0F, 0F, 0F, 1, 4, 3);
      case4.setRotationPoint(0.4F, 4F, 0.1F);
      case4.setTextureSize(128, 128);
      case4.mirror = true;
      setRotation(case4, 0F, 0F, 0F);
      case5 = new ModelRenderer(this, 0, 0);
      case5.addBox(0F, 0F, 0F, 1, 6, 3);
      case5.setRotationPoint(1F, -0.3F, 0.1F);
      case5.setTextureSize(128, 128);
      case5.mirror = true;
      setRotation(case5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    case1.render(f5);
    case2.render(f5);
    case3.render(f5);
    case4.render(f5);
    case5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
