// Date: 11/13/2015 10:12:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Holo extends ModelBase
{
  //fields
    ModelRenderer sight1;
    ModelRenderer sight2;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight6;
    ModelRenderer sight7;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight12;
    ModelRenderer sight13;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
  
  public Holo()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      sight1 = new ModelRenderer(this, 0, 0);
      sight1.addBox(0F, 0F, 0F, 9, 1, 8);
      sight1.setRotationPoint(-5F, -13F, 0F);
      sight1.setTextureSize(256, 128);
      sight1.mirror = true;
      setRotation(sight1, 0F, 0F, 0F);
      sight2 = new ModelRenderer(this, 0, 0);
      sight2.addBox(0F, 0F, 0F, 8, 1, 8);
      sight2.setRotationPoint(4F, -13F, 0F);
      sight2.setTextureSize(256, 128);
      sight2.mirror = true;
      setRotation(sight2, 0F, 0F, 1.301251F);
      sight3 = new ModelRenderer(this, 0, 0);
      sight3.addBox(0F, 0F, 0F, 1, 8, 8);
      sight3.setRotationPoint(-5F, -13F, 0F);
      sight3.setTextureSize(256, 128);
      sight3.mirror = true;
      setRotation(sight3, 0F, 0F, 0.2602503F);
      sight4 = new ModelRenderer(this, 0, 30);
      sight4.addBox(0F, 0F, 0F, 9, 1, 4);
      sight4.setRotationPoint(-5F, -12F, 2F);
      sight4.setTextureSize(256, 128);
      sight4.mirror = true;
      setRotation(sight4, 0F, 0F, 0F);
      sight5 = new ModelRenderer(this, 0, 30);
      sight5.addBox(0F, 0F, 0F, 1, 8, 4);
      sight5.setRotationPoint(-4F, -13F, 2F);
      sight5.setTextureSize(256, 128);
      sight5.mirror = true;
      setRotation(sight5, 0F, 0F, 0.2602503F);
      sight6 = new ModelRenderer(this, 0, 0);
      sight6.addBox(0F, 0F, 0F, 8, 1, 4);
      sight6.setRotationPoint(3F, -13F, 2F);
      sight6.setTextureSize(256, 128);
      sight6.mirror = true;
      setRotation(sight6, 0F, 0F, 1.301251F);
      sight7 = new ModelRenderer(this, 0, 0);
      sight7.addBox(0F, 0F, 0F, 4, 1, 8);
      sight7.setRotationPoint(6.2F, -5.3F, 0F);
      sight7.setTextureSize(256, 128);
      sight7.mirror = true;
      setRotation(sight7, 0F, 0F, 2.41661F);
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 1, 4, 8);
      sight8.setRotationPoint(-7.05F, -5.25F, 0F);
      sight8.setTextureSize(256, 128);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, -0.8179294F);
      sight9 = new ModelRenderer(this, 0, 30);
      sight9.addBox(0F, 0F, 0F, 3, 1, 4);
      sight9.setRotationPoint(5.2F, -5.3F, 2F);
      sight9.setTextureSize(256, 128);
      sight9.mirror = true;
      setRotation(sight9, 0F, 0F, 2.41661F);
      sight10 = new ModelRenderer(this, 0, 30);
      sight10.addBox(0F, 0F, 0F, 1, 3, 4);
      sight10.setRotationPoint(-6.05F, -5.25F, 2F);
      sight10.setTextureSize(256, 128);
      sight10.mirror = true;
      setRotation(sight10, 0F, 0F, -0.8179294F);
      sight11 = new ModelRenderer(this, 0, 0);
      sight11.addBox(0F, 0F, 0F, 7, 2, 14);
      sight11.setRotationPoint(-4F, -4F, -3F);
      sight11.setTextureSize(256, 128);
      sight11.mirror = true;
      setRotation(sight11, 0F, 0F, 0F);
      sight12 = new ModelRenderer(this, 0, 30);
      sight12.addBox(0F, 0F, 0F, 3, 1, 10);
      sight12.setRotationPoint(-2F, -5F, 0F);
      sight12.setTextureSize(256, 128);
      sight12.mirror = true;
      setRotation(sight12, 0F, 0F, 0F);
      sight13 = new ModelRenderer(this, 0, 0);
      sight13.addBox(0F, 0F, 0F, 7, 2, 15);
      sight13.setRotationPoint(-4F, -2F, -17F);
      sight13.setTextureSize(256, 128);
      sight13.mirror = true;
      setRotation(sight13, 0F, 0F, 0F);
      sight14 = new ModelRenderer(this, 0, 0);
      sight14.addBox(0F, 0F, 0F, 5, 3, 23);
      sight14.setRotationPoint(-3F, 0F, -13F);
      sight14.setTextureSize(256, 128);
      sight14.mirror = true;
      setRotation(sight14, 0F, 0F, 0F);
      sight15 = new ModelRenderer(this, 0, 0);
      sight15.addBox(0F, 0F, 0F, 4, 2, 13);
      sight15.setRotationPoint(-2.5F, -2F, -2.5F);
      sight15.setTextureSize(256, 128);
      sight15.mirror = true;
      setRotation(sight15, 0F, 0F, 0F);
      sight16 = new ModelRenderer(this, 0, 0);
      sight16.addBox(0F, 0F, 0F, 5, 2, 14);
      sight16.setRotationPoint(-3F, -4F, -17F);
      sight16.setTextureSize(256, 128);
      sight16.mirror = true;
      setRotation(sight16, 0F, 0F, 0F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 1, 2, 14);
      sight17.setRotationPoint(-3F, -4F, -17F);
      sight17.setTextureSize(256, 128);
      sight17.mirror = true;
      setRotation(sight17, 0F, 0F, 0.4461433F);
      sight18 = new ModelRenderer(this, 0, 0);
      sight18.addBox(0F, 0F, 0F, 2, 1, 14);
      sight18.setRotationPoint(2F, -4F, -17F);
      sight18.setTextureSize(256, 128);
      sight18.mirror = true;
      setRotation(sight18, 0F, 0F, 1.152537F);
      sight19 = new ModelRenderer(this, 0, 30);
      sight19.addBox(0F, 0F, 0F, 3, 1, 8);
      sight19.setRotationPoint(-2F, -4.5F, -16F);
      sight19.setTextureSize(256, 128);
      sight19.mirror = true;
      setRotation(sight19, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight1.render(f5);
    sight2.render(f5);
    sight3.render(f5);
    sight4.render(f5);
    sight5.render(f5);
    sight6.render(f5);
    sight7.render(f5);
    sight8.render(f5);
    sight9.render(f5);
    sight10.render(f5);
    sight11.render(f5);
    sight12.render(f5);
    sight13.render(f5);
    sight14.render(f5);
    sight15.render(f5);
    sight16.render(f5);
    sight17.render(f5);
    sight18.render(f5);
    sight19.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
