// Date: 6/22/2019 8:41:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class JunoGrip extends ModelBase
{
  //fields
    ModelRenderer grip1;
    ModelRenderer grip2;
    ModelRenderer grip3;
    ModelRenderer grip4;
    ModelRenderer grip5;
    ModelRenderer grip6;
    ModelRenderer grip7;
    ModelRenderer grip8;
    ModelRenderer grip9;
    ModelRenderer grip10;
    ModelRenderer grip11;
    ModelRenderer grip12;
    ModelRenderer grip13;
    ModelRenderer grip14;
    ModelRenderer grip15;
    ModelRenderer grip16;
    ModelRenderer grip17;
    ModelRenderer grip18;
    ModelRenderer grip19;
    ModelRenderer grip20;
    ModelRenderer grip21;
    ModelRenderer grip23;
    ModelRenderer grip24;
    ModelRenderer grip25;
    ModelRenderer grip26;
    ModelRenderer grip27;
    ModelRenderer grip28;
    ModelRenderer grip29;
    ModelRenderer grip30;
    ModelRenderer grip31;
    ModelRenderer grip32;
    ModelRenderer grip33;
    ModelRenderer grip34;
    ModelRenderer grip35;
  
  public JunoGrip()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      grip1 = new ModelRenderer(this, 0, 0);
      grip1.addBox(0F, 0F, 0F, 4, 4, 3);
      grip1.setRotationPoint(0F, 0F, 0F);
      grip1.setTextureSize(128, 128);
      grip1.mirror = true;
      setRotation(grip1, 0F, 0F, 0F);
      grip2 = new ModelRenderer(this, 0, 0);
      grip2.addBox(0F, 0F, 0F, 4, 2, 24);
      grip2.setRotationPoint(0F, -2F, -7F);
      grip2.setTextureSize(128, 128);
      grip2.mirror = true;
      setRotation(grip2, 0F, 0F, 0F);
      grip3 = new ModelRenderer(this, 0, 0);
      grip3.addBox(0F, 0F, 0F, 4, 4, 4);
      grip3.setRotationPoint(0F, 4F, -1F);
      grip3.setTextureSize(128, 128);
      grip3.mirror = true;
      setRotation(grip3, 0.2974289F, 0F, 0F);
      grip4 = new ModelRenderer(this, 0, 0);
      grip4.addBox(0F, 0F, 0F, 4, 6, 4);
      grip4.setRotationPoint(0F, 7.8F, 0.2F);
      grip4.setTextureSize(128, 128);
      grip4.mirror = true;
      setRotation(grip4, 0.7063936F, 0F, 0F);
      grip5 = new ModelRenderer(this, 0, 0);
      grip5.addBox(0F, 0F, 0F, 4, 2, 4);
      grip5.setRotationPoint(0F, 12.4F, 4.1F);
      grip5.setTextureSize(128, 128);
      grip5.mirror = true;
      setRotation(grip5, 1.226894F, 0F, 0F);
      grip6 = new ModelRenderer(this, 0, 0);
      grip6.addBox(0F, 0F, 0F, 4, 2, 2);
      grip6.setRotationPoint(0F, 4F, -1F);
      grip6.setTextureSize(128, 128);
      grip6.mirror = true;
      setRotation(grip6, 1.003822F, 0F, 0F);
      grip7 = new ModelRenderer(this, 0, 0);
      grip7.addBox(0F, 0F, 0F, 4, 3, 2);
      grip7.setRotationPoint(0F, 0F, -2F);
      grip7.setTextureSize(128, 128);
      grip7.mirror = true;
      setRotation(grip7, 1.003822F, 0F, 0F);
      grip8 = new ModelRenderer(this, 0, 0);
      grip8.addBox(0F, 0F, 0F, 4, 2, 1);
      grip8.setRotationPoint(0F, 0F, -7F);
      grip8.setTextureSize(128, 128);
      grip8.mirror = true;
      setRotation(grip8, 0F, 0F, 0F);
      grip9 = new ModelRenderer(this, 0, 0);
      grip9.addBox(0F, 0F, 0F, 4, 4, 1);
      grip9.setRotationPoint(0F, 2F, -6F);
      grip9.setTextureSize(128, 128);
      grip9.mirror = true;
      setRotation(grip9, 2.267895F, 0F, 0F);
      grip10 = new ModelRenderer(this, 0, 0);
      grip10.addBox(0F, 0F, 0F, 4, 2, 1);
      grip10.setRotationPoint(0F, 1F, -6F);
      grip10.setTextureSize(128, 128);
      grip10.mirror = true;
      setRotation(grip10, 2.267895F, 0F, 0F);
      grip11 = new ModelRenderer(this, 0, 0);
      grip11.addBox(0F, 0F, 0F, 4, 1, 6);
      grip11.setRotationPoint(0F, -3F, -7F);
      grip11.setTextureSize(128, 128);
      grip11.mirror = true;
      setRotation(grip11, 0F, 0F, 0F);
      grip12 = new ModelRenderer(this, 0, 0);
      grip12.addBox(0F, 0F, 0F, 4, 1, 10);
      grip12.setRotationPoint(0F, -3F, 6F);
      grip12.setTextureSize(128, 128);
      grip12.mirror = true;
      setRotation(grip12, 0F, 0F, 0F);
      grip13 = new ModelRenderer(this, 0, 0);
      grip13.addBox(0F, 0F, 0F, 3, 1, 7);
      grip13.setRotationPoint(0.5F, -3F, -1F);
      grip13.setTextureSize(128, 128);
      grip13.mirror = true;
      setRotation(grip13, 0F, 0F, 0F);
      grip14 = new ModelRenderer(this, 0, 0);
      grip14.addBox(0F, 0F, 0F, 3, 3, 4);
      grip14.setRotationPoint(0.5F, 8.3F, 6.1F);
      grip14.setTextureSize(128, 128);
      grip14.mirror = true;
      setRotation(grip14, 0F, 0F, 0F);
      grip15 = new ModelRenderer(this, 0, 0);
      grip15.addBox(0F, 0F, 0F, 3, 10, 3);
      grip15.setRotationPoint(0.5F, 11.3F, 10.1F);
      grip15.setTextureSize(128, 128);
      grip15.mirror = true;
      setRotation(grip15, 2.379431F, 0F, 0F);
      grip16 = new ModelRenderer(this, 0, 0);
      grip16.addBox(0F, 0F, 0F, 3, 5, 3);
      grip16.setRotationPoint(0.5F, -0.7F, 14F);
      grip16.setTextureSize(128, 128);
      grip16.mirror = true;
      setRotation(grip16, 0F, 0F, 0F);
      grip17 = new ModelRenderer(this, 0, 0);
      grip17.addBox(0F, -1F, 0F, 2, 11, 1);
      grip17.setRotationPoint(1F, 12.3F, 10.1F);
      grip17.setTextureSize(128, 128);
      grip17.mirror = true;
      setRotation(grip17, 2.379431F, 0F, 0F);
      grip18 = new ModelRenderer(this, 0, 0);
      grip18.addBox(0F, 0F, 0F, 2, 2, 4);
      grip18.setRotationPoint(1F, 9.7F, 6.1F);
      grip18.setTextureSize(128, 128);
      grip18.mirror = true;
      setRotation(grip18, 0F, 0F, 0F);
      grip19 = new ModelRenderer(this, 0, 0);
      grip19.addBox(0F, 0F, 0F, 2, 1, 2);
      grip19.setRotationPoint(1F, 4.3F, 15F);
      grip19.setTextureSize(128, 128);
      grip19.mirror = true;
      setRotation(grip19, 0F, 0F, 0F);
      grip20 = new ModelRenderer(this, 0, 0);
      grip20.addBox(0F, 0F, 0F, 2, 3, 1);
      grip20.setRotationPoint(1F, 13.1F, 6F);
      grip20.setTextureSize(128, 128);
      grip20.mirror = true;
      setRotation(grip20, 1.59868F, 0F, 0F);
      grip21 = new ModelRenderer(this, 0, 0);
      grip21.addBox(0F, 2.4F, 0F, 2, 1, 1);
      grip21.setRotationPoint(1F, 13.1F, 6F);
      grip21.setTextureSize(128, 128);
      grip21.mirror = true;
      setRotation(grip21, 1.59868F, 0F, 0F);
      grip23 = new ModelRenderer(this, 0, 0);
      grip23.addBox(0F, 0F, 0F, 1, 3, 3);
      grip23.setRotationPoint(0F, 0F, 14F);
      grip23.setTextureSize(128, 128);
      grip23.mirror = true;
      setRotation(grip23, 0F, 0F, -0.4833219F);
      grip24 = new ModelRenderer(this, 0, 0);
      grip24.addBox(-1F, 0F, 0F, 1, 3, 3);
      grip24.setRotationPoint(4F, 0F, 14F);
      grip24.setTextureSize(128, 128);
      grip24.mirror = true;
      setRotation(grip24, 0F, 0F, 0.4833166F);
      grip25 = new ModelRenderer(this, 0, 0);
      grip25.addBox(0F, 0F, 0F, 4, 2, 2);
      grip25.setRotationPoint(0F, 0F, 1.5F);
      grip25.setTextureSize(128, 128);
      grip25.mirror = true;
      setRotation(grip25, 0.7853982F, 0F, 0F);
      grip26 = new ModelRenderer(this, 0, 0);
      grip26.addBox(0F, 0F, 0F, 3, 6, 1);
      grip26.setRotationPoint(0.5F, -0.5F, -0.5F);
      grip26.setTextureSize(128, 128);
      grip26.mirror = true;
      setRotation(grip26, 0F, 0F, 0F);
      grip27 = new ModelRenderer(this, 0, 0);
      grip27.addBox(0F, 0F, 0F, 5, 2, 2);
      grip27.setRotationPoint(-0.5F, -1.3F, -6.5F);
      grip27.setTextureSize(128, 128);
      grip27.mirror = true;
      setRotation(grip27, 0.4833219F, 0F, 0F);
      grip28 = new ModelRenderer(this, 0, 0);
      grip28.addBox(0F, 0F, 0F, 4, 1, 2);
      grip28.setRotationPoint(0F, -3F, -1F);
      grip28.setTextureSize(128, 128);
      grip28.mirror = true;
      setRotation(grip28, -0.7853982F, 0F, 0F);
      grip29 = new ModelRenderer(this, 0, 0);
      grip29.addBox(0F, 0F, -2F, 4, 1, 2);
      grip29.setRotationPoint(0F, -3F, 6F);
      grip29.setTextureSize(128, 128);
      grip29.mirror = true;
      setRotation(grip29, 0.7853982F, 0F, 0F);
      grip30 = new ModelRenderer(this, 0, 0);
      grip30.addBox(0F, 0F, 0F, 4, 1, 1);
      grip30.setRotationPoint(0F, -2.5F, 16F);
      grip30.setTextureSize(128, 128);
      grip30.mirror = true;
      setRotation(grip30, -0.7853982F, 0F, 0F);
      grip31 = new ModelRenderer(this, 0, 0);
      grip31.addBox(0F, 0F, 0F, 3, 2, 2);
      grip31.setRotationPoint(0.5F, 0F, 12.7F);
      grip31.setTextureSize(128, 128);
      grip31.mirror = true;
      setRotation(grip31, 0.7853982F, 0F, 0F);
      grip32 = new ModelRenderer(this, 0, 0);
      grip32.addBox(0F, 0F, 0F, 3, 6, 1);
      grip32.setRotationPoint(0.5F, -0.5F, 3F);
      grip32.setTextureSize(128, 128);
      grip32.mirror = true;
      setRotation(grip32, 0F, 0F, 0F);
      grip33 = new ModelRenderer(this, 0, 0);
      grip33.addBox(0F, 0F, 4F, 3, 4, 1);
      grip33.setRotationPoint(0.5F, 4F, -1F);
      grip33.setTextureSize(128, 128);
      grip33.mirror = true;
      setRotation(grip33, 0.2974289F, 0F, 0F);
      grip34 = new ModelRenderer(this, 0, 0);
      grip34.addBox(0F, 0F, 4F, 3, 5, 1);
      grip34.setRotationPoint(0.5F, 7.8F, 0.2F);
      grip34.setTextureSize(128, 128);
      grip34.mirror = true;
      setRotation(grip34, 0.7063936F, 0F, 0F);
      grip35 = new ModelRenderer(this, 0, 0);
      grip35.addBox(0F, 0F, 4F, 3, 2, 1);
      grip35.setRotationPoint(0.5F, 12.4F, 4.1F);
      grip35.setTextureSize(128, 128);
      grip35.mirror = true;
      setRotation(grip35, 1.226894F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    grip1.render(f5);
    grip2.render(f5);
    grip3.render(f5);
    grip4.render(f5);
    grip5.render(f5);
    grip6.render(f5);
    grip7.render(f5);
    grip8.render(f5);
    grip9.render(f5);
    grip10.render(f5);
    grip11.render(f5);
    grip12.render(f5);
    grip13.render(f5);
    grip14.render(f5);
    grip15.render(f5);
    grip16.render(f5);
    grip17.render(f5);
    grip18.render(f5);
    grip19.render(f5);
    grip20.render(f5);
    grip21.render(f5);
    grip23.render(f5);
    grip24.render(f5);
    grip25.render(f5);
    grip26.render(f5);
    grip27.render(f5);
    grip28.render(f5);
    grip29.render(f5);
    grip30.render(f5);
    grip31.render(f5);
    grip32.render(f5);
    grip33.render(f5);
    grip34.render(f5);
    grip35.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
