// Date: 10/8/2018 4:45:52 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Laser2 extends ModelBase
{
  //fields
    ModelRenderer laser1;
    ModelRenderer laser2;
    ModelRenderer laser3;
    ModelRenderer laser5;
    ModelRenderer laser6;
    ModelRenderer laser7;
    ModelRenderer laser8;
    ModelRenderer laser9;
    ModelRenderer laser10;
    ModelRenderer laser11;
    ModelRenderer laser12;
    ModelRenderer laser13;
    ModelRenderer laser14;
    ModelRenderer laser15;
    ModelRenderer laser16;
    ModelRenderer laser17;
    ModelRenderer laser18;
    ModelRenderer laser19;
    ModelRenderer laser20;
    ModelRenderer laser21;
    ModelRenderer laser22;
    ModelRenderer laser23;
    ModelRenderer laser24;
    ModelRenderer laser25;
    ModelRenderer laser26;
    ModelRenderer laser27;
    ModelRenderer laser28;
    ModelRenderer laser29;
    ModelRenderer laser30;
  
  public Laser2()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      laser1 = new ModelRenderer(this, 0, 0);
      laser1.addBox(0F, 0F, 0F, 3, 4, 10);
      laser1.setRotationPoint(2F, -1F, 0F);
      laser1.setTextureSize(64, 32);
      laser1.mirror = true;
      setRotation(laser1, 0F, 0F, 0F);
      laser2 = new ModelRenderer(this, 100, 0);
      laser2.addBox(0F, 0F, 0F, 2, 4, 4);
      laser2.setRotationPoint(0F, -0.5F, 4F);
      laser2.setTextureSize(64, 32);
      laser2.mirror = true;
      setRotation(laser2, 0F, 0F, 0F);
      laser3 = new ModelRenderer(this, 0, 0);
      laser3.addBox(0F, 0F, 0F, 2, 6, 10);
      laser3.setRotationPoint(2.5F, -1.5F, 0F);
      laser3.setTextureSize(64, 32);
      laser3.mirror = true;
      setRotation(laser3, 0F, 0F, 0F);
      laser5 = new ModelRenderer(this, 0, 0);
      laser5.addBox(0F, 0F, 0F, 1, 1, 2);
      laser5.setRotationPoint(4F, -1.5F, 3F);
      laser5.setTextureSize(64, 32);
      laser5.mirror = true;
      setRotation(laser5, 0F, 0F, 0F);
      laser6 = new ModelRenderer(this, 100, 0);
      laser6.addBox(0F, 0F, 0F, 1, 2, 2);
      laser6.setRotationPoint(4.3F, 1.5F, 7.5F);
      laser6.setTextureSize(64, 32);
      laser6.mirror = true;
      setRotation(laser6, 0F, 0F, 0F);
      laser7 = new ModelRenderer(this, 100, 0);
      laser7.addBox(0F, 0F, 0F, 1, 2, 2);
      laser7.setRotationPoint(4.4F, -0.1F, 4.5F);
      laser7.setTextureSize(64, 32);
      laser7.mirror = true;
      setRotation(laser7, 0F, 0F, 0F);
      laser8 = new ModelRenderer(this, 100, 0);
      laser8.addBox(0F, 0F, 0F, 2, 2, 12);
      laser8.setRotationPoint(2.5F, -1F, -1.5F);
      laser8.setTextureSize(64, 32);
      laser8.mirror = true;
      setRotation(laser8, 0F, 0F, 0F);
      laser9 = new ModelRenderer(this, 100, 0);
      laser9.addBox(0F, 0F, 0F, 1, 1, 12);
      laser9.setRotationPoint(3F, 0.3F, -1.5F);
      laser9.setTextureSize(64, 32);
      laser9.mirror = true;
      setRotation(laser9, 0F, 0F, 0F);
      laser10 = new ModelRenderer(this, 100, 0);
      laser10.addBox(0F, 0F, 0F, 1, 1, 12);
      laser10.setRotationPoint(3F, -1.3F, -1.5F);
      laser10.setTextureSize(64, 32);
      laser10.mirror = true;
      setRotation(laser10, 0F, 0F, 0F);
      laser11 = new ModelRenderer(this, 100, 0);
      laser11.addBox(0F, 0F, 0F, 1, 1, 12);
      laser11.setRotationPoint(2.2F, -0.5F, -1.5F);
      laser11.setTextureSize(64, 32);
      laser11.mirror = true;
      setRotation(laser11, 0F, 0F, 0F);
      laser12 = new ModelRenderer(this, 100, 0);
      laser12.addBox(0F, 0F, 0F, 1, 1, 12);
      laser12.setRotationPoint(3.8F, -0.5F, -1.5F);
      laser12.setTextureSize(64, 32);
      laser12.mirror = true;
      setRotation(laser12, 0F, 0F, 0F);
      laser13 = new ModelRenderer(this, 100, 0);
      laser13.addBox(0F, 0F, 0F, 2, 1, 1);
      laser13.setRotationPoint(4.5F, 2.5F, -1F);
      laser13.setTextureSize(64, 32);
      laser13.mirror = true;
      setRotation(laser13, 0F, 0F, 2.528146F);
      laser14 = new ModelRenderer(this, 0, 0);
      laser14.addBox(0F, 0F, 0F, 1, 3, 2);
      laser14.setRotationPoint(4.05F, -0.2F, 0.5F);
      laser14.setTextureSize(64, 32);
      laser14.mirror = true;
      setRotation(laser14, 0F, 0F, 0F);
      laser15 = new ModelRenderer(this, 100, 0);
      laser15.addBox(0F, 0F, 0F, 1, 1, 1);
      laser15.setRotationPoint(4.1F, -1.4F, 3.5F);
      laser15.setTextureSize(64, 32);
      laser15.mirror = true;
      setRotation(laser15, 0F, 0F, 0F);
      laser16 = new ModelRenderer(this, 100, 0);
      laser16.addBox(0F, 0F, 0F, 1, 1, 1);
      laser16.setRotationPoint(4.1F, 3F, 3.5F);
      laser16.setTextureSize(64, 32);
      laser16.mirror = true;
      setRotation(laser16, 0F, 0F, 0F);
      laser17 = new ModelRenderer(this, 0, 0);
      laser17.addBox(0F, 0F, 0F, 1, 1, 1);
      laser17.setRotationPoint(3F, 3.6F, 3.5F);
      laser17.setTextureSize(64, 32);
      laser17.mirror = true;
      setRotation(laser17, 0F, 0F, 0F);
      laser18 = new ModelRenderer(this, 0, 0);
      laser18.addBox(0F, 0F, 0F, 1, 3, 1);
      laser18.setRotationPoint(4F, 1.4F, 9.2F);
      laser18.setTextureSize(64, 32);
      laser18.mirror = true;
      setRotation(laser18, 0F, 0F, 0F);
      laser19 = new ModelRenderer(this, 0, 0);
      laser19.addBox(0F, 0F, 0F, 1, 2, 6);
      laser19.setRotationPoint(4F, 2.4F, 3.2F);
      laser19.setTextureSize(64, 32);
      laser19.mirror = true;
      setRotation(laser19, 0F, 0F, 0F);
      laser20 = new ModelRenderer(this, 0, 0);
      laser20.addBox(0F, 0F, 0F, 1, 3, 1);
      laser20.setRotationPoint(4.05F, -0.2F, 2F);
      laser20.setTextureSize(64, 32);
      laser20.mirror = true;
      setRotation(laser20, 0F, 0F, 0F);
      laser21 = new ModelRenderer(this, 0, 0);
      laser21.addBox(0F, 0F, 0F, 1, 1, 1);
      laser21.setRotationPoint(3F, -1.6F, 3.5F);
      laser21.setTextureSize(64, 32);
      laser21.mirror = true;
      setRotation(laser21, 0F, 0F, 0F);
      laser22 = new ModelRenderer(this, 0, 0);
      laser22.addBox(0F, 0F, 0F, 1, 1, 2);
      laser22.setRotationPoint(4F, 4.4F, 3.2F);
      laser22.setTextureSize(64, 32);
      laser22.mirror = true;
      setRotation(laser22, 2.305074F, 0F, 0F);
      laser23 = new ModelRenderer(this, 0, 0);
      laser23.addBox(0F, 0F, 0F, 1, 1, 3);
      laser23.setRotationPoint(5F, 3F, 0.2F);
      laser23.setTextureSize(64, 32);
      laser23.mirror = true;
      setRotation(laser23, 0F, 0F, 1.896109F);
      laser24 = new ModelRenderer(this, 0, 0);
      laser24.addBox(0.5F, 0F, 0F, 1, 1, 3);
      laser24.setRotationPoint(5F, 3F, 0.2F);
      laser24.setTextureSize(64, 32);
      laser24.mirror = true;
      setRotation(laser24, 0F, 0F, 1.896109F);
      laser25 = new ModelRenderer(this, 0, 0);
      laser25.addBox(0F, -0.2F, 0F, 1, 1, 1);
      laser25.setRotationPoint(5F, 3F, 0.8F);
      laser25.setTextureSize(64, 32);
      laser25.mirror = true;
      setRotation(laser25, 0F, 0F, 1.896109F);
      laser26 = new ModelRenderer(this, 0, 0);
      laser26.addBox(0.7F, -0.2F, 0F, 1, 1, 1);
      laser26.setRotationPoint(5F, 3F, 0.8F);
      laser26.setTextureSize(64, 32);
      laser26.mirror = true;
      setRotation(laser26, 0F, 0F, 1.896109F);
      laser27 = new ModelRenderer(this, 0, 0);
      laser27.addBox(0F, 0F, 0F, 1, 1, 1);
      laser27.setRotationPoint(3.4F, 3.8F, 0.5F);
      laser27.setTextureSize(64, 32);
      laser27.mirror = true;
      setRotation(laser27, 0F, 0F, 0F);
      laser28 = new ModelRenderer(this, 0, 0);
      laser28.addBox(0F, 0F, 0F, 1, 1, 1);
      laser28.setRotationPoint(3.4F, 3.8F, 1F);
      laser28.setTextureSize(64, 32);
      laser28.mirror = true;
      setRotation(laser28, 0.0174533F, 0F, 0F);
      laser29 = new ModelRenderer(this, 0, 0);
      laser29.addBox(0F, 0F, 0F, 1, 1, 1);
      laser29.setRotationPoint(2.9F, 3.8F, 0.5F);
      laser29.setTextureSize(64, 32);
      laser29.mirror = true;
      setRotation(laser29, 0F, 0F, 0F);
      laser30 = new ModelRenderer(this, 0, 0);
      laser30.addBox(0F, 0F, 0F, 1, 1, 1);
      laser30.setRotationPoint(2.9F, 3.8F, 1F);
      laser30.setTextureSize(64, 32);
      laser30.mirror = true;
      setRotation(laser30, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    laser1.render(f5);
    laser2.render(f5);
    laser3.render(f5);
    laser5.render(f5);
    laser6.render(f5);
    laser7.render(f5);
    laser8.render(f5);
    laser9.render(f5);
    laser10.render(f5);
    laser11.render(f5);
    laser12.render(f5);
    laser13.render(f5);
    laser14.render(f5);
    laser15.render(f5);
    laser16.render(f5);
    laser17.render(f5);
    laser18.render(f5);
    laser19.render(f5);
    laser20.render(f5);
    laser21.render(f5);
    laser22.render(f5);
    laser23.render(f5);
    laser24.render(f5);
    laser25.render(f5);
    laser26.render(f5);
    laser27.render(f5);
    laser28.render(f5);
    laser29.render(f5);
    laser30.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
}
