// Date: 4/8/2017 12:56:49 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import com.paneedah.weaponlib.ModelWithAttachments;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class M1CarbineAction extends ModelWithAttachments
{
  //fields
    ModelRenderer action81;
    ModelRenderer action90;
    ModelRenderer action91;
    ModelRenderer action92;
    ModelRenderer action93;
    ModelRenderer action94;
    ModelRenderer action149;
    ModelRenderer action200;
    ModelRenderer action201;
    ModelRenderer action202;
    ModelRenderer action203;
  
  public M1CarbineAction()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      action81 = new ModelRenderer(this, 150, 0);
      action81.addBox(0F, 0F, 0F, 3, 1, 1);
      action81.setRotationPoint(-5.5F, -12.5F, -21.5F);
      action81.setTextureSize(64, 32);
      action81.mirror = true;
      setRotation(action81, 0F, 0F, 0F);
      action90 = new ModelRenderer(this, 150, 0);
      action90.addBox(0F, 0F, 0F, 2, 1, 8);
      action90.setRotationPoint(-2.5F, -12.8F, -22.5F);
      action90.setTextureSize(64, 32);
      action90.mirror = true;
      setRotation(action90, 0F, 0F, 0F);
      action91 = new ModelRenderer(this, 150, 0);
      action91.addBox(0F, 0F, 0F, 2, 1, 2);
      action91.setRotationPoint(-2.5F, -13F, -23F);
      action91.setTextureSize(64, 32);
      action91.mirror = true;
      setRotation(action91, 0F, 0F, 0F);
      action92 = new ModelRenderer(this, 150, 0);
      action92.addBox(0F, 0F, 0F, 1, 1, 2);
      action92.setRotationPoint(-2.5F, -13F, -23F);
      action92.setTextureSize(64, 32);
      action92.mirror = true;
      setRotation(action92, 0F, 0F, 0.5948578F);
      action93 = new ModelRenderer(this, 150, 0);
      action93.addBox(0F, 0F, 0F, 1, 1, 2);
      action93.setRotationPoint(-2F, -13.2F, -23F);
      action93.setTextureSize(64, 32);
      action93.mirror = true;
      setRotation(action93, 0F, 0F, 0F);
      action94 = new ModelRenderer(this, 150, 0);
      action94.addBox(0F, 0F, 0F, 1, 1, 8);
      action94.setRotationPoint(-2F, -13F, -22.5F);
      action94.setTextureSize(64, 32);
      action94.mirror = true;
      setRotation(action94, 0F, 0F, 0F);
      action149 = new ModelRenderer(this, 150, 0);
      action149.addBox(0F, 0F, 0F, 3, 1, 1);
      action149.setRotationPoint(-5.5F, -13F, -21.5F);
      action149.setTextureSize(64, 32);
      action149.mirror = true;
      setRotation(action149, 0F, 0F, 0F);
      action200 = new ModelRenderer(this, 150, 0);
      action200.addBox(0F, 0F, 0F, 1, 1, 1);
      action200.setRotationPoint(-3.5F, -13F, -22F);
      action200.setTextureSize(64, 32);
      action200.mirror = true;
      setRotation(action200, 0F, 0F, 0F);
      action201 = new ModelRenderer(this, 150, 0);
      action201.addBox(0F, 0F, 0F, 1, 1, 1);
      action201.setRotationPoint(-3.5F, -12.5F, -22F);
      action201.setTextureSize(64, 32);
      action201.mirror = true;
      setRotation(action201, 0F, 0F, 0F);
      action202 = new ModelRenderer(this, 150, 0);
      action202.addBox(0F, 0F, 0F, 1, 1, 1);
      action202.setRotationPoint(-3.5F, -12.5F, -22F);
      action202.setTextureSize(64, 32);
      action202.mirror = true;
      setRotation(action202, 0F, -1.041001F, 0F);
      action203 = new ModelRenderer(this, 150, 0);
      action203.addBox(0F, 0F, 0F, 1, 1, 1);
      action203.setRotationPoint(-3.5F, -13F, -22F);
      action203.setTextureSize(64, 32);
      action203.mirror = true;
      setRotation(action203, 0F, -1.041001F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    action81.render(f5);
    action90.render(f5);
    action91.render(f5);
    action92.render(f5);
    action93.render(f5);
    action94.render(f5);
    action149.render(f5);
    action200.render(f5);
    action201.render(f5);
    action202.render(f5);
    action203.render(f5);
  }

}
