// Date: 11/9/2018 9:34:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MilitaryCrate extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24Handle;
    ModelRenderer Shape25Handle;
    ModelRenderer Shape26Handle;
    ModelRenderer Shape27Handle;
    ModelRenderer Shape28Handle;
    ModelRenderer Shape29Handle;
  
  public MilitaryCrate()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 25, 1, 50);
      Shape1.setRotationPoint(-12F, 20F, -24F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 23, 12, 48);
      Shape2.setRotationPoint(-11F, 8F, -23F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape3.setRotationPoint(12F, 15.9F, -24F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape4.setRotationPoint(12F, 11.8F, -24F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape5.setRotationPoint(12F, 7.7F, -24F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape6.setRotationPoint(-12F, 15.9F, -24F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape7.setRotationPoint(-12F, 11.8F, -24F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 0);
      Shape8.addBox(0F, 0F, 0F, 1, 4, 50);
      Shape8.setRotationPoint(-12F, 7.7F, -24F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, 0F, 0F, 24, 6, 1);
      Shape9.setRotationPoint(-11.5F, 14F, -24.3F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 0);
      Shape10.addBox(0F, 0F, 0F, 24, 6, 1);
      Shape10.setRotationPoint(-11.5F, 7.8F, -24.3F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 0);
      Shape11.addBox(0F, 0F, 0F, 24, 6, 1);
      Shape11.setRotationPoint(-11.5F, 7.8F, 25.3F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 0);
      Shape12.addBox(0F, 0F, 0F, 24, 6, 1);
      Shape12.setRotationPoint(-11.5F, 14F, 25.3F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 0, 0);
      Shape13.addBox(0F, 0F, 0F, 5, 1, 50);
      Shape13.setRotationPoint(-11F, 7.2F, -24F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 0);
      Shape14.addBox(0F, 0F, 0F, 5, 1, 50);
      Shape14.setRotationPoint(-5.8F, 7.2F, -24F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 0, 0);
      Shape15.addBox(0F, 0F, 0F, 5, 1, 50);
      Shape15.setRotationPoint(-0.6F, 7.2F, -24F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 0);
      Shape16.addBox(0F, 0F, 0F, 5, 1, 50);
      Shape16.setRotationPoint(4.7F, 7.2F, -24F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 0);
      Shape17.addBox(0F, 0F, 0F, 2, 1, 50);
      Shape17.setRotationPoint(9.9F, 7.2F, -24F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 0);
      Shape18.addBox(0F, 0F, 0F, 23, 1, 5);
      Shape18.setRotationPoint(-11F, 6.2F, -19F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 0);
      Shape19.addBox(0F, 0F, 0F, 23, 1, 5);
      Shape19.setRotationPoint(-11F, 6.2F, 16F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 0);
      Shape20.addBox(0F, 0F, 0F, 23, 1, 5);
      Shape20.setRotationPoint(-11F, 21F, -19F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(0F, 0F, 0F, 23, 1, 5);
      Shape21.setRotationPoint(-11F, 21F, 17F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 0, 0);
      Shape22.addBox(0F, 0F, 0F, 7, 2, 2);
      Shape22.setRotationPoint(-3F, 10F, -26F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 0, 0);
      Shape23.addBox(0F, 0F, 0F, 7, 2, 2);
      Shape23.setRotationPoint(-3F, 10F, 26F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24Handle = new ModelRenderer(this, 200, 0);
      Shape24Handle.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape24Handle.setRotationPoint(4F, 10.5F, -25.5F);
      Shape24Handle.setTextureSize(64, 32);
      Shape24Handle.mirror = true;
      setRotation(Shape24Handle, 0F, 0F, 0F);
      Shape25Handle = new ModelRenderer(this, 200, 0);
      Shape25Handle.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape25Handle.setRotationPoint(-4F, 10.5F, -25.5F);
      Shape25Handle.setTextureSize(64, 32);
      Shape25Handle.mirror = true;
      setRotation(Shape25Handle, 0F, 0F, 0F);
      Shape26Handle = new ModelRenderer(this, 200, 0);
      Shape26Handle.addBox(0F, 0F, 0F, 7, 1, 1);
      Shape26Handle.setRotationPoint(-3F, 14F, -25.5F);
      Shape26Handle.setTextureSize(64, 32);
      Shape26Handle.mirror = true;
      setRotation(Shape26Handle, 0F, 0F, 0F);
      Shape27Handle = new ModelRenderer(this, 200, 0);
      Shape27Handle.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape27Handle.setRotationPoint(4F, 10.5F, 26.5F);
      Shape27Handle.setTextureSize(64, 32);
      Shape27Handle.mirror = true;
      setRotation(Shape27Handle, 0F, 0F, 0F);
      Shape28Handle = new ModelRenderer(this, 200, 0);
      Shape28Handle.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape28Handle.setRotationPoint(-4F, 10.5F, 26.5F);
      Shape28Handle.setTextureSize(64, 32);
      Shape28Handle.mirror = true;
      setRotation(Shape28Handle, 0F, 0F, 0F);
      Shape29Handle = new ModelRenderer(this, 200, 0);
      Shape29Handle.addBox(0F, 0F, 0F, 7, 1, 1);
      Shape29Handle.setRotationPoint(-3F, 14F, 26.5F);
      Shape29Handle.setTextureSize(64, 32);
      Shape29Handle.mirror = true;
      setRotation(Shape29Handle, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24Handle.render(f5);
    Shape25Handle.render(f5);
    Shape26Handle.render(f5);
    Shape27Handle.render(f5);
    Shape28Handle.render(f5);
    Shape29Handle.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
