// Date: 1/8/2017 12:45:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MP40Mag extends ModelBase
{
  //fields
    ModelRenderer gun102;
    ModelRenderer gun103;
  
  public MP40Mag()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun102 = new ModelRenderer(this, 0, 0);
      gun102.addBox(0F, 0F, 0F, 2, 20, 4);
      gun102.setRotationPoint(1.2F, -9F, -19.5F);
      gun102.setTextureSize(64, 32);
      gun102.mirror = true;
      setRotation(gun102, 0F, 0F, 0F);
      gun103 = new ModelRenderer(this, 0, 0);
      gun103.addBox(0F, 0F, 0F, 2, 20, 4);
      gun103.setRotationPoint(1.8F, -9F, -19.5F);
      gun103.setTextureSize(64, 32);
      gun103.mirror = true;
      setRotation(gun103, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun102.render(f5);
    gun103.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
