// Date: 9/22/2016 7:13:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import com.paneedah.weaponlib.ModelWithAttachments;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MP5Iron extends ModelWithAttachments
{
  //fields
    ModelRenderer Sight1;
    ModelRenderer Sight2;
    ModelRenderer Sight3;
    ModelRenderer Sight4;
    ModelRenderer Sight5;
    ModelRenderer Sight6;
    ModelRenderer Sight7;
    ModelRenderer Sight8;
    ModelRenderer Sight9;
    ModelRenderer Sight10;
    ModelRenderer Sight11;
    ModelRenderer Sight12;
    ModelRenderer Sight13;
    ModelRenderer Sight14;
    ModelRenderer Sight15;
    ModelRenderer Sight16;
    ModelRenderer Sight17;
    ModelRenderer Sight18;
    ModelRenderer Sight19;
  
  public MP5Iron()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Sight1 = new ModelRenderer(this, 0, 0);
      Sight1.addBox(0F, 0F, 0F, 1, 4, 2);
      Sight1.setRotationPoint(-3F, -3F, 0F);
      Sight1.setTextureSize(64, 32);
      Sight1.mirror = true;
      setRotation(Sight1, 0.2602503F, 0F, 0F);
      Sight2 = new ModelRenderer(this, 0, 0);
      Sight2.addBox(0F, 0F, 0F, 1, 4, 1);
      Sight2.setRotationPoint(-2.5F, -3.5F, 1.8F);
      Sight2.setTextureSize(64, 32);
      Sight2.mirror = true;
      setRotation(Sight2, 0.2602503F, 0F, 0F);
      Sight3 = new ModelRenderer(this, 0, 0);
      Sight3.addBox(0F, 0F, 0F, 1, 4, 1);
      Sight3.setRotationPoint(-2.5F, -2.8F, -0.8F);
      Sight3.setTextureSize(64, 32);
      Sight3.mirror = true;
      setRotation(Sight3, 0.2602503F, 0F, 0F);
      Sight4 = new ModelRenderer(this, 0, 0);
      Sight4.addBox(0F, 0F, 0F, 1, 4, 1);
      Sight4.setRotationPoint(0.5F, -3.5F, 1.8F);
      Sight4.setTextureSize(64, 32);
      Sight4.mirror = true;
      setRotation(Sight4, 0.2602503F, 0F, 0F);
      Sight5 = new ModelRenderer(this, 0, 0);
      Sight5.addBox(0F, 0F, 0F, 1, 4, 1);
      Sight5.setRotationPoint(0.5F, -2.8F, -0.8F);
      Sight5.setTextureSize(64, 32);
      Sight5.mirror = true;
      setRotation(Sight5, 0.2602503F, 0F, 0F);
      Sight6 = new ModelRenderer(this, 0, 0);
      Sight6.addBox(0F, 0F, 0F, 1, 4, 2);
      Sight6.setRotationPoint(1F, -3F, 0F);
      Sight6.setTextureSize(64, 32);
      Sight6.mirror = true;
      setRotation(Sight6, 0.2602503F, 0F, 0F);
      Sight7 = new ModelRenderer(this, 0, 0);
      Sight7.addBox(0F, 0F, 0F, 2, 1, 1);
      Sight7.setRotationPoint(-1.5F, -0.6F, 3F);
      Sight7.setTextureSize(64, 32);
      Sight7.mirror = true;
      setRotation(Sight7, 0.2602503F, 0F, 0F);
      Sight8 = new ModelRenderer(this, 0, 0);
      Sight8.addBox(0F, 0F, 0F, 2, 2, 1);
      Sight8.setRotationPoint(-1.5F, -2.3F, 2.6F);
      Sight8.setTextureSize(64, 32);
      Sight8.mirror = true;
      setRotation(Sight8, 0.2602503F, 0F, 0F);
      Sight9 = new ModelRenderer(this, 0, 0);
      Sight9.addBox(0F, 0F, 0F, 2, 3, 1);
      Sight9.setRotationPoint(-1.5F, -2F, -1.2F);
      Sight9.setTextureSize(64, 32);
      Sight9.mirror = true;
      setRotation(Sight9, 0.2602503F, 0F, 0F);
      Sight10 = new ModelRenderer(this, 0, 0);
      Sight10.addBox(0F, 0F, 0F, 5, 1, 10);
      Sight10.setRotationPoint(-3F, 0F, -1.4F);
      Sight10.setTextureSize(64, 32);
      Sight10.mirror = true;
      setRotation(Sight10, 0F, 0F, 0F);
      Sight11 = new ModelRenderer(this, 0, 0);
      Sight11.addBox(0F, 0F, 0F, 6, 1, 3);
      Sight11.setRotationPoint(-3.5F, 0F, 0.3F);
      Sight11.setTextureSize(64, 32);
      Sight11.mirror = true;
      setRotation(Sight11, 0F, 0F, 0F);
      Sight12 = new ModelRenderer(this, 0, 0);
      Sight12.addBox(0F, 0F, 0F, 1, 2, 4);
      Sight12.setRotationPoint(-3F, -2F, 4.6F);
      Sight12.setTextureSize(64, 32);
      Sight12.mirror = true;
      setRotation(Sight12, 0F, 0F, 0F);
      Sight13 = new ModelRenderer(this, 0, 0);
      Sight13.addBox(0F, 0F, 0F, 1, 2, 4);
      Sight13.setRotationPoint(1F, -2F, 4.6F);
      Sight13.setTextureSize(64, 32);
      Sight13.mirror = true;
      setRotation(Sight13, 0F, 0F, 0F);
      Sight14 = new ModelRenderer(this, 0, 0);
      Sight14.addBox(0F, 0F, 0F, 1, 1, 2);
      Sight14.setRotationPoint(1F, -3F, 4.6F);
      Sight14.setTextureSize(64, 32);
      Sight14.mirror = true;
      setRotation(Sight14, 0F, 0F, 0F);
      Sight15 = new ModelRenderer(this, 0, 0);
      Sight15.addBox(0F, 0F, 0F, 1, 1, 2);
      Sight15.setRotationPoint(-3F, -3F, 4.6F);
      Sight15.setTextureSize(64, 32);
      Sight15.mirror = true;
      setRotation(Sight15, 0F, 0F, 0F);
      Sight16 = new ModelRenderer(this, 0, 0);
      Sight16.addBox(0F, 0F, 0F, 1, 1, 2);
      Sight16.setRotationPoint(-3F, -3F, 6.6F);
      Sight16.setTextureSize(64, 32);
      Sight16.mirror = true;
      setRotation(Sight16, -0.4461433F, 0F, 0F);
      Sight17 = new ModelRenderer(this, 0, 0);
      Sight17.addBox(0F, 0F, 0F, 1, 1, 2);
      Sight17.setRotationPoint(1F, -3F, 6.6F);
      Sight17.setTextureSize(64, 32);
      Sight17.mirror = true;
      setRotation(Sight17, -0.4461433F, 0F, 0F);
      Sight18 = new ModelRenderer(this, 0, 0);
      Sight18.addBox(0F, 0F, 0F, 3, 2, 4);
      Sight18.setRotationPoint(-2F, -1.8F, 4.6F);
      Sight18.setTextureSize(64, 32);
      Sight18.mirror = true;
      setRotation(Sight18, 0F, 0F, 0F);
      Sight19 = new ModelRenderer(this, 0, 0);
      Sight19.addBox(0F, 0F, 0F, 5, 2, 1);
      Sight19.setRotationPoint(-3F, -1.2F, 4.6F);
      Sight19.setTextureSize(64, 32);
      Sight19.mirror = true;
      setRotation(Sight19, -0.9294653F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Sight1.render(f5);
    Sight2.render(f5);
    Sight3.render(f5);
    Sight4.render(f5);
    Sight5.render(f5);
    Sight6.render(f5);
    Sight7.render(f5);
    Sight8.render(f5);
    Sight9.render(f5);
    Sight10.render(f5);
    Sight11.render(f5);
    Sight12.render(f5);
    Sight13.render(f5);
    Sight14.render(f5);
    Sight15.render(f5);
    Sight16.render(f5);
    Sight17.render(f5);
    Sight18.render(f5);
    Sight19.render(f5);
  }

}
