// Date: 12/31/2018 3:45:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ScarIron2 extends ModelBase
{
  //fields
    ModelRenderer sight1;
    ModelRenderer sight3;
    ModelRenderer sight4;
    ModelRenderer sight5;
    ModelRenderer sight7;
    ModelRenderer sight8;
    ModelRenderer sight9;
    ModelRenderer sight10;
    ModelRenderer sight11;
    ModelRenderer sight12;
    ModelRenderer sight13;
    ModelRenderer sight14;
    ModelRenderer sight15;
    ModelRenderer sight16;
    ModelRenderer sight17;
    ModelRenderer sight18;
    ModelRenderer sight19;
    ModelRenderer sight20;
  
  public ScarIron2()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      sight1 = new ModelRenderer(this, 0, 0);
      sight1.addBox(0F, 0F, 0F, 1, 2, 2);
      sight1.setRotationPoint(0F, -6F, 0F);
      sight1.setTextureSize(64, 32);
      sight1.mirror = true;
      setRotation(sight1, 0F, 0F, 0F);
      sight3 = new ModelRenderer(this, 0, 0);
      sight3.addBox(0F, 0F, 0F, 1, 2, 2);
      sight3.setRotationPoint(-3F, -6F, 0F);
      sight3.setTextureSize(64, 32);
      sight3.mirror = true;
      setRotation(sight3, 0F, 0F, 0F);
      sight4 = new ModelRenderer(this, 0, 0);
      sight4.addBox(0F, 0F, 0F, 2, 8, 2);
      sight4.setRotationPoint(-2F, -3F, 0F);
      sight4.setTextureSize(64, 32);
      sight4.mirror = true;
      setRotation(sight4, 0F, 0F, 0F);
      sight5 = new ModelRenderer(this, 0, 0);
      sight5.addBox(0F, 0F, 0F, 4, 3, 2);
      sight5.setRotationPoint(-3F, 5F, 0F);
      sight5.setTextureSize(64, 32);
      sight5.mirror = true;
      setRotation(sight5, 0F, 0F, 0F);
      sight7 = new ModelRenderer(this, 0, 0);
      sight7.addBox(0F, 0F, 0F, 2, 1, 2);
      sight7.setRotationPoint(0.5F, -3.5F, 0F);
      sight7.setTextureSize(64, 32);
      sight7.mirror = true;
      setRotation(sight7, 0F, 0F, 2.156359F);
      sight8 = new ModelRenderer(this, 0, 0);
      sight8.addBox(0F, 0F, 0F, 1, 2, 2);
      sight8.setRotationPoint(-2.5F, -3.5F, 0F);
      sight8.setTextureSize(64, 32);
      sight8.mirror = true;
      setRotation(sight8, 0F, 0F, -0.5576792F);
      sight9 = new ModelRenderer(this, 0, 0);
      sight9.addBox(0F, 0F, 0F, 1, 7, 2);
      sight9.setRotationPoint(1F, 5F, 0F);
      sight9.setTextureSize(64, 32);
      sight9.mirror = true;
      setRotation(sight9, 0F, 0F, 3.011467F);
      sight10 = new ModelRenderer(this, 0, 0);
      sight10.addBox(0F, 0F, 0F, 7, 1, 2);
      sight10.setRotationPoint(-3F, 5F, 0F);
      sight10.setTextureSize(64, 32);
      sight10.mirror = true;
      setRotation(sight10, 0F, 0F, -1.43117F);
      sight11 = new ModelRenderer(this, 0, 0);
      sight11.addBox(0F, 0F, 0F, 2, 1, 2);
      sight11.setRotationPoint(-2F, -7F, 0F);
      sight11.setTextureSize(64, 32);
      sight11.mirror = true;
      setRotation(sight11, 0F, 0F, 0F);
      sight12 = new ModelRenderer(this, 0, 0);
      sight12.addBox(0F, 0F, 0F, 1, 1, 2);
      sight12.setRotationPoint(-3F, -6F, 0F);
      sight12.setTextureSize(64, 32);
      sight12.mirror = true;
      setRotation(sight12, 0F, 0F, -0.7853982F);
      sight13 = new ModelRenderer(this, 0, 0);
      sight13.addBox(0F, 0F, 0F, 1, 1, 2);
      sight13.setRotationPoint(0F, -7F, 0F);
      sight13.setTextureSize(64, 32);
      sight13.mirror = true;
      setRotation(sight13, 0F, 0F, 0.7853982F);
      sight14 = new ModelRenderer(this, 0, 0);
      sight14.addBox(0F, 0F, 0F, 2, 1, 2);
      sight14.setRotationPoint(-2F, -4F, 0F);
      sight14.setTextureSize(64, 32);
      sight14.mirror = true;
      setRotation(sight14, 0F, 0F, 0F);
      sight15 = new ModelRenderer(this, 0, 0);
      sight15.addBox(0F, 0F, 0F, 1, 1, 2);
      sight15.setRotationPoint(-3F, -4F, 0F);
      sight15.setTextureSize(64, 32);
      sight15.mirror = true;
      setRotation(sight15, 0F, 0F, -0.7853982F);
      sight16 = new ModelRenderer(this, 0, 0);
      sight16.addBox(0F, 0F, 0F, 1, 1, 2);
      sight16.setRotationPoint(-2F, -7F, 0F);
      sight16.setTextureSize(64, 32);
      sight16.mirror = true;
      setRotation(sight16, 0F, 0F, 0.7853982F);
      sight17 = new ModelRenderer(this, 0, 0);
      sight17.addBox(0F, 0F, 0F, 1, 1, 2);
      sight17.setRotationPoint(1F, -6F, 0F);
      sight17.setTextureSize(64, 32);
      sight17.mirror = true;
      setRotation(sight17, 0F, 0F, 2.356194F);
      sight18 = new ModelRenderer(this, 0, 0);
      sight18.addBox(0F, 0F, 0F, 1, 1, 2);
      sight18.setRotationPoint(1F, -4F, 0F);
      sight18.setTextureSize(64, 32);
      sight18.mirror = true;
      setRotation(sight18, 0F, 0F, 2.356194F);
      sight19 = new ModelRenderer(this, 0, 0);
      sight19.addBox(0F, 0F, 0F, 1, 1, 2);
      sight19.setRotationPoint(0F, -3F, 0F);
      sight19.setTextureSize(64, 32);
      sight19.mirror = true;
      setRotation(sight19, 0F, 0F, -2.356194F);
      sight20 = new ModelRenderer(this, 0, 0);
      sight20.addBox(0F, 0F, 0F, 1, 1, 2);
      sight20.setRotationPoint(-2F, -3F, 0F);
      sight20.setTextureSize(64, 32);
      sight20.mirror = true;
      setRotation(sight20, 0F, 0F, -2.356194F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    sight1.render(f5);
    sight3.render(f5);
    sight4.render(f5);
    sight5.render(f5);
    sight7.render(f5);
    sight8.render(f5);
    sight9.render(f5);
    sight10.render(f5);
    sight11.render(f5);
    sight12.render(f5);
    sight13.render(f5);
    sight14.render(f5);
    sight15.render(f5);
    sight16.render(f5);
    sight17.render(f5);
    sight18.render(f5);
    sight19.render(f5);
    sight20.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
