// Date: 7/29/2019 10:18:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ServerRackLeftAlt2 extends ModelBase
{
  //fields
    ModelRenderer rack1;
    ModelRenderer rack2;
    ModelRenderer rack3;
    ModelRenderer rack4;
    ModelRenderer rack5;
    ModelRenderer rack6;
    ModelRenderer rack7;
    ModelRenderer rack8;
    ModelRenderer rack9;
    ModelRenderer rack10;
  
  public ServerRackLeftAlt2()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      rack1 = new ModelRenderer(this, 0, 0);
      rack1.addBox(0F, 0F, 0F, 16, 2, 13);
      rack1.setRotationPoint(-8F, 20F, -6F);
      rack1.setTextureSize(64, 32);
      rack1.mirror = true;
      setRotation(rack1, 0F, 0F, 0F);
      rack2 = new ModelRenderer(this, 0, 0);
      rack2.addBox(0F, 0F, 0F, 2, 16, 2);
      rack2.setRotationPoint(-8.2F, 8F, -6.1F);
      rack2.setTextureSize(64, 32);
      rack2.mirror = true;
      setRotation(rack2, 0F, 0F, 0F);
      rack3 = new ModelRenderer(this, 0, 0);
      rack3.addBox(0F, 0F, 0F, 2, 16, 2);
      rack3.setRotationPoint(-8.2F, 8F, 5.1F);
      rack3.setTextureSize(64, 32);
      rack3.mirror = true;
      setRotation(rack3, 0F, 0F, 0F);
      rack4 = new ModelRenderer(this, 0, 50);
      rack4.addBox(0F, 0F, 0F, 1, 15, 9);
      rack4.setRotationPoint(-8.1F, 8F, -4.1F);
      rack4.setTextureSize(64, 32);
      rack4.mirror = true;
      setRotation(rack4, 0F, 0F, 0F);
      rack5 = new ModelRenderer(this, 100, 0);
      rack5.addBox(0F, 0F, 0F, 15, 8, 12);
      rack5.setRotationPoint(-7F, 8F, -5.5F);
      rack5.setTextureSize(64, 32);
      rack5.mirror = true;
      setRotation(rack5, 0F, 0F, 0F);
      rack6 = new ModelRenderer(this, 100, 0);
      rack6.addBox(0F, 0F, 0F, 15, 4, 11);
      rack6.setRotationPoint(-7F, 16F, -5.2F);
      rack6.setTextureSize(64, 32);
      rack6.mirror = true;
      setRotation(rack6, 0F, 0F, 0F);
      rack7 = new ModelRenderer(this, 100, 50);
      rack7.addBox(0F, 0F, 0F, 13, 2, 1);
      rack7.setRotationPoint(-6F, 16.3F, -5.5F);
      rack7.setTextureSize(64, 32);
      rack7.mirror = true;
      setRotation(rack7, 0F, 0F, 0F);
      rack8 = new ModelRenderer(this, 100, 50);
      rack8.addBox(0F, 0F, 0F, 13, 1, 1);
      rack8.setRotationPoint(-6F, 18.7F, -5.5F);
      rack8.setTextureSize(64, 32);
      rack8.mirror = true;
      setRotation(rack8, 0F, 0F, 0F);
      rack9 = new ModelRenderer(this, 100, 50);
      rack9.addBox(0F, 0F, 0F, 8, 2, 1);
      rack9.setRotationPoint(-5.5F, 16.3F, -5.7F);
      rack9.setTextureSize(64, 32);
      rack9.mirror = true;
      setRotation(rack9, 0F, 0F, 0F);
      rack10 = new ModelRenderer(this, 100, 0);
      rack10.addBox(0F, 0F, 0F, 15, 1, 1);
      rack10.setRotationPoint(-7F, 9F, -5.6F);
      rack10.setTextureSize(64, 32);
      rack10.mirror = true;
      setRotation(rack10, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    rack1.render(f5);
    rack2.render(f5);
    rack3.render(f5);
    rack4.render(f5);
    rack5.render(f5);
    rack6.render(f5);
    rack7.render(f5);
    rack8.render(f5);
    rack9.render(f5);
    rack10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
