// Date: 7/29/2019 10:41:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ServerRackEmptyLeft extends ModelBase
{
  //fields
    ModelRenderer rack1;
    ModelRenderer rack2;
    ModelRenderer rack3;
    ModelRenderer rack4;
  
  public ServerRackEmptyLeft()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      rack1 = new ModelRenderer(this, 0, 0);
      rack1.addBox(0F, 0F, 0F, 16, 2, 13);
      rack1.setRotationPoint(-8F, 20F, -6F);
      rack1.setTextureSize(64, 32);
      rack1.mirror = true;
      setRotation(rack1, 0F, 0F, 0F);
      rack2 = new ModelRenderer(this, 0, 0);
      rack2.addBox(0F, 0F, 0F, 2, 16, 2);
      rack2.setRotationPoint(-8.2F, 8F, -6.1F);
      rack2.setTextureSize(64, 32);
      rack2.mirror = true;
      setRotation(rack2, 0F, 0F, 0F);
      rack3 = new ModelRenderer(this, 0, 0);
      rack3.addBox(0F, 0F, 0F, 2, 16, 2);
      rack3.setRotationPoint(-8.2F, 8F, 5.1F);
      rack3.setTextureSize(64, 32);
      rack3.mirror = true;
      setRotation(rack3, 0F, 0F, 0F);
      rack4 = new ModelRenderer(this, 0, 50);
      rack4.addBox(0F, 0F, 0F, 1, 15, 9);
      rack4.setRotationPoint(-8.1F, 8F, -4.1F);
      rack4.setTextureSize(64, 32);
      rack4.mirror = true;
      setRotation(rack4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    rack1.render(f5);
    rack2.render(f5);
    rack3.render(f5);
    rack4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
