// Date: 2/12/2017 12:28:40 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.paneedah.mw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Suppressor300AACBlackout extends ModelBase
{
  //fields
    ModelRenderer gun1;
    ModelRenderer gun2;
    ModelRenderer gun3;
    ModelRenderer gun4;
    ModelRenderer gun5;
    ModelRenderer gun6;
    ModelRenderer gun7;
    ModelRenderer gun8;
    ModelRenderer gun9;
    ModelRenderer gun10;
    ModelRenderer gun11;
    ModelRenderer gun12;
    ModelRenderer gun13;
    ModelRenderer gun26;
    ModelRenderer gun27;
    ModelRenderer gun28;
    ModelRenderer gun29;
    ModelRenderer gun30;
    ModelRenderer gun31;
    ModelRenderer gun32;
    ModelRenderer gun33;
    ModelRenderer gun34;
    ModelRenderer gun35;
    ModelRenderer gun36;
    ModelRenderer gun37;
    ModelRenderer gun38;
    ModelRenderer gun39;
    ModelRenderer gun40;
    ModelRenderer gun41;
    ModelRenderer gun42;
    ModelRenderer gun43;
    ModelRenderer gun44;
    ModelRenderer gun45;
    ModelRenderer gun46;
  
  public Suppressor300AACBlackout()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      gun1 = new ModelRenderer(this, 0, 0);
      gun1.addBox(0F, 0F, 0F, 2, 3, 22);
      gun1.setRotationPoint(0F, 0F, -2F);
      gun1.setTextureSize(64, 32);
      gun1.mirror = true;
      setRotation(gun1, 0F, 0F, 0F);
      gun2 = new ModelRenderer(this, 0, 0);
      gun2.addBox(0F, 0F, 0F, 1, 2, 22);
      gun2.setRotationPoint(2F, 1F, -2F);
      gun2.setTextureSize(64, 32);
      gun2.mirror = true;
      setRotation(gun2, 0F, 0F, 0F);
      gun3 = new ModelRenderer(this, 0, 0);
      gun3.addBox(0F, 0F, 0F, 1, 2, 22);
      gun3.setRotationPoint(-1F, 1F, -2F);
      gun3.setTextureSize(64, 32);
      gun3.mirror = true;
      setRotation(gun3, 0F, 0F, 0F);
      gun4 = new ModelRenderer(this, 0, 0);
      gun4.addBox(0F, 0F, 0F, 2, 1, 22);
      gun4.setRotationPoint(0F, 3F, -2F);
      gun4.setTextureSize(64, 32);
      gun4.mirror = true;
      setRotation(gun4, 0F, 0F, 0F);
      gun5 = new ModelRenderer(this, 0, 0);
      gun5.addBox(0F, 0F, 0F, 1, 1, 22);
      gun5.setRotationPoint(3F, 1F, -2F);
      gun5.setTextureSize(64, 32);
      gun5.mirror = true;
      setRotation(gun5, 0F, 0F, 2.379431F);
      gun6 = new ModelRenderer(this, 0, 0);
      gun6.addBox(0F, 0F, 0F, 1, 1, 22);
      gun6.setRotationPoint(3F, 3F, -2F);
      gun6.setTextureSize(64, 32);
      gun6.mirror = true;
      setRotation(gun6, 0F, 0F, 2.379431F);
      gun7 = new ModelRenderer(this, 0, 0);
      gun7.addBox(0F, 0F, 0F, 1, 1, 22);
      gun7.setRotationPoint(2F, 0F, -2F);
      gun7.setTextureSize(64, 32);
      gun7.mirror = true;
      setRotation(gun7, 0F, 0F, 0.7807508F);
      gun8 = new ModelRenderer(this, 0, 0);
      gun8.addBox(0F, 0F, 0F, 1, 1, 22);
      gun8.setRotationPoint(2F, 2.6F, -2F);
      gun8.setTextureSize(64, 32);
      gun8.mirror = true;
      setRotation(gun8, 0F, 0F, 0.7807508F);
      gun9 = new ModelRenderer(this, 0, 0);
      gun9.addBox(0F, 0F, 0F, 1, 1, 22);
      gun9.setRotationPoint(0F, 2.6F, -2F);
      gun9.setTextureSize(64, 32);
      gun9.mirror = true;
      setRotation(gun9, 0F, 0F, 0.7807508F);
      gun10 = new ModelRenderer(this, 0, 0);
      gun10.addBox(0F, 0F, 0F, 1, 1, 22);
      gun10.setRotationPoint(0.4F, 3F, -2F);
      gun10.setTextureSize(64, 32);
      gun10.mirror = true;
      setRotation(gun10, 0F, 0F, 2.379431F);
      gun11 = new ModelRenderer(this, 0, 0);
      gun11.addBox(0F, 0F, 0F, 1, 1, 20);
      gun11.setRotationPoint(0.4F, 3F, 0F);
      gun11.setTextureSize(64, 32);
      gun11.mirror = true;
      setRotation(gun11, 0F, 0F, 2.379431F);
      gun12 = new ModelRenderer(this, 0, 0);
      gun12.addBox(0F, 0F, 0F, 1, 1, 22);
      gun12.setRotationPoint(0.4F, 1F, -2F);
      gun12.setTextureSize(64, 32);
      gun12.mirror = true;
      setRotation(gun12, 0F, 0F, 2.379431F);
      gun13 = new ModelRenderer(this, 0, 0);
      gun13.addBox(0F, 0F, 0F, 1, 1, 22);
      gun13.setRotationPoint(0F, 0F, -2F);
      gun13.setTextureSize(64, 32);
      gun13.mirror = true;
      setRotation(gun13, 0F, 0F, 0.7807508F);
      gun26 = new ModelRenderer(this, 0, 0);
      gun26.addBox(0F, 0F, 0F, 2, 1, 12);
      gun26.setRotationPoint(0F, -0.1F, 8F);
      gun26.setTextureSize(64, 32);
      gun26.mirror = true;
      setRotation(gun26, 0F, 0F, 0F);
      gun27 = new ModelRenderer(this, 0, 0);
      gun27.addBox(0F, 0F, 0F, 1, 1, 12);
      gun27.setRotationPoint(2F, -0.1F, 8F);
      gun27.setTextureSize(64, 32);
      gun27.mirror = true;
      setRotation(gun27, 0F, 0F, 0.7807508F);
      gun28 = new ModelRenderer(this, 0, 0);
      gun28.addBox(0F, 0F, 0F, 1, 1, 12);
      gun28.setRotationPoint(3.1F, 1F, 8F);
      gun28.setTextureSize(64, 32);
      gun28.mirror = true;
      setRotation(gun28, 0F, 0F, 2.379431F);
      gun29 = new ModelRenderer(this, 0, 0);
      gun29.addBox(0F, 0F, 0F, 1, 2, 12);
      gun29.setRotationPoint(2.1F, 1F, 8F);
      gun29.setTextureSize(64, 32);
      gun29.mirror = true;
      setRotation(gun29, 0F, 0F, 0F);
      gun30 = new ModelRenderer(this, 0, 0);
      gun30.addBox(0F, 0F, 0F, 1, 1, 12);
      gun30.setRotationPoint(3.1F, 3F, 8F);
      gun30.setTextureSize(64, 32);
      gun30.mirror = true;
      setRotation(gun30, 0F, 0F, 2.379431F);
      gun31 = new ModelRenderer(this, 0, 0);
      gun31.addBox(0F, 0F, 0F, 1, 1, 12);
      gun31.setRotationPoint(2F, 2.7F, 8F);
      gun31.setTextureSize(64, 32);
      gun31.mirror = true;
      setRotation(gun31, 0F, 0F, 0.7807508F);
      gun32 = new ModelRenderer(this, 0, 0);
      gun32.addBox(0F, 0F, 0F, 1, 1, 12);
      gun32.setRotationPoint(0F, -0.1F, 8F);
      gun32.setTextureSize(64, 32);
      gun32.mirror = true;
      setRotation(gun32, 0F, 0F, 0.7807508F);
      gun33 = new ModelRenderer(this, 0, 0);
      gun33.addBox(0F, 0F, 0F, 1, 1, 12);
      gun33.setRotationPoint(0.3F, 1F, 8F);
      gun33.setTextureSize(64, 32);
      gun33.mirror = true;
      setRotation(gun33, 0F, 0F, 2.379431F);
      gun34 = new ModelRenderer(this, 0, 0);
      gun34.addBox(0F, 0F, 0F, 1, 2, 12);
      gun34.setRotationPoint(-1.1F, 1F, 8F);
      gun34.setTextureSize(64, 32);
      gun34.mirror = true;
      setRotation(gun34, 0F, 0F, 0F);
      gun35 = new ModelRenderer(this, 0, 0);
      gun35.addBox(0F, 0F, 0F, 1, 1, 12);
      gun35.setRotationPoint(0.3F, 3F, 8F);
      gun35.setTextureSize(64, 32);
      gun35.mirror = true;
      setRotation(gun35, 0F, 0F, 2.379431F);
      gun36 = new ModelRenderer(this, 0, 0);
      gun36.addBox(0F, 0F, 0F, 1, 2, 7);
      gun36.setRotationPoint(-1.1F, 1F, 13F);
      gun36.setTextureSize(64, 32);
      gun36.mirror = true;
      setRotation(gun36, 0F, 0F, 0F);
      gun37 = new ModelRenderer(this, 0, 0);
      gun37.addBox(0F, 0F, 0F, 1, 1, 12);
      gun37.setRotationPoint(0F, 2.7F, 8F);
      gun37.setTextureSize(64, 32);
      gun37.mirror = true;
      setRotation(gun37, 0F, 0F, 0.7807508F);
      gun38 = new ModelRenderer(this, 0, 0);
      gun38.addBox(0F, 0F, 0F, 2, 1, 12);
      gun38.setRotationPoint(0F, 3.1F, 8F);
      gun38.setTextureSize(64, 32);
      gun38.mirror = true;
      setRotation(gun38, 0F, 0F, 0F);
      gun39 = new ModelRenderer(this, 0, 0);
      gun39.addBox(0F, 0F, 0F, 1, 1, 7);
      gun39.setRotationPoint(0.5F, -0.2F, 10.5F);
      gun39.setTextureSize(64, 32);
      gun39.mirror = true;
      setRotation(gun39, 0F, 0F, 0F);
      gun40 = new ModelRenderer(this, 0, 0);
      gun40.addBox(0F, 0F, 0F, 1, 1, 7);
      gun40.setRotationPoint(0.5F, 3.2F, 10.5F);
      gun40.setTextureSize(64, 32);
      gun40.mirror = true;
      setRotation(gun40, 0F, 0F, 0F);
      gun41 = new ModelRenderer(this, 0, 0);
      gun41.addBox(0F, 0F, 0F, 1, 1, 7);
      gun41.setRotationPoint(2.2F, 1.5F, 10.5F);
      gun41.setTextureSize(64, 32);
      gun41.mirror = true;
      setRotation(gun41, 0F, 0F, 0F);
      gun42 = new ModelRenderer(this, 0, 0);
      gun42.addBox(0F, 0F, 0F, 1, 1, 7);
      gun42.setRotationPoint(-1.2F, 1.5F, 10.5F);
      gun42.setTextureSize(64, 32);
      gun42.mirror = true;
      setRotation(gun42, 0F, 0F, 0F);
      gun43 = new ModelRenderer(this, 0, 0);
      gun43.addBox(0F, 0F, 0F, 1, 1, 7);
      gun43.setRotationPoint(-0.25F, 0.05F, 10.5F);
      gun43.setTextureSize(64, 32);
      gun43.mirror = true;
      setRotation(gun43, 0F, 0F, 0.7807508F);
      gun44 = new ModelRenderer(this, 0, 0);
      gun44.addBox(0F, 0F, 0F, 1, 1, 7);
      gun44.setRotationPoint(2.2F, 0.05F, 10.5F);
      gun44.setTextureSize(64, 32);
      gun44.mirror = true;
      setRotation(gun44, 0F, 0F, 0.7807508F);
      gun45 = new ModelRenderer(this, 0, 0);
      gun45.addBox(0F, 0F, 0F, 1, 1, 7);
      gun45.setRotationPoint(3F, 3.2F, 10.5F);
      gun45.setTextureSize(64, 32);
      gun45.mirror = true;
      setRotation(gun45, 0F, 0F, 2.379431F);
      gun46 = new ModelRenderer(this, 0, 0);
      gun46.addBox(0F, 0F, 0F, 1, 1, 7);
      gun46.setRotationPoint(-0.15F, 2.6F, 10.5F);
      gun46.setTextureSize(64, 32);
      gun46.mirror = true;
      setRotation(gun46, 0F, 0F, 0.7807508F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    gun1.render(f5);
    gun2.render(f5);
    gun3.render(f5);
    gun4.render(f5);
    gun5.render(f5);
    gun6.render(f5);
    gun7.render(f5);
    gun8.render(f5);
    gun9.render(f5);
    gun10.render(f5);
    gun11.render(f5);
    gun12.render(f5);
    gun13.render(f5);
    gun26.render(f5);
    gun27.render(f5);
    gun28.render(f5);
    gun29.render(f5);
    gun30.render(f5);
    gun31.render(f5);
    gun32.render(f5);
    gun33.render(f5);
    gun34.render(f5);
    gun35.render(f5);
    gun36.render(f5);
    gun37.render(f5);
    gun38.render(f5);
    gun39.render(f5);
    gun40.render(f5);
    gun41.render(f5);
    gun42.render(f5);
    gun43.render(f5);
    gun44.render(f5);
    gun45.render(f5);
    gun46.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
