package com.paneedah.mwc.entities;

import com.paneedah.mwc.ModernWarfareMod;
import com.paneedah.mwc.proxies.CommonProxy;
import com.paneedah.mwc.weapons.Guns;
import com.paneedah.mwc.weapons.Magazines;
import com.paneedah.weaponlib.ai.*;
import com.paneedah.weaponlib.compatibility.CompatibleBiomeType;
import com.paneedah.weaponlib.compatibility.CompatibleEntityAIAttackOnCollide;
import net.minecraft.entity.EntityCreature;
import net.minecraft.entity.ai.*;
import net.minecraft.entity.boss.EntityDragon;
import net.minecraft.entity.monster.*;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.entity.passive.EntityWolf;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.world.EnumDifficulty;

import static com.paneedah.weaponlib.compatibility.CompatibilityProvider.compatibility;

public class Entities {

    public static void init(CommonProxy commonProxy) {

        new BanditEntityFactory().createEntity(ModernWarfareMod.MOD_CONTEXT);
        
        new SampleMissionGiverEntityFactory().createEntity(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombieBlistered")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(250)
            .withEntityIdSupplier(() -> 10001)
//          .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
//          .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
//          .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
//          .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
//           .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
//          .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.ZombieBlistered", "zombieblistered.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withMaxSpeed(0.25F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(15.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
//          .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
//           .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
//           .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
//          .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombieRipper")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(150)
            .withEntityIdSupplier(() -> 10002)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.RipperZombie", "ripperzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withMaxSpeed(0.3F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(10.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("tornzombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(30)
            .withEntityIdSupplier(() -> 10003)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(20, 1, 5, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.TornZombie", "tornzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))

            .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("necromorph")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(200)
            .withEntityIdSupplier(() -> 10004)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(0, 0, 0, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.Necromorph", "necromorph.png")
            .withHurtSound("necromorph_hurt")
            .withAmbientSound("necromorph_ambient")
            .withStepSound("step")
            .withDeathSound("necromorph_death")
            .withMaxSpeed(0.35F) // 0.1-0.3 is normal speed
            .withCollisionAttackDamage(5.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("tyke")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(40)
            .withEntityIdSupplier(() -> 10005)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(60, 30, 35, CompatibleBiomeType.SANDY)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.Tyke", "tyke.png")
            .withHurtSound("tyke_hurt")
            .withAmbientSound("tyke_ambient")
            .withStepSound("tyke_step")
            .withDeathSound("tyke_death")
            .withMaxSpeed(0.35F) // 0.1-0.3 is normal speed
            .withSize(1f, 1f)
            .withCollisionAttackDamage(6.0)
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withAiTask(2, e-> new EntityAILeapAtTarget(e, 0.4F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
            .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "soldier", true))
            .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "terrorist", true))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(30)
            .withEntityIdSupplier(() -> 10006)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(50, 80, 150, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.Zombie", "zombie_1.png")
            .withTexturedModelVariant("com.paneedah.mwc.models.Zombie", "zombie_2.png")
            .withTexturedModelVariant("com.paneedah.mwc.models.Zombie", "zombie_3.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withMaxSpeed(0.1F) // 0.1-0.3 is normal speed
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
//            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
//            .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("hazmat_zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(40)
            .withEntityIdSupplier(() -> 10007)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(50, 80, 150, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.HazmatZombie", "hazmatzombie.png")
            .withHurtSound("hazmatzombie_hurt")
            .withAmbientSound("hazmatzombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("hazmatzombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withMaxSpeed(0.3F) // 0.1-0.3 is normal speed
//            .withCollisionAttackDamage(30.0)
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("Defiled Zombie")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(300)
            .withEntityIdSupplier(() -> 10008)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(0, 0, 0, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.DefiledZombie", "defiledzombie.png")
            .withHurtSound("zombie_hurt")
            .withAmbientSound("zombie_ambient")
            .withStepSound("zombie_step")
            .withDeathSound("zombie_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
//           .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
            .withName("deathclaw")
            .withBaseClass(EntityCustomMob.class)
            .withMaxHealth(5000)
            .withEntityIdSupplier(() -> 10009)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
    //      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
    //      .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
    //       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
    //      .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
            .withPrimaryEquipmentDropChance(1f)
            .withSpawn(0, 0, 0, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
            .withSpawnEgg(0xA0A000, 0xA0A010)
            .withTexturedModelVariant("com.paneedah.mwc.models.Deathclaw", "deathclaw.png")
            .withHurtSound("deathclaw_hurt")
            .withAmbientSound("deathclaw_ambient")
          .withStepSound("deathclaw_step")
            .withDeathSound("deathclaw_death")
            .withAiTask(1, e -> new EntityAISwimming(e))
            .withCollisionAttackDamage(30.0)
            .withMaxSpeed(0.45F) // 0.1-0.3 is normal speed
    //      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
    //       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
            .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
            .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
            .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 100.0F))
            .withAiTask(6, e -> new EntityAILookIdle(e))
            .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
            .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
            .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
    
    //       .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
    //      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
            .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
        .withName("molded")
        .withBaseClass(EntityCustomMob.class)
        .withMaxHealth(100)
        .withEntityIdSupplier(() -> 10010)
//      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 4f, Magazines.Magazine9mm)
//      .withEquipmentOption(Guns.MakarovPM, EnumDifficulty.EASY, 3.8f, Magazines.Magazine9mm, Attachments.Silencer9mm)
//       .withEquipmentOption(Guns.AK74U, EnumDifficulty.EASY, 0.1f, Magazines.AKS74UMag) //, Attachments.Silencer9mm)
//       .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag)
//    .withEquipmentOption(Guns.VSSVintorez, EnumDifficulty.EASY, 0.1f, Magazines.VSSVintorezMag, Attachments.PSO1)
//   .withEquipmentOption(Guns.Remington870, EnumDifficulty.EASY, 0.07f)
        .withPrimaryEquipmentDropChance(1f)
//        .withSpawn(1, 1, 1, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
        .withSpawnEgg(0xA0A000, 0xA0A010)
        .withTexturedModelVariant("com.paneedah.mwc.models.Molded", "molded.png")
        .withHurtSound("molded_hurt")
        .withAmbientSound("molded_ambient")
        .withDeathSound("molded_death")
//    .withStepSound("step")
        .withMaxSpeed(0.2F) // 0.1-0.3 is normal speed
        .withCollisionAttackDamage(10.0)
        .withAiTask(1, e -> new EntityAISwimming(e))
//      .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
//       .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
        .withAiTask(3, e -> new CompatibleEntityAIAttackOnCollide((EntityCustomMob)e, EntityPlayer.class, 1.0D, false))
        .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
        .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
        .withAiTask(6, e -> new EntityAILookIdle(e))
        .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
        .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
//   .withCollisionAttack(new InfectionAttack(0.1f, 20000, 1.2f, 1.0f, 1.8f))
//      .withDelayedAttack(new ExplosionAttack(2f, true, 30))
        .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
        .withName("soldier")
        .withBaseClass(EntityCustomMob.class)
        .withMaxHealth(80)
        .withEntityIdSupplier(() -> 10011)
        .withEquipmentOption(Guns.M4A1, EnumDifficulty.EASY, 0.1f, Magazines.M4A1Mag)
        .withEquipmentOption(Guns.M110, EnumDifficulty.EASY, 0.1f, Magazines.M110Mag)
        .withPrimaryEquipmentDropChance(0.4f)
        .withSpawn(1, 5, 6, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
        .withMaxTolerableLightBrightness(1f)
        .withSpawnEgg(0x5A674F, 0x464039)
        .withTexturedModelVariant("com.paneedah.mwc.models.Soldier", "soldier.png")
        .withTexturedModelVariant("com.paneedah.mwc.models.Soldier2", "soldier2.png")
        .withTexturedModelVariant("com.paneedah.mwc.models.SoldierSniper", "soldiersniper.png")
        .withHurtSound("hurt")
        .withAmbientSound("drawweapon")
//        .withStepSound("step")
        .withAiTask(1, e -> new EntityAISwimming(e))
        .withAiTask(3, e -> compatibility.createAiAvoidEntity((EntityCreature)e, EntityWolf.class, 6.0F, 1.0D, 1.2D))
        .withAiTask(4, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 10, 30.0F))
        .withAiTask(5, e -> new EntityAIWander((EntityCreature)e, 1.0D))
        .withAiTask(6, e -> new EntityAIWatchClosest(e, EntityPlayer.class, 50.0F))
        .withAiTask(6, e -> new EntityAILookIdle(e))
        .withAiTask(7, e -> new EntityAIBreakDoor(e))
        
        .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
        .withAiTargetTask(2, e -> compatibility.createAINearestAttackableTarget(e, EntityPlayer.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityHusk.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySkeleton.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpider.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEnderman.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityCreeper.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySlime.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityDragon.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEndermite.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityBlaze.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityGhast.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityIllusionIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityMagmaCube.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityPigZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpellcasterIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityStray.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVindicator.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityWitch.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombieVillager.class, true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "terrorist", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "tyke", true))
        .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
        .withName("turret")
        .withBaseClass(EntityCustomMob.class)
        .withMaxHealth(80)
        .withEntityIdSupplier(() -> 10012)
        .withEquipmentOption(Guns.turretgun, EnumDifficulty.EASY, 0.1f)
        .withPrimaryEquipmentDropChance(0.0f)
//        .withSpawn(1, 5, 6, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
//        .withMaxTolerableLightBrightness(1f)
        .withSpawnEgg(0x5A674F, 0x464039)
        .withTexturedModelVariant("com.paneedah.mwc.models.Turret", "turret.png")
        .withAmbientSound("turret_turn")
//        .withStepSound("step")
        .withMaxSpeed(0.0F) // 0.1-0.3 is normal speed
        .withAiTask(1, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 1, 50.0F))
        .withAiTask(2, e -> new EntityAILookIdle(e))
        .withCollidability(false)
        .withDespawnability(false)
        .withPushability(false)
        .withInvulnerability()
        .withLookHeightMulitplier(1.5f)
        .withSize(1f, 0.7f)
        .withPickupItemID(1)
        
        .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityHusk.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySkeleton.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpider.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEnderman.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityCreeper.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySlime.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityDragon.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEndermite.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityBlaze.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityGhast.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityIllusionIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityMagmaCube.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityPigZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpellcasterIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityStray.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVindicator.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityWitch.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombieVillager.class, true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "soldier", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "terrorist", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "tyke", true))
        .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
        .withName("turretupgraded")
        .withBaseClass(EntityCustomMob.class)
        .withMaxHealth(80)
        .withEntityIdSupplier(() -> 10013)
        .withEquipmentOption(Guns.turretgunupgraded, EnumDifficulty.EASY, 0.1f)
        .withPrimaryEquipmentDropChance(0.0f)
//        .withSpawn(1, 5, 6, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
//        .withMaxTolerableLightBrightness(1f)
        .withSpawnEgg(0x5A674F, 0x464039)
        .withTexturedModelVariant("com.paneedah.mwc.models.TurretBuff", "turretbuff.png")
        .withAmbientSound("turret_turn")
//        .withStepSound("step")
        .withMaxSpeed(0.0F) // 0.1-0.3 is normal speed
        .withAiTask(1, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 1, 50.0F))
        .withAiTask(2, e -> new EntityAILookIdle(e))
        .withCollidability(false)
        .withDespawnability(false)
        .withPushability(false)
        .withInvulnerability()
        .withLookHeightMulitplier(1.5f)
        .withSize(1f, 0.7f)
        .withPickupItemID(2)
        
        .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityHusk.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySkeleton.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpider.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEnderman.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityCreeper.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySlime.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityDragon.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEndermite.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityBlaze.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityGhast.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityIllusionIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityMagmaCube.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityPigZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpellcasterIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityStray.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVindicator.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityWitch.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombieVillager.class, true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "soldier", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "terrorist", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "tyke", true))
        .register(ModernWarfareMod.MOD_CONTEXT);
        
        new EntityConfiguration.Builder()
        .withName("turretsilenced")
        .withBaseClass(EntityCustomMob.class)
        .withMaxHealth(80)
        .withEntityIdSupplier(() -> 10014)
        .withEquipmentOption(Guns.turretgunsilenced, EnumDifficulty.EASY, 0.1f)
        .withPrimaryEquipmentDropChance(0.0f)
//        .withSpawn(1, 5, 6, CompatibleBiomeType.PLAINS, CompatibleBiomeType.FOREST, CompatibleBiomeType.HILLS)
//        .withMaxTolerableLightBrightness(1f)
        .withSpawnEgg(0x5A674F, 0x464039)
        .withTexturedModelVariant("com.paneedah.mwc.models.turretsilenced", "turretsilenced.png")
        .withAmbientSound("turret_turn")
//        .withStepSound("step")
        .withMaxSpeed(0.0F) // 0.1-0.3 is normal speed
        .withAiTask(1, e -> new EntityAIAttackRangedWeapon((EntityCustomMob)e, 1.0D, 1, 50.0F))
        .withAiTask(2, e -> new EntityAILookIdle(e))
        .withCollidability(false)
        .withDespawnability(false)
        .withPushability(false)
        .withInvulnerability()
        .withLookHeightMulitplier(1.5f)
        .withSize(1f, 0.7f)
        .withPickupItemID(3)
        
        .withAiTargetTask(1, e -> new EntityAIHurtByTarget((EntityCreature)e, false))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVillager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityHusk.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySkeleton.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpider.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEnderman.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityCreeper.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySlime.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityDragon.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityEndermite.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityBlaze.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityGhast.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityIllusionIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityMagmaCube.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityPigZombie.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntitySpellcasterIllager.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityStray.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityVindicator.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityWitch.class, true))
        .withAiTargetTask(3, e -> compatibility.createAINearestAttackableTarget(e, EntityZombieVillager.class, true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "soldier", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "terrorist", true))
        .withAiTargetTask(4, e -> new BetterAINearestAttackableTarget<>((EntityCreature) e, EntityCustomMob.class, "tyke", true))
        .register(ModernWarfareMod.MOD_CONTEXT);
        }
}
