# Creates a release on GitHub with a new tag of the current version
name: Java CI with Gradle
on:
  push:
    tags:
      - "*.*-*-*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Git Tags
        run: git fetch --prune --unshallow --tags

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: ".gradlew"
          generate-job-summary: false

      - name: Execute Gradle build
        run: ./gradlew build --stacktrace

      - name: Upload artifacts to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: mwc
          path: build/libs/*